/* Batch 02: original lessons drafted from topic coverage, then checked against official documentation.
   No purchased source text, questions, or illustrations are reproduced here. */
const COVERAGE_LESSONS = [
  {track:'frontend',group:'CSS 与布局',id:'css-cascade',title:'层叠、权重与样式覆盖',prompt:'一个更长的选择器为什么有时仍赢不了另一条规则？',core:'浏览器先按来源、重要性和层叠层确定候选规则，再比较同一优先层级内的选择器权重；仍相同时才看作用域距离与出现顺序。选择器“看起来长”不是完整判断依据。',why:'排查样式失效时，应先找出实际参与竞争的声明，避免不断叠加 !important。',example:'普通作者样式中，未分层规则可能覆盖层内更高权重的普通规则；同层内 #id 的权重通常高于 .class。',task:'在开发者工具中为同一元素写两条冲突的 color，分别改变层、选择器和顺序，记录胜出的规则。',answer:'先比较来源、重要性和层；这些相同后才比较权重，最后才用距离与顺序打破平局。',keywords:'CSS cascade specificity layer 选择器 权重 层叠',deep:[{title:'先判断比赛资格',body:'不同来源、important 声明或层叠层中的规则，不应只拿选择器分数直接比较。'},{title:'控制复杂度',body:'用清晰的层级、较低的选择器权重和语义类名，比不断追加覆盖规则更容易维护。'}]},
  {track:'frontend',group:'CSS 与布局',id:'css-stacking',title:'层叠上下文与 z-index',prompt:'子元素 z-index:9999 为什么仍盖不过旁边的弹层？',core:'层叠上下文会把内部后代作为一个整体参与父上下文的排序。子元素的 z-index 只能在所属上下文内竞争，无法直接越过父上下文与外部兄弟比较。',why:'弹窗、下拉菜单被遮挡时，单纯把数字调大可能完全无效。',example:'A 容器 z-index:1、B 容器 z-index:2，各自建立上下文；A 的子元素设为 9999 仍受 A 所在层级限制。',task:'创建两个定位容器和一个弹层，逐级检查 transform、opacity、position 与 z-index。',answer:'先找最近的层叠上下文和两个兄弟上下文的相对顺序，再决定是否提升容器或使用合适的顶层机制。',keywords:'CSS stacking context z-index transform opacity 弹层'},
  {track:'frontend',group:'CSS 与布局',id:'css-flex',title:'Flex 项为什么不按 width 收缩',prompt:'两个 width 相同的 Flex 子项，最终宽度为什么可能不同？',core:'Flex 布局以 flex-basis 形成初始主轴尺寸，再按 grow、shrink 分配空闲或不足空间；内容的固有最小尺寸也可能阻止进一步收缩。width 只是参与某些基准计算，并非最终宽度保证。',why:'布局溢出通常来自基准尺寸、收缩因子和 min-width，而不只是“百分比算错”。',example:'长字符串或代码块所在的 Flex 项可能因 min-width:auto 而撑开容器；在合适的子项设置 min-width:0 后才能继续收缩。',task:'用两个子项比较 flex:1 与 flex:1 1 auto，加入长文本后再测试 min-width:0。',answer:'检查 flex-basis、可分配空间和固有最小尺寸；min-width:0 允许该项小于其自动最小尺寸。',keywords:'CSS flex-basis flex-shrink min-width overflow 弹性布局'},
  {track:'frontend',group:'浏览器',id:'fetch-abort',title:'Fetch 取消与过期响应',prompt:'搜索框连续发送 A、B 请求，A 最后返回时怎样避免覆盖 B？',core:'AbortController 可把取消信号传给 fetch，停止不再需要的请求；但已完成的响应、其它异步步骤和业务回调仍需检查“这是不是最新一次搜索”。取消资源与拒绝过期结果是两个边界。',why:'只用 loading 状态无法解决竞态，慢请求可能把新结果覆盖为旧结果。',example:'每次输入创建新的 controller，先取消上次请求；处理结果前再比较请求序号。',task:'人为让第一次请求比第二次慢，分别测试仅取消和仅检查序号的行为。',answer:'过期请求应不再更新界面；可同时取消无用网络工作并在提交结果时核对最新请求身份。',keywords:'fetch AbortController race stale response 请求竞态'},
  {track:'frontend',group:'网络与安全',id:'http-methods',title:'HTTP 方法：安全与幂等',prompt:'POST 一定不幂等，而 DELETE 一定能无条件重试吗？',core:'HTTP 的安全和幂等描述方法的语义约定：安全方法不应请求改变服务器状态；幂等方法重复执行的预期效果与一次执行相同。业务副作用、鉴权、失败窗口和响应内容仍须具体设计。',why:'重试策略不能只看方法名称，还要看资源状态、唯一键和服务器实现。',example:'DELETE 同一资源两次可都使资源最终不存在，但第二次的状态码可以不同；创建订单的 POST 需业务幂等键避免重复订单。',task:'为查询、覆盖更新、扣款三个接口分别说明方法、重试条件和服务器防重措施。',answer:'查询适合安全读取；覆盖式 PUT 可设计为幂等；扣款必须以业务键和持久化约束保护重试。',keywords:'HTTP safe idempotent GET PUT DELETE POST 重试'},
  {track:'frontend',group:'网络与安全',id:'http-range',title:'Range 请求与断点续传',prompt:'客户端下载了前半段文件后，凭什么能安全接着下载？',core:'Range 请求指定所需字节区间，服务器可用 206 Partial Content 和 Content-Range 返回片段。续传前还应核对资源标识或验证器，防止文件已改变却把新旧片段拼在一起。',why:'大文件下载、媒体拖动和断线恢复都依赖部分内容语义与完整性校验。',example:'客户端请求 bytes=1000-；若服务器返回 200 全量响应，就不能盲目把内容追加到旧文件。',task:'模拟服务端分别返回 206、200 与 416，设计客户端如何保存或重启下载。',answer:'206 且区间和版本匹配时追加；200 按完整表示重新处理；416 检查当前文件长度和资源状态。',keywords:'HTTP Range 206 Content-Range If-Range 断点续传'},
  {track:'frontend',group:'浏览器',id:'browser-storage',title:'localStorage 与跨标签页状态',prompt:'同一页面调用 localStorage.setItem 后会收到自己的 storage 事件吗？',core:'localStorage 按源保存数据，storage 事件通知共享该存储区的其他文档，不在执行写入的当前文档触发。它适合少量客户端偏好，不是可靠的跨标签页事务或服务端真相来源。',why:'多标签页状态同步需要明确谁写入、谁监听，以及冲突时如何决定较新版本。',example:'标签 A 更新主题，标签 B 监听 storage 并刷新主题；A 自己应直接更新界面。',task:'打开两个同源标签页，记录 A 写入后两个页面的事件与显示状态。',answer:'B 能收到 storage 事件；A 不会收到自己的事件，应在写入逻辑中直接更新状态。',keywords:'localStorage storage event same origin tabs 本地存储'},
  {track:'frontend',group:'Node.js',id:'node-stream',title:'Node Stream 与背压',prompt:'不断调用 writable.write 会自动把内存控制在固定上限吗？',core:'write 返回 false 表示内部缓冲达到阈值，生产方应暂停，等待 drain 后再继续。继续写通常仍会缓冲数据，可能造成内存和延迟失控；pipeline 可协调流转与错误传播。',why:'文件、网络和压缩处理的生产速度不同，必须让慢消费者反向约束快生产者。',example:'读大文件并写入慢连接时，逐块读写且尊重 write 的返回值，比一次性读入内存更稳定。',task:'构造一个低速 Writable，对比忽略 false 与等待 drain 时的缓冲增长。',answer:'等待 drain 或用 pipeline 协调流；同时处理错误、关闭和取消。',keywords:'Node.js Stream backpressure highWaterMark drain pipeline 背压'},
  {track:'frontend',group:'Node.js',id:'node-emitter',title:'EventEmitter 的同步派发与错误',prompt:'emit 之后才打印日志，监听器会先执行吗？',core:'EventEmitter 通常按注册顺序同步调用监听器，emit 返回后才继续执行调用方后续代码。once 只监听下一次事件；未处理的 error 事件有特殊失败行为。',why:'把事件派发误当异步队列，会错误判断调用顺序和异常边界。',example:'先注册 on("ready", handler)，再 emit("ready")，handler 在 emit 返回前运行。',task:'给同一事件注册两个 on 和一个 once，连续 emit 两次并记录顺序；再测试 error 事件。',answer:'普通监听器每次按注册顺序同步运行，once 只运行一次；error 应有明确的错误处理路径。',keywords:'Node.js EventEmitter emit on once error 同步事件'},
  {track:'frontend',group:'Node.js',id:'node-buffer',title:'Buffer 的字节与初始化边界',prompt:'Buffer.allocUnsafe(10) 的十个字节为什么不能直接发给客户端？',core:'Buffer 表示原始字节；alloc 初始化内存，而 allocUnsafe 分配的内容未初始化。未写满就发送可能泄露残留数据。文本解码还需要明确编码与字节边界。',why:'文件上传、协议编解码和网络响应都操作字节，不能把字符数等同于字节数。',example:'中文字符的 UTF-8 编码可能占多个字节，Buffer.byteLength(str) 与 str.length 不必相等。',task:'比较 Buffer.alloc(8) 与 Buffer.allocUnsafe(8) 的初始化保证，再测一个中文字符串的字节长度。',answer:'前者填零；后者必须在对外使用前完整写入或显式填充。',keywords:'Node.js Buffer UTF-8 allocUnsafe bytes 字节'},
  {track:'frontend',group:'Node.js',id:'node-nexttick',title:'Node 的 nextTick 与微任务',prompt:'把 nextTick 理解成浏览器微任务，为什么会误判执行顺序？',core:'Node 有 next tick 队列与 Promise/queueMicrotask 使用的微任务队列。它们在不同模块上下文中的相对顺序可能不同，递归排入 nextTick 还会延迟事件循环推进。',why:'服务器端调度问题要以 Node 的实际运行环境和版本验证，不能照搬浏览器事件循环图。',example:'CommonJS 顶层与 ES Module 顶层比较 nextTick 和 queueMicrotask 的日志顺序，结果可能不同。',task:'分别在 CJS 与 ESM 运行同一组 nextTick、Promise.then 和同步日志，记录顺序。',answer:'先区分同步执行、模块求值上下文和 Node 的队列；不要把某一段日志顺序泛化到所有场景。',keywords:'Node process.nextTick queueMicrotask Promise event loop'},
  {track:'frontend',group:'网络与安全',id:'http-compression',title:'HTTP 压缩协商与缓存',prompt:'服务器对同一 URL 返回 gzip 和未压缩版，缓存怎样区分？',core:'客户端用 Accept-Encoding 声明可接受的内容编码，服务端用 Content-Encoding 说明实际响应编码。若同一 URL 按该请求头变化，缓存应依据 Vary: Accept-Encoding 区分表示。',why:'压缩配置错误可造成内容无法解码、缓存混用或带宽浪费。',example:'HTML 通常适合文本压缩；已压缩的 JPEG 再通用压缩收益可能很小。',task:'对比浏览器发送 Accept-Encoding、服务端的 Content-Encoding 与 Vary，解释缓存键。',answer:'编码是响应表示的一部分；Vary 告知缓存哪些请求头参与选择表示。',keywords:'HTTP compression gzip br Accept-Encoding Content-Encoding Vary'},
  {track:'java',group:'JVM',id:'jvm-areas',title:'JVM 运行时数据区：规范与实现',prompt:'JVM 的程序计数器是不是 CPU 寄存器里“下一条机器指令地址”？',core:'JVM 规范定义每个线程有自己的 pc 寄存器：执行非 native 方法时记录当前 JVM 指令地址；执行 native 方法时其值未定义。它是抽象机的运行时数据区，不应直接等同 CPU 物理程序计数器。虚拟机栈、堆和方法区也需按规范与具体实现区分。',why:'旧面试资料常把 JVM 抽象结构、HotSpot 内存实现和 CPU 硬件混在一张图里，导致排障时选错指标。',example:'方法调用创建栈帧；对象与数组通常在 JVM 堆中；类元数据相关结构属于方法区语义，但具体放置由实现决定。',task:'画出线程私有与共享区域，并标注哪些是 JVM 规范定义、哪些是特定虚拟机实现。',answer:'pc 与 Java 虚拟机栈属于每线程区域；堆和方法区由线程共享。不要把“方法区=某块固定物理内存”当作规范。',keywords:'JVM pc register stack heap method area 运行时数据区',origin:'《JVM内存区域划分.pdf》的运行时数据区章节',deep:[{title:'规范层',body:'JVM 规范描述可观察的逻辑区域与行为边界，例如 pc、虚拟机栈、堆和方法区。'},{title:'实现层',body:'具体虚拟机可以用不同内存布局和优化策略实现这些语义；调优参数与异常信息需要绑定实际实现及版本。'}]},
  {track:'java',group:'JVM',id:'java-classloading',title:'类加载器与类身份',prompt:'两个同名同字节码类为什么可能不能互相强转？',core:'Java 类的运行时身份涉及类的二进制名称和定义它的类加载器。常见类加载器按父委派寻找类，但自定义加载器可改变加载路径；仅看类名不足以判断是否同一类型。',why:'插件隔离、应用容器和热更新问题常是类加载器边界问题。',example:'两个隔离加载器分别定义 com.demo.User，打印名称相同，运行时类型却不同。',task:'用两个自定义加载器加载同一类，打印各自 ClassLoader 并尝试转换。',answer:'先比较定义类加载器，再判断类型身份；类名相同不能保证强转成功。',keywords:'Java ClassLoader delegation type identity 类加载器'},
  {track:'java',group:'Java 基础',id:'java-stream',title:'Stream 懒执行与副作用',prompt:'只调用 map 却没有终端操作，转换函数会运行吗？',core:'Java Stream 的中间操作形成延迟执行的流水线，通常在终端操作启动后才按需要处理元素。实现可进行优化；不要依赖中间操作中的副作用一定运行或运行固定次数。',why:'用 peek 或 map 偷偷修改外部状态，容易因短路、并行或优化造成不稳定结果。',example:'list.stream().map(x -> x * 2) 本身不会产生一个已计算的新 List；需要 collect 或 toList 等终端操作。',task:'给 Stream 加 filter、map、findFirst 和日志，观察哪些元素真正经过各步。',answer:'短路操作可能只处理找到结果所需的前缀；中间操作不是立即完整遍历。',keywords:'Java Stream lazy intermediate terminal short circuit 懒执行'},
  {track:'java',group:'并发',id:'java-interrupt',title:'线程中断是协作信号',prompt:'调用 Thread.interrupt() 会立即“杀死”目标线程吗？',core:'interrupt 是中断请求，不是强制终止。部分阻塞方法抛 InterruptedException 并清除中断标志；普通计算代码需主动检查并决定退出或继续。吞掉异常会丢失取消信号。',why:'线程池关闭、任务取消和超时传播都依赖一致的中断处理约定。',example:'循环任务定期检查 isInterrupted；捕获 InterruptedException 后若不能继续向上抛，可恢复中断标志并退出。',task:'写一个 sleep 循环任务，调用 interrupt 后比较“直接吞异常”与“退出并恢复标志”的结果。',answer:'正确响应取决于任务契约，但不能假设 interrupt 会立即强杀；应传播或明确处理取消。',keywords:'Java Thread interrupt InterruptedException cancellation 中断'},
  {track:'java',group:'并发',id:'java-future-errors',title:'CompletableFuture 的错误恢复',prompt:'whenComplete 打印了异常，后续阶段就恢复正常了吗？',core:'whenComplete 主要观察完成结果，通常不会把原有异常替换成正常值；exceptionally 可从异常产生替代结果，handle 同时接收结果与异常并计算新结果。不同 *Async 方法还涉及执行器选择。',why:'把“记录错误”和“恢复错误”混淆，会让请求链在日志之后继续异常完成。',example:'supplyAsync 抛错后，whenComplete 记录原因，后续 join 仍会异常；加 exceptionally 返回默认值才形成恢复分支。',task:'分别用 whenComplete、exceptionally、handle 处理同一个失败 Future，观察下游完成状态。',answer:'明确是观察、替代结果还是统一变换；记录日志本身不等于恢复。',keywords:'CompletableFuture whenComplete exceptionally handle async errors'},
  {track:'java',group:'并发',id:'java-concurrent-map',title:'ConcurrentHashMap 的复合操作',prompt:'先 get，发现没有，再 put，就保证只初始化一次吗？',core:'即使用线程安全 Map，两次独立操作之间也可能被其他线程插入。需要单个原子复合操作，如 putIfAbsent 或 ConcurrentHashMap.computeIfAbsent；映射函数应保持简短且避免递归修改同一 Map。',why:'线程安全容器不自动把业务上的“读—算—写”序列变成原子事务。',example:'两个线程同时 get(key)==null，都去昂贵地创建对象；使用 computeIfAbsent 可让该键的计算与插入受容器协调。',task:'并发运行两个初始化任务，统计创建函数调用次数并检查最终值。',answer:'使用具体 API 的原子语义设计，同时考虑计算失败、空返回与函数副作用。',keywords:'ConcurrentHashMap computeIfAbsent putIfAbsent atomic 复合操作'},
  {track:'java',group:'并发',id:'java-reentrant-lock',title:'显式锁与 try/finally',prompt:'使用 ReentrantLock 时，异常会自动释放锁吗？',core:'Lock 接口不会因为离开作用域自动释放。成功获取锁后应在 finally 中 unlock；tryLock 可以避免无限等待或执行替代路径。公平锁配置也不意味着所有获取方式都严格排队。',why:'漏掉 unlock 会让其他线程长期阻塞，吞掉中断或锁超时也会掩盖过载。',example:'lock.lock(); try { update(); } finally { lock.unlock(); } 保证更新抛异常时仍释放锁。',task:'让更新函数抛异常，比较有无 finally 时另一线程能否获得同一锁。',answer:'获取成功后才进入保护区，并在 finally 释放；若获取失败，不应调用 unlock。',keywords:'Java ReentrantLock tryLock unlock finally fairness 显式锁'},
  {track:'java',group:'框架',id:'spring-scopes',title:'Spring Bean 作用域与共享状态',prompt:'给一个 Spring Bean 标了 singleton，就等于它的字段线程安全吗？',core:'Spring singleton 表示同一容器中该 Bean 定义通常对应一个共享实例，不提供字段的并发保护。prototype 是按获取创建实例；request 等作用域绑定 Web 上下文。作用域决定实例生命周期，不直接决定业务状态安全。',why:'把用户请求数据放进共享单例字段，可能让不同请求互相覆盖。',example:'无状态 Service 可作为 singleton；每请求草稿应放在方法局部变量、请求对象或合适作用域中。',task:'检查一个 Service 是否把 currentUser 存为成员字段，并设计并发请求测试。',answer:'共享 Bean 字段若可变且由并发请求读写，需要同步或改为请求内状态；仅改注解不能替代建模。',keywords:'Spring bean singleton prototype request scope thread safety'},
  {track:'java',group:'数据库',id:'mysql-deadlock',title:'InnoDB 死锁与整笔事务重试',prompt:'出现死锁后，只重发最后一条 UPDATE 就够了吗？',core:'InnoDB 检测到死锁时会回滚一个受害事务；应用需要重试整笔事务，而不是只补最后一条语句。锁等待超时的默认回滚范围又可能不同，应按错误类别处理。',why:'订单和余额操作不能在事务被回滚后误以为前面的写入还在。',example:'事务 T1 更新 A 后更新 B，T2 反向更新；死锁后某事务整笔回滚，重试必须重新读取并执行完整业务步骤。',task:'用两个连接反向更新两行制造死锁，记录受害事务状态和重试结果。',answer:'捕获死锁，按有界次数和退避重跑整个事务；同时统一加锁顺序、缩短事务来减少冲突。',keywords:'MySQL InnoDB deadlock retry transaction rollback 死锁'},
  {track:'java',group:'缓存',id:'redis-persistence',title:'Redis 持久化与数据丢失窗口',prompt:'打开 AOF 后，Redis 每次写成功都意味着磁盘绝不会丢数据吗？',core:'Redis 的 RDB 是时间点快照，AOF 记录写操作；实际持久性取决于 fsync 策略、重写、故障方式和部署。不能只凭“开启 AOF”承诺零丢失。',why:'缓存、会话和库存数据的恢复目标不同，必须明确可接受的数据损失与重建方式。',example:'每秒同步 AOF 的策略在崩溃时仍可能有最近一小段已确认写入未落盘；若业务不能容忍，需使用更强的权威存储设计。',task:'为可重建商品缓存与不可重复扣减的账务记录分别选择权威数据源和恢复策略。',answer:'商品缓存可由数据库重建；账务正确性不能只依赖 Redis 本机持久化，应以有事务保证的权威系统维护。',keywords:'Redis RDB AOF fsync durability persistence 持久化'}
];

const COVERAGE_POINTS = {
  'css-cascade':['来源、重要性与层叠层','选择器权重和作用域距离','样式覆盖的调试顺序'],
  'css-stacking':['哪些属性建立层叠上下文','子元素 z-index 的局部边界','弹层遮挡的排查路径'],
  'css-flex':['flex-basis 的初始尺寸','grow 与 shrink 的分配','自动最小尺寸和 min-width:0'],
  'fetch-abort':['AbortController 取消网络工作','旧响应覆盖新结果的竞态','提交结果时核对请求身份'],
  'http-methods':['安全方法与幂等方法','方法语义和实际业务副作用','失败重试与幂等键'],
  'http-range':['Range 与 206 部分响应','Content-Range 校验区间','资源变更时的续传安全'],
  'browser-storage':['localStorage 的同源范围','storage 事件只通知其他文档','跨标签页状态冲突'],
  'node-stream':['Writable.write 返回 false','drain 与生产者背压','pipeline 的错误和关闭处理'],
  'node-emitter':['emit 同步执行监听器','on 与 once 的生命周期','error 事件的特殊处理'],
  'node-buffer':['字符数与 UTF-8 字节数','Buffer.alloc 的初始化','allocUnsafe 的数据泄露边界'],
  'node-nexttick':['next tick 队列与微任务队列','CJS 和 ESM 的上下文差异','递归调度导致事件循环饥饿'],
  'http-compression':['Accept-Encoding 内容协商','Content-Encoding 响应编码','Vary 与缓存表示区分'],
  'jvm-areas':['JVM pc 寄存器不是 CPU 寄存器','线程私有的栈与栈帧','共享堆与方法区的规范语义'],
  'java-classloading':['类名与定义加载器组成身份','常见父委派查找路径','插件隔离与类型转换失败'],
  'java-stream':['中间操作的懒执行','终端操作与短路','副作用不可依赖固定执行次数'],
  'java-interrupt':['interrupt 是协作请求','InterruptedException 与标志清除','取消信号的传播与恢复'],
  'java-future-errors':['whenComplete 观察完成','exceptionally 替代失败结果','handle 统一处理正常和异常'],
  'java-concurrent-map':['线程安全单操作与业务复合操作','computeIfAbsent 原子计算','映射函数副作用和异常'],
  'java-reentrant-lock':['显式获取和释放锁','finally 防止异常泄锁','tryLock 与公平性边界'],
  'spring-scopes':['singleton 是容器内共享实例','prototype 与 request 生命周期','共享可变字段的并发风险'],
  'mysql-deadlock':['交叉加锁形成等待环','死锁回滚整笔事务','有界重试与统一加锁顺序'],
  'redis-persistence':['RDB 快照与 AOF 日志','fsync 策略决定丢失窗口','缓存与权威数据的恢复目标']
};

const COVERAGE_REFERENCES = {
  'css-cascade':[['MDN：CSS Cascade','https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascade/Introduction'],['MDN：Specificity','https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Cascade/Specificity']],
  'css-stacking':[['MDN：Stacking context','https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Positioned_layout/Stacking_context']],
  'css-flex':[['MDN：Flexbox 基础','https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Flexible_box_layout/Basic_concepts'],['MDN：Flex 项比例','https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Flexible_box_layout/Controlling_flex_item_ratios']],
  'fetch-abort':[['MDN：AbortController','https://developer.mozilla.org/en-US/docs/Web/API/AbortController'],['MDN：Fetch API','https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch']],
  'http-methods':[['RFC 9110：HTTP Semantics','https://www.rfc-editor.org/rfc/rfc9110.html#section-9.2']],
  'http-range':[['MDN：Range requests','https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Range_requests'],['RFC 9110：Range Requests','https://www.rfc-editor.org/rfc/rfc9110.html#section-14']],
  'browser-storage':[['MDN：storage event','https://developer.mozilla.org/en-US/docs/Web/API/Window/storage_event'],['MDN：localStorage','https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage']],
  'node-stream':[['Node.js：Stream','https://nodejs.org/api/stream.html']],
  'node-emitter':[['Node.js：Events','https://nodejs.org/api/events.html']],
  'node-buffer':[['Node.js：Buffer','https://nodejs.org/api/buffer.html']],
  'node-nexttick':[['Node.js：process.nextTick','https://nodejs.org/api/process.html#processnexttickcallback-args']],
  'http-compression':[['MDN：Compression in HTTP','https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Compression']],
  'jvm-areas':[['JVM 规范：运行时数据区','https://docs.oracle.com/javase/specs/jvms/se25/html/jvms-2.html#jvms-2.5']],
  'java-classloading':[['Oracle：ClassLoader','https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/lang/ClassLoader.html']],
  'java-stream':[['Oracle：Stream','https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/util/stream/Stream.html']],
  'java-interrupt':[['Oracle：Thread.interrupt','https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/lang/Thread.html#interrupt()']],
  'java-future-errors':[['Oracle：CompletionStage','https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/util/concurrent/CompletionStage.html']],
  'java-concurrent-map':[['Oracle：ConcurrentHashMap','https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/util/concurrent/ConcurrentHashMap.html']],
  'java-reentrant-lock':[['Oracle：ReentrantLock','https://docs.oracle.com/en/java/javase/25/docs/api/java.base/java/util/concurrent/locks/ReentrantLock.html']],
  'spring-scopes':[['Spring：Bean Scopes','https://docs.spring.io/spring-framework/reference/core/beans/factory-scopes.html']],
  'mysql-deadlock':[['MySQL 8.4：InnoDB Deadlocks','https://dev.mysql.com/doc/refman/8.4/en/innodb-deadlocks.html'],['MySQL 8.4：Error Handling','https://dev.mysql.com/doc/refman/8.4/en/innodb-error-handling.html']],
  'redis-persistence':[['Redis：Persistence','https://redis.io/docs/latest/operate/oss_and_stack/management/persistence/']]
};

for (const lesson of COVERAGE_LESSONS) {
  window.LESSONS.push(lesson);
  window.KNOWLEDGE_POINTS[lesson.id]=COVERAGE_POINTS[lesson.id];
  window.LESSON_REFERENCES[lesson.id]=COVERAGE_REFERENCES[lesson.id];
}
