/* Second path pass: mechanisms the first 128 lessons still left unconnected. */
const COVERAGE_PATH_02 = [
  {
    track:'frontend', group:'浏览器', id:'dom-event-flow',
    title:'事件先捕获，再到达目标，然后冒泡',
    prompt:'点在按钮上，为什么父元素的监听器也会执行？',
    core:'一次 DOM 事件先从 window 走到目标（捕获），在目标上触发，再按原路返回（冒泡）。eventPhase 用 1、2、3 区分这三段。监听器默认在冒泡阶段。stopPropagation 阻止事件继续传到别的节点，同一节点上其余监听器仍会运行。stopImmediatePropagation 还会停掉当前节点上尚未运行的监听器。focus、blur 等事件不冒泡，不能靠父元素监听它们来做事件委托。',
    why:'弹层、列表和文档级快捷键叠在一起时，先分清事件走到了哪一段，再决定拦在哪一层。',
    example:'文档上监听 click 可以处理后来插入的按钮。把监听器写成捕获阶段，它会在按钮自己的 click 之前运行。按钮里调用 stopPropagation 后，文档上的冒泡监听器不再运行。',
    task:'在祖先、目标和文档上分别注册捕获与冒泡监听，记录顺序；再分别调用两种 stop 方法，看同一节点上的第二个监听器是否还在。',
    answer:'顺序是捕获、目标、冒泡。stopPropagation 停的是后续节点。stopImmediatePropagation 连当前节点剩下的监听器一起停。不冒泡的事件不能委托到祖先。',
    keywords:'DOM eventPhase capture bubble stopPropagation 事件委托',
    points:['事件按捕获、目标、冒泡三段传播','stopPropagation 不停掉同一节点的其他监听器','不冒泡的事件不能用父元素做委托'],
    refs:[['MDN：eventPhase','https://developer.mozilla.org/en-US/docs/Web/API/Event/eventPhase'],['MDN：stopPropagation','https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation']]
  },
  {
    track:'frontend', group:'CSS 与布局', id:'css-containing-block',
    title:'fixed 不一定相对视口',
    prompt:'元素写了 position:fixed，为什么没有贴在窗口上？',
    core:'绝对定位和固定定位的参照物是包含块，不是永远是视口。position 不是 static 的祖先可以成为包含块。transform、filter、perspective、contain 或 will-change 为 transform 的祖先也会成为 fixed 元素的包含块。这时 fixed 相对那个祖先，而不是窗口。top、right、bottom、left 的百分比也相对这个包含块。',
    why:'弹层被裁切或跟着某张卡片滚动时，先找最近的包含块，而不是把 z-index 越调越大。',
    example:'对话框用 position:fixed; inset:0。若外层卡片写了 transform:translateZ(0)，对话框会相对卡片铺满，页面滚动时它跟着卡片走。',
    task:'给固定定位元素的某一层祖先分别加上 transform 和 position:relative，用开发者工具看包含块变成了谁。',
    answer:'fixed 的包含块可以被 transform 等属性改到某个祖先上。先去掉或挪开那个属性，再谈相对视口定位。',
    keywords:'CSS containing block position fixed transform 包含块',
    points:['绝对定位和固定定位参照包含块','transform 等属性会让 fixed 脱离视口','偏移的百分比相对包含块计算'],
    refs:[['MDN：包含块','https://developer.mozilla.org/en-US/docs/Web/CSS/Guides/Display/Containing_block'],['MDN：position','https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Properties/position']]
  },
  {
    track:'frontend', group:'网络与安全', id:'http-status-auth',
    title:'401 是没证明身份，403 是不许做',
    prompt:'登录失败和登录后没有权限，为什么不该都返回 403？',
    core:'401 表示请求缺少可被接受的认证，或认证未被接受。响应可以带 WWW-Authenticate，告诉客户端用什么方式再证明身份。403 表示服务器已经理解请求，但拒绝执行。用户已经登录、只是没有该操作的权限时，用 403，而不是再要求登录。把两种失败都写成 200 再在 JSON 里塞错误码，缓存和中间层就看不出这次调用失败了。',
    why:'前端据此决定是弹出登录，还是显示无权限。网关和监控也靠状态码区分失败类型。',
    example:'没有会话的管理接口返回 401。普通用户调用停用账号返回 403。校验失败的字段用 400，并在正文里说明哪个字段。',
    task:'为未登录、已登录但缺权限、参数不合法三种请求各选一个状态码，并说明客户端下一步做什么。',
    answer:'未登录用 401，已认证但被拒绝用 403，参数问题用 400。不要用 200 表示这些失败。',
    keywords:'HTTP 401 403 WWW-Authenticate 认证 授权',
    points:['401 表示需要或拒绝了认证','403 表示已理解请求但拒绝授权','失败不要伪装成 200'],
    refs:[['MDN：401','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/401'],['MDN：403','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/403']]
  },
  {
    track:'frontend', group:'网络与安全', id:'fetch-credentials',
    title:'跨源 Cookie 要两边一起允许',
    prompt:'fetch 写了 credentials:include，为什么 Cookie 还是没带到另一个源？',
    core:'fetch 的 credentials 默认是 same-origin，只在同源请求上带 Cookie。include 才会在跨源请求里带上。浏览器要读到这个跨源响应，服务器必须返回 Access-Control-Allow-Credentials: true，并且 Access-Control-Allow-Origin 是具体源，不能是星号。预检请求也要允许这一点。只改前端、不改响应头，脚本仍然读不到响应。',
    why:'登录态跨站点时，漏掉任意一边都会表现为“明明登录了，接口却像匿名”。',
    example:'页面在 app.example，接口在 api.example。fetch 使用 include。接口响应 Allow-Origin 为 https://app.example，并带上 Allow-Credentials。',
    task:'分别用默认 credentials、include 加星号源、include 加具体源，记录请求是否带 Cookie、脚本是否读得到正文。',
    answer:'跨源带 Cookie 需要 include，以及具体的 Allow-Origin 和 Allow-Credentials。星号和凭证不能同时成立。',
    keywords:'fetch credentials CORS Access-Control-Allow-Credentials Cookie',
    points:['credentials 默认只在同源发送 Cookie','跨源携带凭证时 Allow-Origin 不能是星号','响应还要显式允许凭证'],
    refs:[['MDN：使用 Fetch','https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch'],['MDN：Access-Control-Allow-Credentials','https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Access-Control-Allow-Credentials']]
  },
  {
    track:'frontend', group:'React', id:'react-error-boundary',
    title:'错误边界只管渲染，不管点击里的异步',
    prompt:'组件出错了，为什么错误边界有时完全看不到？',
    core:'React 的错误边界是类组件，用 getDerivedStateFromError 或 componentDidCatch 接住子树在渲染、生命周期和构造函数里抛出的错误。它接不住事件处理函数、异步回调、服务端渲染，也接不住边界自己渲染时抛出的错误。点击里的请求失败要在事件或 Promise 路径上处理。渲染期间读到坏数据，才由边界换成备用界面。',
    why:'只在根上套一个边界，仍会漏掉按钮点击和请求失败，用户看到的是未处理拒绝，不是备用界面。',
    example:'子组件渲染时读取 user.name，user 为空，边界可以显示“这段暂时不可用”。按钮 onClick 里的 await 失败，必须在点击函数里捕获。',
    task:'分别在渲染期间、点击回调和 Promise 拒绝里抛错，记录哪一次能被错误边界接住。',
    answer:'只有渲染和生命周期中的错误进入边界。事件和异步错误留在各自的调用路径里处理。',
    keywords:'React error boundary componentDidCatch 渲染错误 事件处理',
    points:['错误边界接住子树渲染和生命周期中的异常','事件处理和异步代码不经过边界','边界自身的渲染错误需要上层边界'],
    refs:[['React：错误边界','https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary']]
  },
  {
    track:'frontend', group:'Vue', id:'vue-props-one-way',
    title:'子组件改 prop，父组件不会跟着变',
    prompt:'在子组件里给 props 赋值，为什么父组件的数据没变，控制台却出现警告？',
    core:'Vue 的 prop 是单向的：父组件把数据传下来，子组件把它当输入。直接改 prop 会触发警告，也不能当成修改父状态的办法。子组件用 emit 发出事件，由父组件决定是否改自己的状态，再把新值传下来。需要一份可编辑的本地副本时，用本地状态接初始值，并在父数据变化时同步；不要把 prop 本身当成子组件的私有可变状态。',
    why:'双向偷偷改对象，会让数据来源变多，父组件无法解释子组件为什么变了。',
    example:'子组件收到 title。用户编辑时 emit update:title，父组件写入自己的 ref。子组件继续通过 prop 显示最新标题。',
    task:'在子组件直接改一个对象 prop 的字段，再改成 emit。比较父组件是否更新，以及有没有变异警告。',
    answer:'输入用 prop，变更用事件。父组件拥有状态。子组件不把 prop 当作自己的可写状态。',
    keywords:'Vue props emit 单向数据流 v-model',
    points:['prop 从父组件流向子组件','子组件用事件请求变更，不直接写 prop','本地副本要在父数据变化时再同步'],
    refs:[['Vue：Props 单向数据流','https://vuejs.org/guide/components/props.html'],['Vue：组件事件','https://vuejs.org/guide/components/events.html']]
  },
  {
    track:'frontend', group:'工程实践', id:'web-vitals',
    title:'先看三次用户可见的等待',
    prompt:'打包体积小了，就能说明页面变快了吗？',
    core:'Core Web Vitals 量的是用户看得见的结果。LCP 是视口里最大内容绘制出来的时间。INP 是交互到下一次绘制的延迟，用来代替已经退出主指标的 FID。CLS 是意外布局偏移的累计。它们不由包体积直接决定。大图、字体、长任务和没有尺寸的图片会分别拉高这三项。实验数据说明一次访问，现场数据说明真实用户分布。',
    why:'优化若只比较构建产物的 KB，可能让实验室分数上升，而用户仍在等主内容或忍受页面跳动。',
    example:'首屏英雄图没有宽高，CLS 升高。主线程在点击时跑一段长任务，INP 升高。图很大且发现得晚，LCP 升高。',
    task:'用一次性能记录指出 LCP 元素、一次交互的长任务，以及造成偏移的节点，再分别改一项并复测。',
    answer:'LCP 看主要内容何时出现，INP 看交互后多久有绘制，CLS 看布局是否乱跳。三项分开测。',
    keywords:'Core Web Vitals LCP INP CLS 性能',
    points:['LCP 衡量最大内容何时绘制','INP 衡量交互到下一次绘制','CLS 累计意外的布局偏移'],
    refs:[['MDN：LCP','https://developer.mozilla.org/en-US/docs/Glossary/Largest_contentful_paint'],['MDN：INP','https://developer.mozilla.org/en-US/docs/Glossary/Interaction_to_next_paint'],['MDN：CLS','https://developer.mozilla.org/en-US/docs/Glossary/CLS']]
  },
  {
    track:'frontend', group:'安全', id:'client-env-public',
    title:'打进前端包里的变量不是秘密',
    prompt:'把数据库密码写成 VITE_DB_PASSWORD，构建之后它还安全吗？',
    core:'Vite 只会把以 VITE_ 开头的环境变量静态替换进客户端代码，通过 import.meta.env 读取。替换发生在构建时，产物是任何打开页面的人都能下载的脚本。模式文件和 .env.local 决定构建时读到哪一组值，不提供运行时保密。密钥、数据库口令和私钥只能留在服务器。前端可以持有的是公开的站点地址、分析编号，以及设计成可公开的客户端标识。',
    why:'把秘密放进前端环境变量，等于把它发布到每个用户的浏览器。',
    example:'VITE_API_URL 可以进包。数据库密码只放在服务端进程的环境里，由接口在服务器上使用。',
    task:'构建后在产物里搜索一个 VITE_ 变量的值，确认它已经是明文；再确认没有 VITE_ 前缀的变量不会出现在客户端代码里。',
    answer:'进客户端包的值都是公开的。秘密留在服务器。VITE_ 前缀只是暴露开关，不是加密。',
    keywords:'Vite import.meta.env VITE_ 环境变量 前端密钥',
    points:['只有 VITE_ 前缀会进入客户端代码','这些值在构建时被写进可下载的脚本','密钥不能放进前端环境变量'],
    refs:[['Vite：环境变量与模式','https://vite.dev/guide/env-and-mode.html']]
  },
  {
    track:'frontend', group:'Node.js', id:'node-worker-cluster',
    title:'多核要拆进程或工作线程，不是把事件循环变并行',
    prompt:'开了 cluster，主线程里的一个大循环就会用满所有 CPU 吗？',
    core:'Node 的 JavaScript 默认在一个线程的事件循环上运行。cluster 是多个进程，各自有自己的堆和事件循环，可以共享一个服务器端口。worker_threads 是同一进程里的额外线程，各自有自己的 JavaScript 堆，可以通过转移 ArrayBuffer 或消息传递数据，普通对象不会变成共享内存。两种方式都要明确任务怎么切分。一个进程里的死循环仍然占满它自己的那个线程。',
    why:'流量上来之后，若工作不能切开，加机器规格也不会让那一段同步计算变并行。',
    example:'每个 cluster 工作进程各自接受连接。CPU 密集的图片处理放到 Worker，把图像字节转移过去，完成后再把结果传回。',
    task:'用一个死循环占住主线程，同时发一个 HTTP 请求，记录它是否被堵住；再把死循环放进 Worker，比较请求是否还能返回。',
    answer:'cluster 用多进程分担连接。Worker 用消息或转移的内存做并行计算。都不会让同一个事件循环里的同步代码并行。',
    keywords:'Node.js cluster worker_threads 事件循环 多核',
    points:['一个事件循环不会把同步代码跑到多个核上','cluster 是多进程，各自有独立的堆','worker_threads 用消息或转移内存交换数据'],
    refs:[['Node.js：worker_threads','https://nodejs.org/api/worker_threads.html'],['Node.js：cluster','https://nodejs.org/api/cluster.html']]
  },
  {
    track:'java', group:'数据库', id:'sql-outer-join-where',
    title:'外连接的条件写进 WHERE，就变成内连接',
    prompt:'LEFT JOIN 之后为什么有的左表行消失了？',
    core:'LEFT JOIN 先保留左表每一行，右表没有匹配时用 NULL 补齐。若随后在 WHERE 里判断右表列等于某个值，NULL 的比较不是 TRUE，这些补齐行会被丢掉，结果和内连接一样。右表的匹配条件应写在 ON 里。左表自己的过滤可以写在 WHERE，因为它本来就不是要保留的“缺失”。选了右表列却用 WHERE 排除 NULL，就是在要回那些行。',
    why:'报表少了一部分客户或订单时，连接类型没写错，错的常常是条件放错了位置。',
    example:'要“全部客户及其 5 月订单，没有订单也列出客户”。订单月份放在 ON 里。若放进 WHERE，没有 5 月订单的客户会被过滤掉。',
    task:'准备有订单和没订单的客户，把月份条件分别放在 ON 和 WHERE，比较客户是否还在结果里。',
    answer:'外连接要保留的那一侧，不能靠 WHERE 去要求另一侧一定有值。另一侧的条件放在 ON。',
    keywords:'SQL LEFT JOIN ON WHERE 外连接 NULL',
    points:['左连接会用 NULL 补上没有匹配的右表','WHERE 里的比较会丢掉这些 NULL 行','右表条件放在 ON，才留得住左表'],
    refs:[['MySQL 8.4：JOIN','https://dev.mysql.com/doc/refman/8.4/en/join.html'],['MySQL 8.4 手册镜像：JOIN','https://docs.oracle.com/cd/E17952_01/mysql-8.4-en/join.html']]
  },
  {
    track:'java', group:'数据库', id:'mysql-replica-lag',
    title:'从库读到的是已经追上的数据吗',
    prompt:'主库刚提交的订单，为什么立刻读从库会读不到？',
    core:'MySQL 异步复制时，主库提交并写入二进制日志之后，从库才去拉取并应用。应用完成前，从库上没有这笔提交。同一用户先写主库、再读从库，会看不到自己刚写的数据。Seconds_Behind_Source 是估计，日志还在中继、或从库时钟不同，它都可以是 0 而数据仍未应用完。要读到自己的写入，读主库，或等复制位置至少到达这次写入的位点。',
    why:'把从库当成立即一致的读扩展，会让用户看到“提交成功但列表里没有”。',
    example:'下单写入主库后，订单列表若查从库，复制延迟期间列表是旧的。这笔查询改读主库，列表才能包含刚提交的订单。',
    task:'在从库暂停 SQL 线程，向主库插入一行，再分别查主库、从库和 Seconds_Behind_Source。',
    answer:'异步从库默认落后于已提交的主库。读自己的写入要读主库，或确认复制位点已经超过这次写入。',
    keywords:'MySQL replica lag Seconds_Behind_Source 读写分离 复制延迟',
    points:['异步复制在提交之后才把事件应用到从库','从库延迟期间读不到刚提交的行','延迟秒数是估计，不能代替复制位点'],
    refs:[['MySQL 8.4 手册镜像：复制实现','https://docs.oracle.com/cd/E17952_01/mysql-8.4-en/replication-implementation.html'],['MySQL 8.4 手册镜像：复制延迟排错','https://docs.oracle.com/cd/E17952_01/mysql-8.4-en/replication-problems.html']]
  },
  {
    track:'java', group:'框架', id:'spring-bean-lifecycle',
    title:'Bean 先造出来，再注入，然后才初始化',
    prompt:'构造器里调用另一个 Bean 的方法，为什么有时对象还没准备好？',
    core:'Spring 创建单例时，先调用构造器，再注入依赖，然后才执行初始化回调和 BeanPostProcessor 的后置处理。构造器里只能依赖已经作为构造参数传入的对象。用字段或 setter 注入时，构造器执行期间那些依赖还没有赋上。构造器循环依赖不能靠提前暴露半成品解决，容器会失败。初始化回调才适合在依赖齐全之后做检查或注册。',
    why:'在构造器里做依赖其他 Bean 的工作，会碰到空引用，或把循环依赖从可诊断的启动失败变成运行期空指针。',
    example:'支付客户端需要配置对象。配置通过构造参数传入，构造完成后配置已经可用。不要在构造器里再向容器要另一个尚未注入的字段。',
    task:'用构造器注入和字段注入各写一个 Bean，在构造器里打印依赖是否为 null，再把两个构造器互相依赖，看容器是否能启动。',
    answer:'构造器阶段只有构造参数。其余依赖在注入之后才存在。构造器循环依赖应改成明确的分层，而不是指望后初始化。',
    keywords:'Spring Bean 生命周期 构造器注入 循环依赖',
    points:['顺序是构造、注入、初始化','构造器里还没有字段注入的依赖','构造器循环依赖不能靠半成品提前暴露'],
    refs:[['Spring Framework：Bean 概述','https://docs.spring.io/spring-framework/reference/core/beans/definition.html'],['Spring Framework：循环依赖','https://docs.spring.io/spring-framework/reference/core/beans/dependencies/factory-collaborators.html']]
  },
  {
    track:'java', group:'框架', id:'spring-mvc-dispatch',
    title:'过滤器、拦截器和控制器不是同一层',
    prompt:'在 Filter 里抛出的异常，为什么 @ControllerAdvice 接不到？',
    core:'Servlet Filter 在进入 DispatcherServlet 之前或之后包住整个请求。DispatcherServlet 才查找 HandlerMapping、调用拦截器的 preHandle、用 HandlerAdapter 进入控制器，再走 postHandle。@ControllerAdvice 处理的是控制器及其返回值这一段抛出的异常。过滤器在更外面，它的异常不会自动变成控制器通知。拦截器可以拦下请求，让控制器不执行。三者的顺序决定了认证、日志和异常各自能看见什么。',
    why:'把所有横切都写成过滤器或都写成控制器通知，异常和登录态会在某一层悄悄丢失。',
    example:'编码和链路标识放在最外层过滤器。登录校验若依赖 Spring Security，走它的过滤器链。参数和业务异常放在控制器通知。',
    task:'在过滤器、拦截器和控制器里各打一条日志并各抛一次异常，记录哪些通知看得到、响应是谁写的。',
    answer:'过滤器包住 Servlet。拦截器包住控制器调用。控制器通知只覆盖控制器这一段。',
    keywords:'Spring MVC Filter Interceptor ControllerAdvice DispatcherServlet',
    points:['过滤器在 DispatcherServlet 之外','拦截器在控制器前后','控制器通知接不住过滤器里的异常'],
    refs:[['Spring Framework：MVC 处理顺序','https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-servlet/sequence.html'],['Spring Framework：过滤器','https://docs.spring.io/spring-framework/reference/web/webmvc/filters.html']]
  },
  {
    track:'java', group:'消息队列', id:'kafka-producer-acks',
    title:'生产者发出去，还不等于副本都记下了',
    prompt:'acks 设成 1，领导者返回成功后，消息就一定不会丢吗？',
    core:'acks=0 时生产者不等待确认。acks=1 时只要领导者把记录写入本地日志就返回。acks=all 时要等所有同步副本确认。领导者在确认后、跟随者复制前宕机，acks=1 的记录可能丢。当前 Kafka 生产者默认 acks=all，并可以开启幂等生产者，使同一生产者会话内的重试不重复写入。分区仍是顺序边界。确认级别不代替消费端的幂等。',
    why:'下游说没收到消息时，要先看生产者等到了哪一级确认，而不是只看 send 有没有抛错。',
    example:'订单事件用 acks=all 和幂等生产者。允许丢失的点击统计才考虑更低的确认级别。',
    task:'分别用 acks=1 和 acks=all 描述领导者在确认后立即失败时，跟随者可能有没有这条记录。',
    answer:'acks=1 只说明领导者自己写过。acks=all 才等到同步副本。消费重复仍要按业务键处理。',
    keywords:'Kafka acks producer idempotence ISR 副本',
    points:['acks=1 只等领导者本地日志','acks=all 等所有同步副本','生产者确认不等于消费端只处理一次'],
    refs:[['Kafka：acks','https://kafka.apache.org/documentation/#producerconfigs_acks'],['Kafka：幂等生产者','https://kafka.apache.org/documentation/#producerconfigs_enable.idempotence']]
  },
  {
    track:'java', group:'搜索', id:'es-refresh-visibility',
    title:'写入成功后，搜索仍可能看不到',
    prompt:'索引请求返回 201，下一次搜索为什么还查不到这篇文档？',
    core:'Elasticsearch 的索引成功表示文档已被接受。搜索看见它，要等 refresh 把新的段打开。默认大约每一秒刷新一次，所以搜索是近实时的。按 id 获取可以读到尚未刷新、但已经进 translog 的文档，这和搜索不是同一条路径。把 refresh 设成立即发生，写入会变慢。刷新也不是磁盘上的 fsync，进程崩溃时还要靠 translog 恢复。',
    why:'测试里“写入后马上搜索”会偶发失败。把刷新间隔当成强一致读，会误判丢数据。',
    example:'保存文章后立刻用搜索接口查标题，可能要到下一次刷新才出现。同一时刻用文档 id 获取，却已经能读到正文。',
    task:'关闭自动刷新，索引一篇文档，比较按 id 获取和按词搜索的结果，再手动 refresh 后重试搜索。',
    answer:'搜索等待 refresh。按 id 的实时获取可以读 translog。刷新间隔和落盘是两件事。',
    keywords:'Elasticsearch refresh translog near real-time 近实时',
    points:['索引成功不等于已经可被搜索','refresh 让新段对搜索可见','按 id 获取和搜索不是同一条可见性路径'],
    refs:[['Elasticsearch：近实时搜索','https://www.elastic.co/docs/manage-data/data-store/near-real-time-search'],['Elasticsearch：refresh','https://www.elastic.co/docs/api/doc/elasticsearch/operation/operation-indices-refresh']]
  },
  {
    track:'java', group:'工程实践', id:'hikari-pool-timeout',
    title:'池里借不到连接，和 SQL 跑得慢，不是同一个超时',
    prompt:'Hikari 的 connectionTimeout 设成 3 秒，慢查询就会在 3 秒失败吗？',
    core:'connectionTimeout 是从池里拿到一条连接的最长等待。池被占满时，超时抛出的是拿连接失败，查询还没开始。它不限制 SQL 执行多久。语句超时要设在 Statement.setQueryTimeout 或驱动的 socket 超时上。maxLifetime 让连接在被数据库或中间网络掐掉之前归还。把连接超时调大，只会让线程在池外排更久，不会让慢 SQL 更快结束。',
    why:'线上既有“池耗尽”，也有“查询拖住连接”。用一个数字会把两种故障调成同一种症状。',
    example:'20 条连接都卡在未提交的查询上。新请求在 connectionTimeout 内拿不到连接并失败。已经借出的那 20 条仍要靠语句超时或取消才能回来。',
    task:'占满池并不归还，观察新请求的失败时间。再单独把一条查询挂起，确认它不受 connectionTimeout 控制。',
    answer:'connectionTimeout 只限制借连接。SQL 执行用语句或网络超时。连接还要在生命周期结束前归还。',
    keywords:'HikariCP connectionTimeout query timeout maxLifetime 连接池',
    points:['connectionTimeout 是等待池中连接的时间','查询超时要另设在语句或套接字上','调大借连接等待不会取消已借出的慢查询'],
    refs:[['HikariCP：配置项','https://github.com/brettwooldridge/HikariCP/blob/dev/README.md']]
  },
  {
    track:'java', group:'工程实践', id:'spring-graceful-shutdown',
    title:'停机时先停新请求，再等手里的请求做完',
    prompt:'滚动发布时，旧进程一收到停止信号就退出，正在处理的请求会怎样？',
    core:'Spring Boot 打开优雅停机后，Web 服务器先停止接收新请求，再等待已经接受的请求结束，等待上限是停机阶段的超时。超时后仍可能中断剩余请求。这不包含已经在后台线程池里、却没有和这次请求绑定的任务。Kubernetes 要让停止宽限长于这个等待，并让就绪探针先把 Pod 移出服务，这样负载均衡才会停止送入新流量。',
    why:'直接杀进程会把支付、下单等写到一半的请求切掉，客户端只能看到连接断开。',
    example:'就绪探针失败后，Service 不再把新请求转到这个 Pod。进程再等待最多 30 秒让手头的请求写完响应，然后退出。',
    task:'停机期间同时发出一个已在处理的慢请求和一个新请求，记录哪个被拒绝、哪个能在超时前返回。',
    answer:'先从负载均衡摘掉，再拒绝新连接，并给已接受的请求一段有限的完成时间。后台任务要单独收尾。',
    keywords:'Spring Boot graceful shutdown readiness 优雅停机',
    points:['优雅停机先停止接受新请求','已接受的请求只等待有限时间','就绪探针要先于进程退出把流量摘掉'],
    refs:[['Spring Boot：优雅停机','https://docs.spring.io/spring-boot/reference/web/graceful-shutdown.html'],['Kubernetes：容器生命周期','https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/']]
  },
  {
    track:'java', group:'安全', id:'password-adaptive-hash',
    title:'口令只存慢哈希，不存原文，也不存快哈希',
    prompt:'把口令做一次 SHA-256 再入库，为什么仍然不够？',
    core:'口令不能可逆地存，也不能只做一次快速散列。应使用带唯一盐的自适应口令哈希，例如 Argon2id、bcrypt 或 scrypt。盐让相同口令的结果不同。工作因子把每次猜测变慢，数据库泄露后才买得到时间。SHA-256 这类快哈希适合校验文件，不适合单独保存口令。登录时用同样的参数重算并比较结果，不要在日志、异常或接口响应里输出口令或哈希。',
    why:'快哈希加上并行猜测，泄露后的口令库可以在短时间里被大量试验。',
    example:'注册时用 Argon2id 和随机盐保存结果。登录时取出盐和参数重算。调整工作因子时，在登录成功后升级旧哈希。',
    task:'说明盐、工作因子和比较方式各自防止什么，并指出为什么把 SHA-256 结果再加密存库仍然不该当口令方案。',
    answer:'每个口令使用唯一盐和自适应慢哈希。验证时重算。快哈希和可逆加密都不是口令存储。',
    keywords:'Argon2 bcrypt scrypt password hash salt 口令',
    points:['口令用带盐的自适应慢哈希保存','盐让相同口令不会得到相同结果','SHA-256 这类快哈希不能单独保存口令'],
    refs:[['OWASP：口令存储','https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html']]
  }
];

for (const {points, refs, ...lesson} of COVERAGE_PATH_02) {
  window.LESSONS.push(lesson);
  window.KNOWLEDGE_POINTS[lesson.id] = points;
  window.LESSON_REFERENCES[lesson.id] = refs;
}
