/* Original knowledge-point index for reviewed public lessons. No source excerpts. */
window.KNOWLEDGE_POINTS = {
  closure:['词法作用域与闭包','每次渲染的状态快照','函数式更新为何读取最新队列值'],
  eventloop:['任务与微任务检查点','浏览器获得绘制机会的时机','过量微任务为何延迟渲染'],
  'linked-list':['Hook 单向链表与调用顺序','Fiber 的 child/sibling/return/alternate','Lane 位掩码表达更新集合'],
  rendering:['JSX 编译为 JavaScript','React Element、Fiber 与 DOM 的关系','样式计算、布局、绘制与合成'],
  identity:['key 与组件身份','稳定 key 和下标 key 的差别','列表重排时状态如何复用'],
  effects:['Render 阶段记录 Effect','Layout Effect 与 Passive Effect 时序','依赖变化和卸载时的清理'],
  'event-system':['原生事件与 React 合成事件','根容器事件委派及特殊路径','停止传播与阻止默认行为'],
  performance:['React Profiler 定位组件耗时','memo 的适用条件','区分 JavaScript、DOM 与浏览器布局成本'],
  'java-memory':['GC Roots 与可达性','可回收不等于立即回收','静态引用导致对象长期存活'],
  'java-collections':['HashMap 定位桶与比较键','equals/hashCode 契约','可变键带来的查找问题'],
  'java-concurrency':['线程间可见性','复合操作的原子性','volatile 与原子类的边界'],
  'spring-transaction':['声明式事务代理边界','同类方法内部调用','事务调用路径的验证'],
  'mysql-index':['索引选择性与统计信息','组合索引和查询条件','EXPLAIN 与真实执行成本'],
  idempotency:['请求重试与重复提交','业务唯一键和幂等键','并发冲突后的结果复用'],
  cache:['缓存失效的并发窗口','数据陈旧的业务容忍度','库存与详情的不同一致性要求'],
  'design-review':['量化业务规模与约束','先设计正确的最小路径','根据瓶颈逐步演进'],
  'js-equality':['严格相等与对象引用身份','Object.is 的 NaN 和零值边界','React 依赖比较的影响'],
  'promise-chain':['then 返回新的 Promise','异常沿拒绝链传播','catch 后的完成态恢复'],
  esm:['ES Module 的导入绑定','模块依赖图与代码分块','循环依赖的执行顺序'],
  'http-cache':['no-cache 与 no-store','ETag 条件请求与 304','HTML 和哈希静态资源的缓存策略'],
  cors:['浏览器同源策略','CORS 响应头由服务端提供','OPTIONS 预检与凭据限制'],
  xss:['HTML 上下文的注入风险','textContent 与 innerHTML','输出编码、净化和 CSP 的职责'],
  layout:['读写交错触发强制布局','批量读取与批量写入','Performance 面板定位 Layout'],
  'state-queue':['渲染快照中的 state','替换更新与函数式更新','队列计算后的下一次渲染'],
  'controlled-input':['受控组件的数据来源','onChange 同步状态','受控与非受控输入的重置'],
  context:['最近 Provider 的值','Context 更新与消费者重渲染','按变化频率划分 Provider'],
  suspense:['支持 Suspense 的资源挂起','fallback 与重试','普通 Effect 请求不会自动挂起'],
  'frontend-testing':['用户可观察的行为契约','单元、组件和端到端层级','失败与恢复场景'],
  accessibility:['原生语义元素','键盘焦点与激活','读屏可理解的交互'],
  'java-generics':['编译期泛型检查','类型擦除的运行时边界','通配符与安全读取'],
  'java-exceptions':['异常传播与恢复边界','避免吞掉失败信号','try-with-resources 关闭资源'],
  'java-happens-before':['线程内顺序不等于跨线程可见性','锁建立的 happens-before 关系','volatile 和线程生命周期同步'],
  'java-executor':['线程数、队列与拒绝策略','无界排队的延迟与内存风险','背压、超时与下游容量'],
  'java-virtual-threads':['虚拟线程适合等待 I/O','CPU 密集任务的瓶颈','连接池和限流仍需独立设置'],
  'java-gc':['吞吐、停顿与内存权衡','分配速率和堆占用','关联 GC 暂停与请求延迟'],
  'spring-rollback':['运行时异常的默认回滚','受检异常与 rollbackFor','代理调用路径影响事务入口'],
  'spring-propagation':['外层事务与内层事务','REQUIRES_NEW 的独立提交','资源连接与回滚边界'],
  'mysql-mvcc':['一致性读与版本视图','锁定读 FOR UPDATE','库存扣减的原子条件更新'],
  'mysql-isolation':['隔离级别与可见性','业务不变量不能只靠隔离级别','唯一约束与冲突重试'],
  'redis-expire':['TTL 同时到期的回源峰值','热键失效与请求合并','空值缓存的误判与时效'],
  'message-delivery':['至少一次交付允许重复','消费幂等的业务键','去重记录与状态修改的事务边界'],
  'rate-limit':['到达速率与并发容量','队列边界与拒绝策略','超载时的反馈与退避'],
  complexity:['时间复杂度与输入规模','空间复杂度的额外成本','最坏情况与实际数据分布'],
  bfs:['队列按层遍历','访问标记防止重复','无权图的最短步数'],
  'distributed-cap':['先定义网络分区','分区期间的一致性与可用性取舍','CAP 不能代替正常运行时设计'],
  'distributed-kafka-order':['分区内顺序保证','同一业务键的分区策略','重试和多消费者影响处理顺序'],
  'distributed-bloom':['位数组与多次哈希','可能误判存在','不能单独保证数据库正确性'],
  'distributed-xa':['准备与提交两个阶段','协调者和参与者故障','阻塞成本与替代方案边界'],
  'distributed-cache':['雪崩：大量键集中失效','击穿：热点键回源','穿透：不存在数据的反复请求'],
  'distributed-token-bucket':['令牌补充速率','桶容量与短时突发','限速不等于限制并发'],
  'distributed-consistent-hash':['哈希环与顺时针映射','节点变化时的键迁移','虚拟节点不能消除单键热点'],
  'distributed-seckill':['库存不变量与原子扣减','限流、排队和资格校验','支付失败后的补偿与对账'],
  'distributed-outbox':['业务状态与事件同事务写入','异步发布与重试','消费者仍需幂等'],
  'distributed-lock':['租约过期与所有权','续租及故障时序','fencing token 保护共享资源']
};
