/* Original explanations. Source collection supplies topic coverage, not licensed text. */
window.LESSONS=[
{track:'frontend',group:'语言基础',id:'closure',title:'闭包、状态快照与函数组件',prompt:'为什么事件处理器可能读到旧 state？',core:'JavaScript 函数能访问创建它那一次调用中的变量。React 组件每次渲染都会再次执行函数，形成新的变量绑定；旧事件处理器仍可能引用旧渲染的值。',why:'理解闭包后，才容易区分「当前变量」和「队列中的下一次状态」。',example:'setCount(n => n + 1) 使用入队时的最新计算值；setCount(count + 1) 使用当前闭包看到的 count。',task:'从 count=0 开始，在一次点击中连续调用三次 setCount(count + 1)，再换成三次函数式更新。分别预测结果。',answer:'固定快照版本通常得到 1，函数式更新得到 3。',react:'hooks',keywords:'闭包 state react hooks setState'},
{track:'frontend',group:'语言基础',id:'eventloop',title:'事件循环与微任务',prompt:'Promise.then 和浏览器绘制的先后关系是什么？',core:'同步 JavaScript 先运行。当前任务结束后，事件循环处理微任务检查点；浏览器随后可能进行渲染。微任务过多也可能延迟绘制。',why:'React 的根调度会使用微任务整理待处理根，但真正执行同步工作还是安排任务取决于当前优先级与条件。',example:'console.log(1); queueMicrotask(() => console.log(3)); console.log(2); // 1,2,3',task:'画出一次点击处理器、同步日志、queueMicrotask 回调、浏览器获得绘制机会的顺序。',answer:'点击处理器中的同步代码完成 → 微任务检查点 → 浏览器可能绘制。',react:'scheduler',keywords:'事件循环 微任务 Promise Scheduler'},
{track:'frontend',group:'React',id:'linked-list',title:'链表、树与位运算',prompt:'为什么 Hook 顺序会影响 state 身份？',core:'Hook 节点通过 next 串联，Fiber.memoizedState 指向链表头。更新时 React 依次读取旧节点，调用顺序提供了位置身份。Lane 用不同二进制位表达更新集合。',why:'三个小数据结构就能解释 Hook 顺序、Fiber 树遍历和更新优先级。',example:'child → 第一个孩子；sibling → 下一个兄弟；return → 父节点；alternate → 同一身份的另一版本。',task:'画 App 的两个子节点 Header、Main 的 child/sibling/return 关系，并指出它们的 alternate。',answer:'App.child=Header，Header.sibling=Main，两者 return=App；alternate 分别指向另一树的对应节点。',react:'fiber',keywords:'链表 Fiber tree lane bitmask'},
{track:'frontend',group:'浏览器',id:'rendering',title:'JSX 到浏览器像素',prompt:'React Render 和浏览器 Paint 是一回事吗？',core:'JSX 先被工具转换成 JavaScript。执行时创建 React Element；React 协调 Fiber 并提交 DOM；浏览器再计算样式和布局、绘制并合成。',why:'性能问题发生在不同层：编译、JavaScript 计算、DOM 提交和浏览器渲染分别需要定位。',example:'root.render(<App />) 先安排 React 更新，不意味着该行返回时像素已绘制。',task:'指出 createElement、appendChild、Layout 和 Paint 分别属于哪一层。',answer:'DOM 创建与插入属于 React 宿主操作；Layout/Paint 属于浏览器渲染。',react:'pipeline',keywords:'JSX React DOM CSSOM Layout Paint'},
{track:'frontend',group:'React',id:'identity',title:'key、身份与列表状态',prompt:'为什么使用数组下标作为 key 可能让输入框内容错位？',core:'同一父节点下，React 用 key 和元素类型识别旧节点与新节点。用下标当 key 时，重排后相同位置可能代表不同业务项，旧组件状态却被复用。',why:'key 是身份约束，不只是消除警告。',example:'旧 A,B；新 B,A。稳定 key 让 B 与旧 B 对应；位置 key 会让新位置 0 继承旧 A 的状态。',task:'给 A、B 各一个输入状态，交换顺序后预测稳定 key 与 index key 的状态归属。',answer:'稳定 key 让状态跟随 A/B；index key 让状态留在原位置。',react:'diff',keywords:'React key reconciliation diff'},
{track:'frontend',group:'React',id:'effects',title:'Effect、清理与提交时序',prompt:'useEffect 一定在浏览器绘制后运行吗？',core:'React 在 Render 记录 Effect，在提交后刷新 Passive Effect。常见情况下它晚于绘制，但某些交互或布局阶段触发的更新可使其在绘制前刷新。Layout Effect 在 DOM 变更后、重绘前运行。',why:'Effect 用于已提交界面与外部系统同步，不能在可能被放弃的 Render 阶段执行。',example:'订阅逻辑返回 cleanup。依赖变更时，先清理旧订阅，再建立新订阅。',task:'解释依赖变化、卸载、StrictMode 开发检查时 cleanup 分别何时发生。',answer:'依赖变化与卸载会清理；开发 StrictMode 还可能额外执行 setup/cleanup 检查对称性。',react:'effects',keywords:'useEffect useLayoutEffect cleanup'},
{track:'frontend',group:'React',id:'event-system',title:'React 事件与原生事件',prompt:'React 19 仍把所有 click 处理器委派到 document 吗？',core:'现代 React DOM 为许多事件在根容器注册监听，也存在针对 document 或特定目标的特殊处理。合成事件包装了浏览器事件，stopPropagation 控制传播，preventDefault 控制默认行为。',why:'事件委派减少逐节点处理器成本，也让 React 在宿主层统一派发。旧资料中“一律 document”“stopPropagation 无效”已经不准确。',example:'e.stopPropagation() 阻止后续传播；e.preventDefault() 阻止默认浏览器动作，两者目的不同。',task:'用一个内外两层按钮容器，分别测试 stopPropagation 与 preventDefault 的效果。',answer:'前者控制冒泡，后者控制链接跳转或表单提交等默认动作。',react:'events',keywords:'SyntheticEvent React 事件 委派'},
{track:'frontend',group:'工程实践',id:'performance',title:'性能诊断：测量再优化',prompt:'memo 为什么不能解决所有慢渲染？',core:'memo 比较 props，并在合适条件下让组件跳过某些重算。组件自己的 state、context、外部 store 和昂贵浏览器布局仍可能造成工作。',why:'先用 Profiler 和浏览器 Performance 确定成本在哪层。',example:'稳定 props + memo 可能跳过子树；频繁改变对象字面量可能破坏浅比较收益。',task:'列出一次输入卡顿可能来自计算、DOM 提交和布局的三种证据。',answer:'看组件渲染耗时、DOM 变更耗时与浏览器 Layout/Paint 记录，再决定优化。',react:'architecture',keywords:'memo Profiler 性能'},
{track:'java',group:'Java 基础',id:'java-memory',title:'JVM 内存、对象与可达性',prompt:'对象没有变量引用就立刻被回收吗？',core:'垃圾回收判断对象是否从 GC Roots 可达。对象何时被收集由收集器和内存压力等因素决定，不保证“无人引用后立即回收”。',why:'区分可回收条件与实际回收时机，才能分析内存泄漏和延迟问题。',example:'长期存在的静态 Map 持有对象时，该对象仍可达。',task:'画出静态缓存 → 集合 → 用户对象的引用链，再说明删除缓存键的影响。',answer:'删除后若没有其他根引用，用户对象可变成不可达；实际回收仍取决于 GC。',keywords:'Java JVM GC roots 内存'},
{track:'java',group:'Java 基础',id:'java-collections',title:'HashMap 与集合选择',prompt:'HashMap 的键为什么要正确实现 equals 与 hashCode？',core:'哈希值决定桶的候选位置，equals 判定逻辑相等。相等对象必须有相同哈希值，否则查找会落入不同桶。',why:'集合行为依赖对象身份语义，错误实现会造成查找失败或重复元素。',example:'把可变字段用作键的 hashCode，放入后修改该字段，可能再也无法按新值找到它。',task:'设计一个 Person 键，说明哪些字段参与 equals/hashCode，以及何时应避免可变字段。',answer:'同一组稳定字段共同参与两者；键入集合后保持哈希相关字段不变。',keywords:'Java HashMap equals hashCode'},
{track:'java',group:'并发',id:'java-concurrency',title:'线程、可见性与原子性',prompt:'volatile 能让 count++ 线程安全吗？',core:'volatile 提供特定的可见性和有序性保证；count++ 包括读、加、写多个步骤，整体不因 volatile 变成原子操作。',why:'并发故障需要分清可见性、原子性和顺序性。',example:'多线程计数可选 AtomicInteger.incrementAndGet 或锁保护。',task:'模拟两个线程都读到 0、各自加 1 并写回，最终结果是多少？',answer:'结果可能是 1，而不是期望的 2。',keywords:'Java volatile CAS synchronized 线程'},
{track:'java',group:'框架',id:'spring-transaction',title:'Spring 事务边界',prompt:'同一个类里的方法直接调用另一个 @Transactional 方法一定生效吗？',core:'常见 Spring 声明式事务经由代理拦截方法调用。对象内部的 self-invocation 可能绕过代理，因此事务行为还取决于代理方式和调用路径。',why:'先画调用路径，再判断代理是否真正经过。',example:'Controller → Service 代理 → public 方法通常能进入拦截器；this.inner() 不一定。',task:'画出控制器经代理调用和 this 调用两条链。',answer:'前者经过事务拦截器；后者在常见代理模式下直接进入目标对象。',keywords:'Spring @Transactional proxy self invocation'},
{track:'java',group:'数据库',id:'mysql-index',title:'SQL 索引与执行计划',prompt:'建了索引就一定会走吗？',core:'优化器根据选择性、统计信息、谓词形态和成本选择访问路径。组合索引与查询条件的关系需要看具体计划，而非只背最左前缀。',why:'EXPLAIN 和真实数据分布比口头规则更可靠。',example:'低选择性条件或对列施加函数可能让优化器选择扫描。',task:'为用户表的 status、created_at 查询设计索引，并比较两个过滤条件的选择性。',answer:'先结合真实查询、排序与分布设计组合索引，再用 EXPLAIN 和耗时验证。',keywords:'MySQL index explain SQL'},
{track:'java',group:'系统设计',id:'idempotency',title:'接口幂等与重试',prompt:'为什么支付或创建订单接口不能只靠前端防重复点击？',core:'请求可能因网络超时被重试，后端必须让同一业务操作的重复提交得到一致结果。常用业务唯一键、幂等键和持久化状态机。',why:'分布式系统无法把“用户只点了一次”当作可靠假设。',example:'客户端带同一 idempotency key 重试；服务器原子地记录并返回先前结果。',task:'设计订单创建的幂等键、持久化位置和并发冲突处理。',answer:'用请求或业务唯一键，数据库唯一约束兜底；重复请求读取并返回原结果。',keywords:'分布式 幂等 重试 订单'},
{track:'java',group:'系统设计',id:'cache',title:'缓存一致性与失效',prompt:'更新数据库后立即删缓存，就绝对不会读到旧值吗？',core:'并发读写、传播延迟与故障会产生窗口。先定义允许的过期时间和一致性要求，再选择失效、版本号或读写协调策略。',why:'缓存优化必须以产品的一致性目标为边界。',example:'对商品描述可容忍短暂旧值；库存扣减需要更强约束。',task:'区分商品详情与库存余额的缓存策略。',answer:'详情可用 TTL 和失效；库存应由权威存储或原子扣减路径保证正确性。',keywords:'Redis 缓存 一致性 失效'},
{track:'java',group:'工程实践',id:'design-review',title:'系统设计题的回答框架',prompt:'如何避免一上来就说“上 Redis、MQ、分库分表”？',core:'先澄清规模、吞吐、延迟、一致性和故障目标；设计数据模型及最简单可行路径；再指出瓶颈、演进策略和验证方式。',why:'技术名词不能替代需求与权衡。',example:'每日 1000 请求与每秒 10000 请求需要不同架构。',task:'为秒杀服务列出 5 个必须先问的量化问题。',answer:'峰值 QPS、库存规模、超卖容忍度、延迟目标、故障恢复目标等。',keywords:'系统设计 QPS 需求 权衡'}
];
window.LESSON_REFERENCES={
closure:[['React：State as a Snapshot','https://react.dev/learn/state-as-a-snapshot'],['React：Queueing a Series of State Updates','https://react.dev/learn/queueing-a-series-of-state-updates']],
eventloop:[['MDN：JavaScript event loop','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Execution_model']],
'linked-list':[['React v19.3.0：ReactFiberHooks.js','https://github.com/facebook/react/blob/v19.3.0/packages/react-reconciler/src/ReactFiberHooks.js']],
rendering:[['React：createRoot','https://react.dev/reference/react-dom/client/createRoot'],['MDN：Critical rendering path','https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/Critical_rendering_path']],
identity:[['React：Preserving and Resetting State','https://react.dev/learn/preserving-and-resetting-state']],
effects:[['React：useEffect','https://react.dev/reference/react/useEffect'],['React：useLayoutEffect','https://react.dev/reference/react/useLayoutEffect']],
'event-system':[['React：Responding to Events','https://react.dev/learn/responding-to-events'],['React v19.3.0：DOMPluginEventSystem.js','https://github.com/facebook/react/blob/v19.3.0/packages/react-dom-bindings/src/events/DOMPluginEventSystem.js']],
performance:[['React：memo','https://react.dev/reference/react/memo'],['React：Profiler','https://react.dev/reference/react/Profiler']],
'java-memory':[['Oracle：GC Roots','https://docs.oracle.com/en/java/javase/21/gctuning/other-considerations.html']],
'java-collections':[['Oracle：Object equals/hashCode contract','https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html']],
'java-concurrency':[['Oracle：Atomic Access','https://docs.oracle.com/javase/tutorial/essential/concurrency/atomic.html']],
'spring-transaction':[['Spring：Using @Transactional','https://docs.spring.io/spring-framework/reference/data-access/transaction/declarative/annotations.html']],
'mysql-index':[['MySQL 8.4：EXPLAIN','https://dev.mysql.com/doc/refman/8.4/en/explain.html'],['MySQL 8.4：Optimizer-related issues','https://dev.mysql.com/doc/refman/8.4/en/optimizer-issues.html']],
idempotency:[],cache:[],'design-review':[]
};
