/* Batch 23: regex DOTALL, Redis 512MB, unchecked exceptions, Eureka lease, PC no OOM, Linux BKL, virtual memory series. */
const COVERAGE_JAVA_23 = [
  {
    track:'frontend', group:'语言基础', id:'js-regex-dot-not-newline',
    title:'. 默认不匹配换行，\\d 也不总等于 0-9 的全部数字',
    prompt:'为什么把正则背成“. 匹配任意单个字符、\\d 就是 [0-9]”会在开了 Unicode 或 DOTALL 时翻车？',
    promptAnswer:'默认点号不匹配换行。要跨行开 s/DOTALL；\\d 也不等于永远 [0-9]。',
    core:'多数引擎里 `.` 是元字符，默认不匹配换行；要匹配换行需 `(?s)`、`/s`、Pattern.DOTALL 或 `[^]` 这类写法。匹配字面点用 `\\.`。`\\d` 在 JavaScript 默认是 `[0-9]`；在 Java 开 UNICODE_CHARACTER_CLASS、或 Python 的 Unicode 模式下可以匹配其他数字字符。`[^0-9]` 是否等于“最后一个不是数字”还取决于锚点和量词，资料里的 `abc[^0-9]` 只会再吃一个非数字字符。正则嵌在宿主语言里，flag 决定语义。',
    why:'把 . 背成任意单个字符，多行日志会在第一处换行停住；把 \\d 背成永远等于 [0-9]，开了 Unicode 时全角数字会判断反。区分信号是点号要 DOTALL 或 s 标志才跨行，\\d 的宽度看 flag。',
    example:'JS 默认 `/a.b/` 匹配 `a\\nb` 失败，加上 `s` 才成功。Java `Pattern.compile("\\\\d", UNICODE_CHARACTER_CLASS)` 可能吃到非 ASCII 数字。',
    task:'对照所在语言的 flag 列表，写出让 `.` 匹配换行的开关；试一个 `\\d` 与 `[0-9]` 不一致的输入。',
    answer:'对照所在语言的 flag 列表，让 . 匹配换行的开关是 JavaScript 的 s、Java 的 Pattern.DOTALL，或内联 (?s)。默认点号不跨行。一个 \\d 与 [0-9] 不一致的输入是非 ASCII 数字：Java 开 UNICODE_CHARACTER_CLASS，或 Python 的 Unicode 模式下 \\d 能吃到，[0-9] 吃不到。字面点要转义。',
    keywords:'正则 DOTALL 换行 \\d Unicode',
    points:['默认点号不匹配换行，要开 DOTALL 或等价 flag','\\\\d 在 Unicode 模式下可能宽于 [0-9]','字面元字符必须转义'],
    deep:[
      {title:'旗标决定点号和数字',body:'默认的点号在换行处停下，所以多行日志用它会只吃到第一行。要跨行得打开 DOTALL、JavaScript 的 s，或写 (?s)。\\d 在 JavaScript 里默认就是 [0-9]；Java 开了 UNICODE_CHARACTER_CLASS、Python 走 Unicode 模式时，它可以吃到别的数字字符。字面量的点必须转义。'},
      {title:'怎样自己验证',body:'在所用语言里找出让点号匹配换行的那个 flag，用含换行的 a 换行 b 试一次，默认应失败，打开 flag 后应成功。再拿一个非 ASCII 数字分别交给 \\d 和 [0-9]，只有开了 Unicode 相关开关时两者才分开。'},
    ],
    refs:[['MDN：Regular expressions','https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions'],['Pattern.DOTALL','https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/regex/Pattern.html#DOTALL']]
  },
  {
    track:'java', group:'缓存', id:'redis-string-max-512mb',
    title:'Redis 字符串上限是 512MB，淘汰策略也不止那六项',
    prompt:'为什么同一份资料先写 value 最大 1GB，后面又写字符串 512MB，并把集群方案写成 Codis 最多？',
    promptAnswer:'除 noeviction、lru、random、ttl 外还有 LFU。',
    core:'协议里 STRING 的上限是 512MB，不是 1GB。工作集放内存，持久化是快照或 AOF，不是“整个库定期 flush 一次就完”。淘汰除 noeviction/lru/random/ttl 外还有 LFU 等，见 `redis-eviction-policy-menu`。官方提供 Windows 构建说明，只是不以 Windows 为第一平台。Cluster 用 16384 槽，不是一致性哈希；Codis 已不再是“用得最多”的默认答案。List 是双向链表结构，不等于开箱即用的消息队列。Lua 能把多条命令放进一次脚本做到原子，见 `redis-lua-atomic`。',
    why:'按 value 最大 1GB 去估容量，STRING 写到超过 512MB 会失败；把集群默认写成 Codis，会选到已经不再是现行答案的方案。区分信号是协议上限 512MB，官方分片是 16384 个槽。',
    example:'把一张图或一段 JSON 放进 STRING 之前，先确认远小于 512MB，而不是按 1GB 预留。分片用 Redis Cluster 的哈希槽；淘汰名单里要有 LFU，不能只背旧的六项。上限以 SET 为准。',
    task:'对照 SET 文档写出 STRING 上限；从淘汰名单里划掉“只有六项、没有 LFU”。',
    answer:'对照 SET 文档，STRING 上限是 512MB，不是资料前半段写的 1GB。从淘汰名单里划掉“只有六项、没有 LFU”：除 noeviction、lru、random、ttl 外还有 LFU。集群优先官方 Cluster 的 16384 槽，Codis 不是现行默认。',
    keywords:'Redis 512MB eviction LFU Cluster Codis',
    origin:'本地库《图解 redis 数据结构》SDS 结构设计页（协议上限以 SET 文档为准）',
    diagram:'library-assets/illustrated-basics/redis-ds-p0010.png',
    points:['STRING 上限 512MB 不是 1GB','淘汰策略包含 LFU 等，不是旧六项','官方集群是 hash slot，Codis 不是现行默认'],
    deep:[
      {title:'上限和淘汰不是旧清单',body:'协议里一条 STRING 到 512MB 为止，按 1GB 预留会在写入时失败。淘汰除了 noeviction、lru、random 和 ttl，还有 LFU。官方集群按 16384 个槽划分，不是再把 Codis 当成默认，也不是一致性哈希。'},
      {title:'怎样自己验证',body:'打开 SET 的命令文档，确认 STRING 上限写的是 512MB，并把 1GB 划掉。再打开淘汰策略列表，确认里面有 LFU，不是只有旧的六项。集群说明里应能看到 16384 个槽。'},
    ],
    refs:[['Redis：SET','https://redis.io/docs/latest/commands/set/'],['Redis Cluster spec','https://redis.io/docs/latest/operate/oss_and_stack/reference/cluster-spec/']]
  },
  {
    track:'java', group:'Java 基础', id:'java-unchecked-not-must-catch',
    title:'RuntimeException 不必写进 catch，Error 更不是业务必捕',
    prompt:'笔试题常写：RuntimeException 必须 try/catch，非 RuntimeException 都是外部错误。为什么这不能当标准答案？',
    promptAnswer:'RuntimeException 是未检查异常，编译器不强制 catch。必须处理的是检查异常；Error 不该当业务分支。',
    core:'异常的种类（Kinds of Exceptions）从 Throwable 分成 Error 和 Exception。RuntimeException 及其子类是未检查异常，编译器不要求 catch 或声明 throws。IOException 这类检查异常才必须处理。Error 表示虚拟机内部错误和资源耗尽，应用代码通常不要接住后假装恢复。',
    example:'Integer.parseInt 抛出的 NumberFormatException 可以不写 catch。Files.readAllBytes 的 IOException 必须处理或在方法上声明。OutOfMemoryError 不要收进来当业务分支恢复。',
    task:'对照 JLS 异常分类，划掉“RuntimeException 必须 catch”；写出 Error 为什么不该当业务分支。',
    answer:'对照 JLS 的异常分类，划掉“RuntimeException 必须 catch”：它和子类是未检查异常，编译器不要求捕获或声明 throws。必须处理或声明的是 IOException 一类检查异常。Error 不该当业务分支，因为它表示 JVM 内部错误或资源耗尽，捕捉后假装恢复会掩盖进程已经不行。',
    keywords:'RuntimeException checked Error Throwable',
    points:['RuntimeException 是未检查异常，不必必须 catch','IOException 等检查异常必须处理或声明','Error 表示严重故障，不要当普通业务分支'],
    deep:[
      {title:'编译器只强迫检查异常',body:'RuntimeException 及其子类不用写 catch，也不用 throws，空指针包一层只会把故障藏起来。IOException 这类检查异常漏了处理，编译直接不过。Error 表示虚拟机或资源已经不行，收进业务分支再假装恢复，调用方会以为这次失败可以重试成功。'},
      {title:'怎样自己验证',body:'对照语言规范里的异常分类，把“RuntimeException 必须 catch”划掉。写一个 parseInt，确认不捕获也能编译；写一个读文件的方法，确认 IOException 不处理就编不过。Error 留在分类说明里，不要放进业务 catch 清单。'},
    ],
    refs:[['JLS：Kinds of Exceptions','https://docs.oracle.com/javase/specs/jls/se21/html/jls-11.html#jls-11.1.1'],['Throwable','https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Throwable.html']]
  },
  {
    track:'java', group:'Spring Cloud Alibaba', id:'eureka-lease-30-90',
    title:'Eureka 默认 30 秒心跳、90 秒摘除，但发现不只有这一家',
    prompt:'为什么把服务发现只背成 Eureka 心跳 30/90，还把 Zuul、Hystrix、Ribbon 当成永久内核？',
    promptAnswer:'30/90 是可改默认，不是定律。Spring Cloud 也不再把 Zuul/Hystrix/Ribbon 当永久内核。',
    core:'Eureka 客户端默认约 30 秒续约，服务端在约 90 秒没续约后摘除，客户端会缓存注册表，注册中心全挂时短时间还能用旧地址。这些数字是默认租约，可配，不是物理定律。现行 Spring Cloud 常用 Spring Cloud LoadBalancer、Gateway，断路器见 `sca-circuit-not-only-hystrix`。注册中心还可以是 Nacos、Consul、ZK。Dubbo 负载均衡在客户端，默认 random，见既有 Dubbo 课。',
    why:'把 30 秒心跳、90 秒摘除写成不能改的物理定律，租约调大之后仍按 90 秒等摘除，会把还活着的实例判成故障。区分信号是这两个数是默认可配的租约，发现组件也不只有 Eureka。',
    example:'本地 Eureka 用默认租约做演示。生产若改 leaseRenewalIntervalInSeconds，摘除时间要一起改。新项目优先 Nacos 或 Consul，而不是只装 Netflix 全家桶。',
    task:'写出 Eureka 默认续约和摘除秒数；列出两种非 Eureka 的发现组件。',
    answer:'Eureka 默认约 30 秒续约一次，约 90 秒没有续约就摘除，这两个秒数可以改，不是固定定律。客户端还会缓存注册表，注册中心短时全挂仍可能用旧地址。两种非 Eureka 的发现组件是 Nacos 和 Consul。网关也不只有 Zuul。',
    keywords:'Eureka lease 30 90 Nacos Gateway',
    points:['Eureka 默认约 30 秒续约、90 秒摘除','客户端会缓存实例列表','网关和发现都有非 Netflix 的现行选项'],
    deep:[
      {title:'30 和 90 是默认租约',body:'客户端大约每 30 秒续一次约，服务端大约 90 秒收不到续约才摘除。把秒数写进预案之后又调大续约间隔，摘除阈值不一起改，活着的实例会被提前拿走。客户端本地还有一份注册表，注册中心短时不可用时旧地址仍可能能用。'},
      {title:'怎样自己验证',body:'在 Eureka 的续约说明里确认默认大约 30 秒心跳、90 秒摘除，并标出这两项可以配置。再列出 Nacos 和 Consul 两种不是 Eureka 的发现组件，网关不要只剩下 Zuul。'},
    ],
    refs:[['Eureka：Understanding Eureka','https://github.com/Netflix/eureka/wiki/Understanding-Eureka-Client-server-communication'],['Spring Cloud Netflix','https://spring.io/projects/spring-cloud-netflix']]
  },
  {
    track:'java', group:'JVM', id:'jvm-pc-no-oom',
    title:'程序计数器不会 OOM，方法区也不再等于永久代',
    prompt:'为什么把“JVM 内存模型”五个区背完之后，还说程序计数器可能和栈一样撑爆？',
    promptAnswer:'程序计数器不抛 OOM。那五个区是运行时数据区，不要和 JMM 混成一张图。',
    core:'规范里每个线程有 pc：执行 Java 方法时指向字节码，native 时未定义。HotSpot 的 pc 不抛 StackOverflowError 也不抛 OutOfMemoryError。虚拟机栈和本地方法栈才可能 SOE，可扩展时还可能 OOM。堆用 -Xms/-Xmx。方法区在 8 之后由元空间实现，见 `jvm-no-permgen-hotspot`。运行时常量池和字符串池位置随版本变过，JDK 7 起字符串进堆。直接内存用 DirectByteBuffer，不受 -Xmx 管，见 `jvm-oom-signals`。资料把运行时数据区叫成内存模型，和 JMM 重名，见 `jvm-jmm-not-runtime-areas`。',
    why:'把程序计数器和栈当成都会撑爆，就会去给 pc 加 -Xss 或按 OOM 查它，栈溢出和元空间泄漏会查错地方。区分信号是 HotSpot 的 pc 不抛 StackOverflowError，也不抛 OutOfMemoryError。',
    example:'无限递归看到的是虚拟机栈的 StackOverflowError，不是程序计数器。类加载泄漏去看元空间，而不是去查 pc。堆外的 DirectByteBuffer 看直接内存，它不受 -Xmx 单独封顶。',
    task:'对照规范列出哪个区不抛 OOM；划掉“内存模型五个区=JMM”。',
    answer:'对照规范，不抛 OutOfMemoryError、也不抛 StackOverflowError 的是程序计数器：执行 Java 方法时它指向字节码，native 时未定义。划掉“内存模型五个区等于 JMM”，这五个是运行时数据区。栈帧过深才是栈溢出。方法区在 8 之后由元空间实现。',
    keywords:'程序计数器 OOM 方法区 元空间 DirectByteBuffer',
    diagram:'diagrams/jvm-pc-no-oom.svg',
    points:['程序计数器不抛 OOM 或栈溢出','栈帧过深才是 SOE','方法区现行实现是元空间，字符串池在堆'],
    deep:[
      {title:'计数器没有容量可爆',body:'每个线程有自己的程序计数器，执行 Java 方法时指向当前字节码，执行 native 时规范里是未定义。它不占用你会用 -Xss 或 -Xmx 去调的那块空间，所以既不是栈溢出也不是堆溢出的来源。真正会栈溢出的是虚拟机栈；方法区在 8 之后看元空间。'},
      {title:'怎样自己验证',body:'对照虚拟机规范的运行时数据区，标出程序计数器不抛 OutOfMemoryError。用一段无限递归，确认抛的是栈溢出而不是 pc。再把“五个区等于 JMM”划掉，JMM 是另一套内存模型。'},
    ],
    refs:[['JVM Spec：pc Register','https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-2.html#jvms-2.5.1'],['JVM Spec：Run-Time Data Areas','https://docs.oracle.com/javase/specs/jvms/se21/html/jvms-2.html#jvms-2.5']]
  },
  {
    track:'java', group:'工程实践', id:'linux-bkl-gone',
    title:'Linux 已经没有大内核锁，内核也不再“绝对不能抢占”',
    prompt:'为什么还按 2.4/2.6 入门文把内核锁背成自旋锁加信号量加大内核锁，并说内核代码不能缺页、不能被抢占？',
    promptAnswer:'大内核锁已从主线移除。中断上下文不能睡；短临界区用自旋锁，能睡用 mutex。',
    core:'早期有过 BKL（大内核锁），主线早已去掉。现行内核同步是自旋锁、mutex、rwsem、RCU、seqlock、原子操作等，按能否睡眠、是否在中断上下文选用。2.6 引入内核抢占，后面还有实时补丁；不是 2.4 那种内核态一直占着 CPU。内核某些路径仍不能阻塞或不能缺页，但不是“内核模式一律不许缺页”。用户态与内核态、系统调用进内核，这些边界还在。申请大块连续物理内存仍然难，那是 CMA/启动预留的问题，不是再去搬 BKL 例程。',
    why:'按大内核锁去读现行 kernel/locking，lock_kernel 已经不在；再按内核绝对不能抢占去解释延迟，会对不上 2.6 起的抢占。区分信号是按能否睡眠选自旋锁或 mutex，中断上下文不能睡。',
    example:'驱动里很短、不能睡眠的临界区用 spinlock_irqsave。可能睡眠的路径用 mutex。读多写少用 RCU。中断里不要用会睡眠的信号量。不要再把 lock_kernel() 写进现行内核代码。',
    task:'对照现行内核锁定文档，划掉 BKL 作为必考现状；写出中断上下文为什么不能用会睡眠的信号量。',
    answer:'对照现行内核锁定文档，划掉 BKL 作为必考现状：大内核锁已从主线移除。中断上下文不能用会睡眠的信号量，因为睡眠会把这段中断处理停住，还可能在不可调度的路径上阻塞。短临界区用自旋锁，能睡眠的路径用 mutex。内核抢占从 2.6 起就有，不是 2.4 一直占着 CPU。',
    keywords:'BKL spinlock mutex RCU 内核抢占',
    origin:'本地库《图解系统》内核能力与调度页',
    diagram:'library-assets/illustrated-basics/os-p0111.png',
    points:['大内核锁已经从主线移除','中断上下文不能用会睡眠的锁','2.6 起内核可抢占，不是绝对占着 CPU'],
    deep:[
      {title:'按能不能睡来选锁',body:'自旋锁占着 CPU 等，适合很短、不能睡眠的临界区，中断上下文里也只能用这种。mutex 允许睡眠，用在可能阻塞的路径。读多写少可以用 RCU。大内核锁和 lock_kernel 已经不在主线里，不能再当成必考的第三把锁。'},
      {title:'怎样自己验证',body:'打开现行内核的锁定文档，确认没有大内核锁这一项，并把 BKL 从现状清单划掉。再写下一句：中断上下文不能调用会睡眠的信号量，因为睡眠会停住这段处理。2.6 起的抢占说明用来对照“内核绝对不能抢占”。'},
    ],
    refs:[['kernel：locking','https://docs.kernel.org/locking/index.html'],['kernel：preempt','https://docs.kernel.org/scheduler/preempt.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-user-kernel-syscall',
    title:'用户态只能访问局部地址空间，进内核靠系统调用陷入',
    prompt:'为什么普通业务代码不能直接改页表，却又能通过 open、read、mmap 碰到内核能力？',
    promptAnswer:'用户态只能碰自己的用户空间。要特权操作时发系统调用，CPU 陷入内核态执行后再返回。',
    core:'用户态代码只能访问本进程的用户空间；内核态代码可以访问内核空间与完整特权。需要建文件、映射内存、发网络包时，用户程序发起系统调用：CPU 产生陷入/中断，切到内核执行对应服务，完成后返回用户态。这不是“业务代码自己跑进内核”，而是经过固定入口把特权工作交给内核。用户态与内核态、系统调用边界仍在；BKL 等历史锁见 `linux-bkl-gone`。',
    why:'把用户程序当成随时能改任意物理内存，会对不上权限与隔离；把系统调用当成普通函数调用，又解释不了为何会陷入内核。区分信号是：有没有经过系统调用入口切换特权级。',
    example:'`read` 从用户缓冲读数据时，内核在内核态完成设备或页缓存访问，再把结果拷回用户缓冲并返回。业务线程自己写页表项会失败或被保护。',
    task:'写出用户态与内核态在可访问范围上的差别；用三步描述一次系统调用（发请求 → CPU 做什么 → 返回哪里）。',
    answer:'用户态只能访问本进程用户空间；内核态可访问内核空间并做特权操作。系统调用：用户程序发起调用；CPU 陷入内核执行；完成后返回用户态。',
    keywords:'用户态 内核态 系统调用 陷入',
    origin:'本地库《图解系统》用户态与内核态、系统调用页',
    diagram:'library-assets/illustrated-basics/os-p0112.png',
    points:['用户态只能访问本进程用户空间','系统调用经陷入进入内核再返回','特权操作走固定入口，不是业务代码直改内核结构'],
    deep:[
      {title:'和虚拟内存隔离的关系',body:'`linux-virtual-memory-isolation` 讲进程地址空间分开。本课钉特权级：即使有虚拟地址，改映射仍要进内核。'},
      {title:'怎样自己验证',body:'对照「用户程序 → 系统调用 → 中断/陷入 → 内核执行 → 返回」图，标出哪一段在用户态、哪一段在内核态。'},
    ],
    refs:[['man：syscalls','https://man7.org/linux/man-pages/man2/syscalls.2.html'],['kernel：User-space API','https://docs.kernel.org/userspace-api/index.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-process-states',
    title:'教材进程五态是调度模型，不是 Java Thread.State',
    prompt:'为什么把“创建、就绪、运行、阻塞、结束”背成 Java 线程只有这五种，读 jstack 会对不上？',
    promptAnswer:'那是操作系统教材里的进程调度模型。Java 用 Thread.State 六个值；两者名字相近但不是同一套枚举。',
    core:'操作系统教材常用进程五态：创建、就绪、运行、阻塞、结束。就绪被调度才进入运行；时间片用完回到就绪；等事件进入阻塞，事件完成回到就绪。这是理解调度与阻塞的模型。Java 的 `Thread.State`（JDK 5 起）是 `NEW`、`RUNNABLE`、`BLOCKED`、`WAITING`、`TIMED_WAITING`、`TERMINATED`，见 `java-thread-six-states`。不要把教材五态直接当成 JVM 线程枚举，也不要在五态里找“挂起”当现行 API。',
    why:'两套状态机混背，会把 TIMED_WAITING 说成阻塞、把 BLOCKED 说成挂起，排障时读错 jstack。区分信号是：在讲内核调度还是在讲 `Thread.getState()`。',
    example:'进程等磁盘完成：教材里是阻塞；事件完成后回就绪再被调度。Java 里 `Thread.sleep` 是 TIMED_WAITING，抢不到监视器是 BLOCKED，都不是教材里的“挂起”。',
    task:'列出教材五态各在什么事件下迁移；写一句它和 Thread.State 的关系；划掉“Java 线程就是这五种”。',
    answer:'五态：创建→就绪→运行，运行可因时间片回就绪、因等待进阻塞、因结束进结束；阻塞事件完成回就绪。它是 OS 调度模型，不是 Thread.State。Java 线程状态看六个枚举值。',
    keywords:'进程五态 就绪 运行 阻塞 Thread.State',
    origin:'本地库《图解系统》进程状态变迁页（Java 状态以 Thread.State 为准）',
    diagram:'library-assets/illustrated-basics/os-p0148.png',
    points:['教材五态描述调度与阻塞，不是 JVM 枚举','就绪经调度才运行；等事件走阻塞','Java 线程状态见 Thread.State 六个值'],
    deep:[
      {title:'和 java-thread-six-states',body:'那一课钉 JDK 枚举。本课钉 OS 教材模型，并写明不要混背。'},
      {title:'怎样自己验证',body:'对照五态图说出时间片用完、等待事件、事件完成三条边。再打开 Thread.State，确认没有“挂起”。'},
    ],
    refs:[['kernel：scheduler','https://docs.kernel.org/scheduler/index.html'],['Thread.State','https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Thread.State.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-process-context-switch',
    title:'进程上下文切换要保存 CPU 上下文，并换上另一进程的地址空间等资源',
    prompt:'为什么把“换一个线程跑一下”想成只改程序计数器，会低估进程切换成本？',
    promptAnswer:'CPU 上下文包括寄存器与 PC。进程切换还要换虚拟内存等用户态资源，以及内核栈等内核态资源，且在内核态完成。',
    core:'多任务靠快速切换制造“同时在跑”的效果。CPU 上下文至少包括寄存器与程序计数器（PC）：切走前要保存，切来时再装入并跳到新的 PC。进程上下文切换在内核态进行，除 CPU 上下文外，还涉及用户态资源（如虚拟地址空间、用户栈）与内核态资源（如内核栈）。同进程内的线程切换通常不必换整个地址空间，成本往往更低，见线程与虚拟线程相关课。切换太频繁会吃掉有效工作时间。',
    why:'只背“改一下 PC”，解释不了为何进程切换比同进程线程切换更贵，也解释不了页表/地址空间与切换的关系。区分信号是：有没有换地址空间等进程级资源。',
    example:'从进程 A 切到进程 B：内核保存 A 的寄存器与 PC，装入 B 的，并让 MMU 使用 B 的地址空间映射。同进程两个线程切换时，虚拟地址空间通常仍是这份。',
    task:'写出 CPU 上下文至少包含什么；说明进程切换为何在内核态；用一句话对比进程切换与同进程线程切换。',
    answer:'CPU 上下文至少含寄存器与 PC。进程由内核调度，切换在内核态完成。进程切换还要换地址空间等进程级资源；同进程线程切换通常不必换整份地址空间。',
    keywords:'上下文切换 寄存器 PC 虚拟内存 内核态',
    origin:'本地库《图解系统》进程上下文切换页',
    diagram:'library-assets/illustrated-basics/os-p0154.png',
    points:['切换前保存寄存器与 PC，再装入下一任务','进程切换在内核态，含用户态与内核态资源','同进程线程切换通常不必换整份地址空间'],
    deep:[
      {title:'和调度五态',body:'`linux-process-states` 讲何时从运行回到就绪。本课钉切换时内核实际保存与装入什么。'},
      {title:'怎样自己验证',body:'对照上下文切换页，列出要保存的 CPU 上下文，再标出进程切换多换了哪些资源。'},
    ],
    refs:[['kernel：Context switching','https://docs.kernel.org/scheduler/sched-design-CFS.html'],['Intel SDM：Context','https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-virtual-memory-isolation',
    title:'多进程不能共用绝对物理地址，要用虚拟地址做隔离',
    prompt:'为什么把单片机那种“CPU 直接按物理地址读写内存”套到多进程操作系统上，会在两个程序写同一地址时说不通？',
    promptAnswer:'没有操作系统的直访模型里地址就是物理位置。多进程要靠虚拟地址隔离，再由操作系统映射到不同物理页。',
    core:'单片机等场景常让 CPU 直接使用物理地址；两个程序若都写同一个绝对地址，会互相覆盖。操作系统为每个进程提供独立的虚拟地址空间：进程只在自己的虚拟地址里访问，相同的虚拟地址可以映射到不同的物理内存。映射由操作系统维护，访存时再经硬件翻译。这样进程不必协调彼此的物理布局，也能避免直接踩到对方的数据。',
    why:'把物理直访当成多进程现状，就解释不了进程隔离，也解释不了为何两个进程打印出相同指针值却互不影响。区分信号是：冲突来自共用绝对物理地址；虚拟地址把“程序看到的地址”和“内存条位置”分开。',
    example:'进程 A 与进程 B 都在虚拟地址 0x2000 写入，物理页可以完全不同，因此不会互相覆盖。若强制共用物理地址 0x2000，后写的会毁掉先写的内容。',
    task:'画出「进程 → 虚拟内存 → 物理内存」三层；用一句话说明为何两个进程可以用相同虚拟地址；写出物理直访模型在多进程下的主要风险。',
    answer:'三层是进程、虚拟内存、物理内存。两个进程可以用相同虚拟地址，因为各自映射到不同物理位置。物理直访的主要风险是互相覆盖、无法隔离。',
    keywords:'虚拟内存 进程隔离 物理地址 映射',
    origin:'本地库《图解系统》为何需要虚拟内存页',
    diagram:'library-assets/illustrated-basics/os-p0121.png',
    points:['多进程不能安全共用绝对物理地址','每个进程有独立虚拟地址空间','相同虚拟地址可映射到不同物理页'],
    deep:[
      {title:'虚拟内存在这里解决的问题',body:'先解决隔离与独立地址空间，再谈缺页、换页和文件映射。没有这层抽象，后面的页表机制没有落点。'},
      {title:'怎样自己验证',body:'对照「进程 / 虚拟内存 / 物理内存」三层图，指出程序写出的地址落在哪一层。再写一句：冲突来自绝对物理地址，不是来自“数字长得像”。'},
    ],
    refs:[['kernel：Memory Management','https://docs.kernel.org/admin-guide/mm/index.html'],['man：mmap','https://man7.org/linux/man-pages/man2/mmap.2.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-virtual-addr-mmu',
    title:'程序里的地址是虚拟地址，经 MMU 才落到物理内存',
    prompt:'为什么把程序打印出来的指针或数组下标当成内存条上的物理地址，会在多进程、缺页时说不通？',
    promptAnswer:'程序用的是虚拟地址。CPU 里的 MMU 把它翻译成物理地址后再访问物理内存。',
    core:'虚拟地址是程序看到的地址空间；物理地址才是硬件内存里真正的位置。操作系统给每个进程一套虚拟地址空间，访存时由芯片里的内存管理单元（MMU）做地址翻译。同一虚拟地址在不同进程可以对应不同物理页；未映射或被换出时会走缺页，不是“指针数字直接等于内存条偏移”。管理虚拟与物理对应关系的常见机制是分段与分页；现行通用操作系统以分页为主，分段多作历史与兼容背景。',
    why:'把虚拟地址当成物理地址，就解释不了进程隔离、同一指针值在两个进程里指向不同内容，也解释不了缺页与换页。区分信号是：CPU 发出的是虚拟地址，落到内存条之前一定经过 MMU。',
    example:'两个进程各自把一个 int 放在看起来相同的虚拟地址上，物理页可以完全不同。进程访问尚未映射的页会触发缺页异常，由内核补页或报错，而不是直接读到别的进程的物理内存。',
    task:'画出「CPU → MMU → 物理内存」三步；写出虚拟地址与物理地址各一句话定义；说明分段与分页分别按什么单位做映射。',
    answer:'CPU 发出虚拟地址，MMU 翻译成物理地址，再访问物理内存。虚拟地址是程序使用的地址；物理地址是硬件内存中的位置。分段按逻辑段（代码、数据、栈等）映射；分页按固定大小的页映射。现行通用系统以分页为主。',
    keywords:'虚拟地址 物理地址 MMU 分页 分段',
    origin:'本地库《图解系统》虚拟地址与物理地址页',
    diagram:'library-assets/illustrated-basics/os-p0122.png',
    points:['程序使用虚拟地址，不是内存条上的物理偏移','MMU 在 CPU 芯片内完成地址翻译','分段与分页是管理虚实映射的两种机制，现行系统以分页为主'],
    deep:[
      {title:'为什么要虚拟地址',body:'每个进程看到自己的地址空间，彼此隔离；物理页可以按需映射、共享只读页或换出到磁盘。没有这层翻译，多进程就不能安全共用同一块物理内存。'},
      {title:'怎样自己验证',body:'对照一张「CPU → MMU → 物理内存」图，指出程序打印的指针落在哪一侧。再写两句：虚拟地址是程序用的；物理地址是硬件位置。分段按逻辑段，分页按页，现行通用系统以分页为主。'},
    ],
    refs:[['kernel：Memory Management','https://docs.kernel.org/admin-guide/mm/index.html'],['Intel SDM：Memory Management','https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-memory-paging',
    title:'分页把地址空间切成固定大小的页，经页表翻译成物理地址',
    prompt:'为什么在讲完虚拟地址和 MMU 之后，还要把“分段整段换入换出”当成现行通用做法？',
    promptAnswer:'现行通用操作系统以分页为主。虚拟地址拆成页号与页内偏移，用页表查出物理页再拼偏移。',
    core:'分页把虚拟地址空间和物理内存都切成固定大小的页（Linux 常见默认 4KB）。虚拟地址分为页号与页内偏移：页号索引页表，得到物理页号（或页帧基址），再与页内偏移拼成物理地址；翻译由 MMU 完成。相对分段，页是固定粒度，换入换出可以按页进行，不必整段搬迁。页不在物理内存时会缺页，由内核补页或换入后再继续执行。',
    why:'把整段换入换出当成现状，会夸大碎片与交换成本，也对不上页表、缺页这些现行机制。区分信号是：地址先按页号查表，再拼偏移。',
    example:'访问某个虚拟地址时，先取出页号查页表得到物理页，再加上页内偏移才落到具体字节。进程不必一次性装入全部虚拟页；首次访问未映射页会触发缺页，内核分配物理页并更新页表。',
    task:'写出分页下虚拟地址的两部分名称；用三步写出「页号 → 页表 → 物理地址」；说明 Linux 常见默认页大小。',
    answer:'两部分是页号与页内偏移。三步：拆出页号和偏移；用页号查页表得到物理页；物理页与偏移拼成物理地址。Linux 常见默认页大小是 4KB。',
    keywords:'分页 页表 页号 页内偏移 MMU 缺页',
    origin:'本地库《图解系统》分页地址翻译页',
    diagram:'library-assets/illustrated-basics/os-p0128.png',
    points:['分页用固定大小的页映射虚拟与物理地址','页号查页表，再与页内偏移拼成物理地址','缺页时由内核补页或换入后再继续'],
    deep:[
      {title:'分页相对分段在交换上的差别',body:'分段时常要搬整段，碎片和交换成本都大。分页按页换入换出，未用到的虚拟页可以先不占物理内存，靠缺页再装入。'},
      {title:'怎样自己验证',body:'对照页号与页内偏移的拆分图，用手算一次：给定页号查表得到物理页，再加偏移。写出一句：翻译在 MMU，页表由操作系统维护。'},
    ],
    refs:[['kernel：Memory Management','https://docs.kernel.org/admin-guide/mm/index.html'],['kernel：Page Table Isolation','https://docs.kernel.org/x86/pti.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-multilevel-page-table',
    title:'单级页表按进程占满地址空间会太大，要用多级页表按需展开',
    prompt:'为什么把“每个进程一张覆盖全部虚拟空间的扁平页表”背成实现现状，会在算内存开销时对不上？',
    promptAnswer:'32 位、4KB 页时单级页表可到约 4MB/进程。多级页表只为用到的区间建下级表。',
    core:'简单单级页表要为整个虚拟地址空间准备页表项。以 32 位、4KB 页为例，约 2^20 个页表项，每项 4 字节则约 4MB，且每个进程一份，进程一多就很贵。多级页表把页号再拆成多级索引：先查一级表得到二级表基址，再查二级得到物理页号，最后拼页内偏移。未使用的虚拟区间可以不建下级页表，从而省空间。64 位还会用更多级或其它压缩结构，但“按需展开、不按满地址空间常驻一张扁平表”的道理相同。',
    why:'按每人一张满幅扁平页表去估内存，会高估页表占用，也解释不了为什么空地址区间不必占满物理页表页。区分信号是：多级索引 + 未用区间可不建下级表。',
    example:'32 位常见拆分是 10 位一级页号、10 位二级页号、12 位页内偏移（对应 4KB 页）。进程只用了少量虚拟页时，一级表里大量项为空，对应二级表根本不分配。',
    task:'算出 32 位、4KB 页、每项 4 字节时单级页表大约多大；写出多级页表省空间的关键一句；标出 10-10-12 拆分里哪一段是页内偏移。',
    answer:'单级页表大约 4MB（2^20 项 × 4 字节）。多级页表省空间的关键是：未使用的虚拟区间可以不建下级页表。10-10-12 里最后 12 位是页内偏移。',
    keywords:'多级页表 页表项 一级页表 二级页表',
    origin:'本地库《图解系统》多级页表页',
    diagram:'library-assets/illustrated-basics/os-p0130.png',
    points:['单级页表按满虚拟空间计会随进程数迅速变贵','多级页表按级索引，未用区间可不建下级表','页内偏移与页大小对应，常见 4KB 对应 12 位偏移'],
    deep:[
      {title:'多级并非永远更省',body:'若进程真的映射满整个地址空间，多级表项总数不会变少，还多了层级指针。省的是“大部分虚拟空间从未用到”这一常见情况。'},
      {title:'怎样自己验证',body:'用 2^32 / 4KB 算出页数，再乘每项 4 字节得到约 4MB。对照 10-10-12 图，指出一级索引、二级索引和页内偏移各多少位。'},
    ],
    refs:[['kernel：Memory Management','https://docs.kernel.org/admin-guide/mm/index.html'],['Intel SDM：Paging','https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-memory-segmentation',
    title:'分段用段号查段表再加偏移，现行通用系统不以它做主映射',
    prompt:'为什么还把“程序按代码/数据/堆/栈四大段直接映射到物理内存”背成今天的主机制？',
    promptAnswer:'分段是早期常用做法。现行通用操作系统以分页为主；分段多作历史与兼容背景。',
    core:'分段机制下，虚拟地址常拆成段选择子（含段号）与段内偏移：用段号索引段表，取出段基址、段界限等，再把偏移加到基址上得到物理地址；偏移不能越过段界限。程序常按代码、数据、堆、栈等逻辑段划分，段长短不一。段大小可变，容易产生外部碎片，整段换入换出成本也高，所以后来主流转向固定大小的分页。现行 x86 仍保留段相关结构，但通用操作系统的地址翻译主路径是分页。',
    why:'把四大段直映物理内存当成现状，会对不上页表、缺页和按页换入换出。区分信号是：段表按可变长段映射；页表按固定页映射。',
    example:'访问某段内偏移 500：先用段号查段表得到基址，再基址加 500。若偏移超过段界限则非法。四个段在物理内存上可以不相邻，中间留下难以利用的空洞，这就是外部碎片的来源之一。',
    task:'写出分段下虚拟地址的两部分；说明物理地址怎样由基址与偏移得到；写一句现行通用系统为何不以分段做主映射。',
    answer:'两部分是段选择子（段号）与段内偏移。物理地址由段基址加段内偏移得到，且偏移不能越界。现行通用系统不以分段做主映射，因为可变长段易碎片、整段交换成本高，主路径改为分页。',
    keywords:'分段 段表 段基址 段界限 外部碎片',
    origin:'本地库《图解系统》分段地址翻译页',
    diagram:'library-assets/illustrated-basics/os-p0123.png',
    points:['分段用段号查段表，基址加偏移得到物理地址','段长短可变，易产生外部碎片','现行通用操作系统地址翻译主路径是分页'],
    deep:[
      {title:'分段解决了什么，又留下什么',body:'分段让程序按逻辑段组织，不必直接写物理地址。留下的问题是可变长占用造成外部碎片，以及整段换入换出偏慢，这些推动了分页。'},
      {title:'怎样自己验证',body:'对照段选择子与段内偏移的图，用手算一次基址加偏移。再写一句：今天讲进程地址空间映射，主模型是页表而不是四大段直映。'},
    ],
    refs:[['Intel SDM：Segmentation','https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html'],['kernel：Memory Management','https://docs.kernel.org/admin-guide/mm/index.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-external-fragmentation',
    title:'外部碎片：空闲总量够，却放不下一个连续分配',
    prompt:'物理内存还空着 256MB，为什么一个只要 200MB 的新程序仍可能装不进去？',
    promptAnswer:'空闲块不连续时，每一块都小于 200MB，总和够也不等于能装下。这叫外部碎片。',
    core:'外部碎片指物理内存里空闲块总容量够，但被占用块隔成多段不连续空洞，放不下一个需要连续区间的新分配。分段下段长短不一，进程退出后更容易留下这种空洞。内部碎片则是已分配块内部用不满的浪费，和“洞在块与块之间”不是同一回事。缓解外部碎片可以靠把整段换出再换入以合并空闲区，但整段交换成本高；固定大小的分页让分配按页进行，不再依赖很大的连续物理空洞，这是后来主流转向分页的重要原因之一。',
    why:'只背“空闲字节数够就能装”，会对不上分段时代常见的装载失败，也解释不清为何分页减轻的是连续空洞问题。区分信号是：看空闲是否连成一块，还是只看总和。',
    example:'1GB 物理内存里先有游戏 512MB、浏览器 128MB、音乐 256MB。浏览器退出后空出中间 128MB，加上末尾 128MB，空闲合计 256MB，但新程序要连续 200MB 时两段都塞不进去——这就是外部碎片。',
    task:'用一句话区分外部碎片与内部碎片；写出“总和够仍装不下”的条件；说明分页如何减轻对大块连续空闲的依赖。',
    answer:'外部碎片是空闲块之间的不连续空洞；内部碎片是已分配块内部浪费。总和够仍装不下，是因为没有任何一块连续空闲满足所需长度。分页按固定页分配，不要求很大的连续物理空洞。',
    keywords:'外部碎片 内部碎片 分段 连续分配 分页',
    origin:'本地库《图解系统》外部碎片算例页',
    diagram:'library-assets/illustrated-basics/os-p0125.png',
    points:['外部碎片：空闲总够但块不连续，装不下新分配','内部碎片：已分配块内部用不满','分页按页分配，减轻对大块连续空闲的依赖'],
    deep:[
      {title:'和分段课怎么衔接',body:'`linux-memory-segmentation` 讲段表翻译。本课钉它留下的问题：可变长占用后的空洞。分页课再讲固定页如何改分配粒度。'},
      {title:'怎样自己验证',body:'对照「游戏/浏览器/音乐 → 浏览器退出 → 200MB 新程序两处都标 X」图，写出空闲总和与最大连续空闲各是多少。'},
    ],
    refs:[['kernel：Memory Management','https://docs.kernel.org/admin-guide/mm/index.html'],['Intel SDM：Memory Management','https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-page-fault-swap',
    title:'缺页时内核补页或换入，内存紧时可以把页换出到磁盘',
    prompt:'为什么把“进程一启动就把全部虚拟页装进物理内存”背成现状，会在解释懒加载和 swap 时说不通？',
    promptAnswer:'可以先建映射、访问时再缺页补页。内存紧时把近期不用的页换出到磁盘，需要时再换入。',
    core:'分页下不必一次装入进程的全部虚拟页。访问到页表中尚未对应物理页（或页在磁盘上）的地址时，硬件产生缺页异常，陷入内核：分配或换入物理页、更新页表，再回到用户态继续执行。内存紧张时，操作系统可以把近期较少使用的页换出到磁盘上的交换空间（如 Linux 的 swap），需要时再换入。按页换入换出比整段搬迁粒度更小，也支持按需装入。',
    why:'按“启动时装满物理内存”去想，解释不了为什么进程虚拟空间可以很大却只占部分 RSS，也解释不了 swap 命中后的停顿。区分信号是：缺页路径负责补页；换出换入按页与磁盘交互。',
    example:'首次读到尚未分配物理页的数据页会缺页，内核分配一页并填好页表项。物理内存不够时，可能把另一个进程很久未用的脏页写到 swap，腾出页帧给当前缺页。',
    task:'写出缺页发生后的三步（异常 → 内核做什么 → 回到哪里）；用一句话区分换出与换入；说明为何按页交换通常比整段交换更合适。',
    answer:'缺页后：硬件进缺页异常；内核分配或换入物理页并更新页表；再返回用户态继续执行。换出是把页写到磁盘腾出内存，换入是从磁盘读回。按页交换粒度小，不必整段搬迁。',
    keywords:'缺页 换入 换出 swap 按需装入',
    origin:'本地库《图解系统》缺页与换入换出页',
    diagram:'library-assets/illustrated-basics/os-p0127.png',
    points:['缺页异常后由内核补页或换入并更新页表','换出把页落到磁盘交换空间，换入再读回','分页支持按需装入，不必启动时装满物理内存'],
    deep:[
      {title:'和分段整段交换的差别',body:'分段时常要搬整段，成本高。分页只移动用到的页，未访问的虚拟页可以长期不占物理页帧。'},
      {title:'怎样自己验证',body:'对照「虚拟页 → 页表 → 物理页 / 硬盘」图，标出换出与换入两条箭头。写下一句：缺页是访问路径上的补页机会，不是程序写错才会发生的唯一情况。'},
    ],
    refs:[['kernel：Page Frame Reclamation','https://docs.kernel.org/mm/page_reclaim.html'],['man：mmap','https://man7.org/linux/man-pages/man2/mmap.2.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-tlb-cache',
    title:'TLB 缓存近期页表翻译，未命中才走完整页表查找',
    prompt:'为什么多级页表省了空间之后，还把“每次访存都完整走一遍多级页表”当成没有额外代价？',
    promptAnswer:'多级查找要多次访存。CPU 里用 TLB（快表）缓存近期翻译，命中则不必每次走完整页表。',
    core:'多级页表降低了页表占用，但一次地址翻译可能要读多级表项，延迟高。利用程序局部性，CPU 芯片内用 TLB（Translation Lookaside Buffer，也称快表、页表缓存）保存近期用过的页表翻译结果。MMU 先查 TLB：命中则直接得到物理页相关信息；未命中再查内存中的页表，并通常把结果填回 TLB。进程切换或页表更新时还要考虑 TLB 失效，否则会用到过期翻译。',
    why:'忽略 TLB，会低估多级页表的时间成本，也解释不了为何页表更改后要刷新快表。区分信号是：TLB 在 CPU 侧缓存翻译；页表在内存里是完整映射权威来源。',
    example:'循环访问同一小段代码页时，TLB 命中率通常很高，地址翻译几乎不再每次穿透多级页表。修改页表映射或切换到另一进程的地址空间后，需要让旧的 TLB 项失效，避免落到错误物理页。',
    task:'写出 TLB 命中与未命中时 MMU 各怎么做；用一句话说明局部性为何让 TLB 有效；指出 TLB 与页表谁是完整映射的权威来源。',
    answer:'命中：MMU 用 TLB 里的翻译继续访问。未命中：查内存中的页表，并通常把结果写入 TLB。局部性使短期访问集中在少数页，TLB 才有高命中率。完整映射的权威来源是内存中的页表，不是 TLB。',
    keywords:'TLB 快表 MMU 局部性 页表缓存',
    origin:'本地库《图解系统》TLB 与 MMU 页',
    diagram:'library-assets/illustrated-basics/os-p0133.png',
    points:['TLB 缓存在 CPU 侧的近期地址翻译','未命中才查内存页表，并常回填 TLB','页表是完整映射权威；TLB 失效后必须更新或丢弃旧项'],
    deep:[
      {title:'多级页表与 TLB 各管什么',body:'多级页表主要省空间；TLB 主要补时间。两者都依赖局部性：地址空间用不满，且短期访问集中。'},
      {title:'怎样自己验证',body:'对照 CPU 芯片内 MMU 与 TLB 的图，指出虚拟地址先到哪里。写两句：命中走快表；改页表或切进程要考虑 TLB 失效。'},
    ],
    refs:[['Intel SDM：Caching Translation Information','https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html'],['kernel：Memory Management','https://docs.kernel.org/admin-guide/mm/index.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-segmented-paging',
    title:'段页式先段后页：逻辑地址经线性地址再到物理地址',
    prompt:'为什么把“分段和分页只能二选一”背成定律，会在读 x86/Linux 地址翻译时对不上？',
    promptAnswer:'可以合用。段式单元先得到线性地址（虚拟地址），再由页式单元映射到物理地址。',
    core:'段页式把分段与分页接在一条链上：程序侧常是段号加偏移的逻辑地址；段式管理先映射出线性地址（也常称虚拟地址）；页式管理再经页表落到物理地址。地址里还可以进一步看成段号、段内页号、页内偏移。Intel 从 80386 起在分段之上叠加分页；Linux 在这种硬件模型上做内存管理，并不是“只有分页、芯片上从来没有段”。合用时一次翻译可能经过段表与页表等多级访存，开销更大，但可兼顾逻辑分段与按页分配。',
    why:'把二者对立成互斥选项，就读不懂逻辑地址、线性地址、物理地址三层，也解释不了为何教材仍提段寄存器。区分信号是：段的输出是线性/虚拟地址，页的输出才是物理地址。',
    example:'逻辑地址进入段式单元得到线性地址，再进入页式单元得到物理地址。段表项可以指向该段的页表，页表项再给出物理页号，最后拼页内偏移。',
    task:'按顺序列出逻辑地址、线性地址、物理地址；标明段式单元与页式单元各吃哪一种、产出哪一种；写一句 Linux 为何仍要理解这条链。',
    answer:'顺序是逻辑地址 → 线性地址（虚拟地址） → 物理地址。段式单元吃逻辑地址、产出线性地址；页式单元吃线性地址、产出物理地址。Linux 跑在先段后页的硬件模型上，公开课要把三层地址分清，不能背成互斥二选一。',
    keywords:'段页式 逻辑地址 线性地址 虚拟地址',
    origin:'本地库《图解系统》段页式与 Linux 内存管理页',
    diagram:'library-assets/illustrated-basics/os-p0135.png',
    points:['分段与分页可以合用，不是互斥二选一','逻辑地址经段式得到线性地址，再经页式得到物理地址','Linux 内存管理建立在这种先段后页的硬件链上'],
    deep:[
      {title:'和“现行以分页为主”怎么同时成立',body:'主路径的灵活映射、缺页、换页按页做；硬件上仍可能先经过段式再进入页式。教学上既要说清主模型是分页，也要分清三层地址名字。'},
      {title:'怎样自己验证',body:'对照「逻辑地址 → 段式 → 线性地址 → 页式 → 物理地址」图，给每一箭头写下输入输出。划掉“分段与分页只能挑一个”。'},
    ],
    refs:[['Intel SDM：Memory Management','https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html'],['kernel：Memory Management','https://docs.kernel.org/admin-guide/mm/index.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-shell-pipe-fds',
    title:'shell 管道是父进程建 pipe 再 fork，子进程各留一端',
    prompt:'为什么把 `A | B` 想成“两个无关进程凭空接到同一根管子”，会在解释匿名管道时说不通？',
    promptAnswer:'匿名管道靠继承文件描述符。shell 先 pipe，再 fork 出写端与读端子进程，并关掉不用的一端。',
    core:'shell 执行 `A | B` 时，父进程先调用 `pipe` 得到读端与写端文件描述符，再 `fork` 出两个子进程。写侧子进程保留写端、关闭读端；读侧子进程保留读端、关闭写端；父进程通常关掉两端，避免多余引用妨碍读端收到结束。匿名管道因此只适合有共同祖先、能继承描述符的进程；无亲缘关系要用命名管道等其它 IPC。双向通信通常需要两根管道。',
    why:'漏掉 fork 继承，就会以为任意两个进程都能接匿名管道，也对不上为何要关闭不用的一端。区分信号是：匿名管道靠描述符继承；命名管道以路径存在，可给无亲缘进程用。',
    example:'`ls | grep txt`：shell 建 pipe，一个子进程执行 ls 并把标准输出接到写端，另一个执行 grep 并从读端接到标准输入；各自关闭不用的那一端。',
    task:'按顺序列出 shell 建管道的三步；说明写端子进程与读端子进程各保留哪一端；写一句匿名管道与命名管道在亲缘关系上的差别。',
    answer:'三步：pipe 创建读写端；fork 出两个子进程；各进程关闭不用的一端（父进程常两端都关）。写侧保留写端，读侧保留读端。匿名管道依赖继承，适合有共同祖先的进程；命名管道以路径存在，可供无亲缘进程使用。',
    keywords:'pipe fork 匿名管道 文件描述符 shell',
    origin:'本地库《图解系统》shell 管道与匿名管道页',
    diagram:'library-assets/illustrated-basics/os-p0187.png',
    points:['shell 先 pipe 再 fork，用继承把管道交给子进程','写端与读端进程要关掉不用的那一端','匿名管道依赖亲缘继承；无亲缘用命名管道等'],
    deep:[
      {title:'和只讲 fork 复制的关系',body:'`linux-fork-copies-one-thread` 讲创建时拷什么。本课钉管道场景：描述符如何接到子进程，以及关闭策略如何影响读端结束。'},
      {title:'怎样自己验证',body:'对照 shell 父进程与两个子进程的描述符图，标出谁关读端、谁关写端。写一句：匿名管道不是凭空出现的全局管子。'},
    ],
    refs:[['man：pipe','https://man7.org/linux/man-pages/man2/pipe.2.html'],['man：pipe(7)','https://man7.org/linux/man-pages/man7/pipe.7.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-vfs-unified-api',
    title:'VFS 给多种文件系统一套统一的用户接口',
    prompt:'为什么用户能用同一套 open/read 打开 ext4、NFS 和 /proc 里的文件？',
    promptAnswer:'中间有虚拟文件系统（VFS）。它对用户提供统一接口，下面再接到具体文件系统。',
    core:'Linux 上文件系统种类很多。操作系统在用户与具体文件系统之间加一层虚拟文件系统（Virtual File System，VFS）：用户侧仍是 open、read、write、close 等统一接口；VFS 再把调用分派到具体文件系统的实现（如磁盘上的 ext4、网络上的 NFS、内存里的 proc）。“一切皆文件”描述的是这种统一视图，不是所有后端都用同一种磁盘布局。inode、目录项等是具体文件系统里的组织单位，经 VFS 暴露成统一对象模型。',
    why:'以为每一种文件系统各有一套互不兼容的系统调用，就解释不了为何同一段代码能打开不同后端。区分信号是：统一的是接口；不同的是下面的实现。',
    example:'`cat /etc/hosts` 与 `cat /proc/cpuinfo` 都走 read，但一个落到磁盘文件系统，一个落到内核导出的 proc 数据。',
    task:'用一句话说明 VFS 夹在哪两层之间；写出用户看到的统一接口举两例；说明“一切皆文件”指的是视图还是同一种存储格式。',
    answer:'VFS 在用户与具体文件系统之间。统一接口如 open、read。一切皆文件指统一视图，不是同一种磁盘布局。',
    keywords:'VFS 虚拟文件系统 inode open read',
    origin:'本地库《图解系统》虚拟文件系统 VFS 页',
    diagram:'library-assets/illustrated-basics/os-p0287.png',
    points:['VFS 向用户提供统一文件接口','下面再接到具体文件系统实现','一切皆文件是统一视图，不是单一存储格式'],
    deep:[
      {title:'和管道课的关系',body:'管道、套接字也常以文件描述符出现，仍经 VFS/描述符表管理。`linux-shell-pipe-fds` 讲管道两端如何接到子进程。'},
      {title:'和 inode 课的关系',body:'统一接口背后的名字与元数据分工见 `linux-inode-dentry`；数据块指针见 `linux-inode-block-pointers`。'},
      {title:'怎样自己验证',body:'对照 VFS 分层图，标出用户接口层与具体文件系统层。再各举一个磁盘文件与 /proc 文件的例子。'},
    ],
    refs:[['kernel：VFS','https://docs.kernel.org/filesystems/vfs.html'],['man：path_resolution','https://man7.org/linux/man-pages/man7/path_resolution.7.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-epoll-vs-select',
    title:'epoll 用就绪链表避免每次扫全部描述符',
    prompt:'为什么连接数上去以后，还把 select 当唯一多路复用答案，会在解释 epoll 时说不通？',
    promptAnswer:'select/poll 每次要带着整份集合进内核并线性扫。epoll 在内核里维护关注集合，只返回就绪的那些。',
    core:'I/O 多路复用让一条线程同时盯很多描述符。select/poll 常见成本是：每次调用把关注集合从用户态拷进内核，再线性检查；select 还有 FD_SETSIZE 一类上限。epoll 在内核用树形结构登记关注的描述符，事件就绪时挂到就绪链表；`epoll_wait` 主要取回已就绪的项，不必每次扫全部。水平触发与边缘触发见 `epoll-et-must-drain`；Java NIO Selector / Netty EventLoop 见 `nio-not-one-thread-per-request`。',
    why:'只背“都能同时等很多连接”，会漏掉拷贝与扫描成本，也解释不清为何高并发服务偏 epoll。区分信号是：每次是否搬运整份集合、返回时是否只含就绪项。',
    example:'一万个空闲连接注册在 epoll 上时，一次 `epoll_wait` 在没有事件时几乎不用遍历这一万个；select 则要带着更大的集合进内核检查。',
    task:'写出 select/poll 相对 epoll 的两个常见成本；说明 epoll_wait 返回的是什么；点名 ET/LT 细节去哪一课。',
    answer:'成本：整份集合拷贝进内核；对关注集合线性扫描。epoll_wait 返回已就绪的描述符（事件）。ET/LT 细节见 epoll-et-must-drain。',
    keywords:'epoll select poll 多路复用 就绪链表',
    origin:'本地库《图解系统》select/poll 与 epoll 对比页',
    diagram:'library-assets/illustrated-basics/os-p0358.png',
    points:['select/poll 常要拷贝并扫描整份关注集合','epoll 在内核登记关注，wait 取就绪项','ET/LT 行为见 epoll-et-must-drain'],
    deep:[
      {title:'和 NIO 课怎么分工',body:'`nio-not-one-thread-per-request` 讲一条线程盯多通道。本课钉 Linux 上 select 与 epoll 的成本差别。'},
      {title:'怎样自己验证',body:'对照对比页，列出 select 的两次遍历/拷贝与 epoll 的就绪链表。划掉“多路复用都一样贵”。'},
    ],
    refs:[['man：epoll','https://man7.org/linux/man-pages/man7/epoll.7.html'],['man：select','https://man7.org/linux/man-pages/man2/select.2.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-inode-dentry',
    title:'inode 记元数据与数据位置，dentry 记名字',
    prompt:'为什么同一个文件可以有多个名字，却仍是一份数据？',
    promptAnswer:'名字在目录项（dentry）里；元数据与数据块位置在 inode 里。多个 dentry 可以指向同一个 inode，这就是硬链接。',
    core:'Linux 上「一切皆文件」指统一用文件接口管理普通文件、目录、设备、管道和套接字等，不是说它们磁盘布局相同。每个文件对应一个 inode：存权限、大小、时间戳，以及数据在盘上的位置；inode 号是这份文件的身份。目录项（dentry）存文件名，并指向对应 inode；多个名字可以指向同一 inode，形成硬链接。目录本身也是一种文件，其数据是子项列表。dentry 常在内存里做路径查找缓存；持久落盘的是目录文件内容与 inode，二者不要混成「目录就是 dentry」。',
    why:'把「文件名」当成唯一身份，就解释不了硬链接，也会把内存里的 dentry 缓存当成盘上的目录文件。区分信号是：改名或加硬链接改的是名字到 inode 的映射，不是另起一份数据。',
    example:'对同一文件执行 `ln a.txt b.txt` 后，两个名字对应同一 inode 号；删掉其中一个名字，只要链接计数仍大于零，数据还在。',
    task:'分别写出 inode 与 dentry 各记什么；说明硬链接是几对几；用一句话区分「目录文件」与「dentry 缓存」。',
    answer:'inode 记元数据与数据位置；dentry 记名字并指向 inode。硬链接是多个 dentry 对一个 inode。目录是盘上的文件；dentry 是内核里加速查找的目录项缓存。',
    keywords:'inode dentry 硬链接 目录项 一切皆文件',
    origin:'本地库《图解系统》目录项与索引节点关系页',
    diagram:'library-assets/illustrated-basics/os-p0286.png',
    points:['inode 存元数据与数据块位置，是文件身份','dentry 存名字并指向 inode；多对一即硬链接','目录是文件；dentry 缓存不要当成盘上的目录本身'],
    deep:[
      {title:'和 VFS 课的关系',body:'`linux-vfs-unified-api` 讲统一接口。本课钉接口背后的 inode / 目录项模型。多级索引指针见 `linux-inode-block-pointers`；扇区与逻辑块见 `linux-fs-sector-block`。'},
      {title:'怎样自己验证',body:'`ls -i` 看两个硬链接是否同 inode；再对照图标出名字在哪一层、数据块指针在哪一层。'},
    ],
    refs:[['man：inode','https://man7.org/linux/man-pages/man7/inode.7.html'],['kernel：VFS','https://docs.kernel.org/filesystems/vfs.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-fs-sector-block',
    title:'文件系统按逻辑块读写，扇区是更小的物理单位',
    prompt:'为什么不能把“磁盘一次至少读 512 字节”理解成文件系统每次也只按 512 字节分配？',
    promptAnswer:'扇区是磁盘 I/O 的物理最小单位；文件系统通常把多个扇区合成逻辑块（常见 4KB）再分配与缓存。',
    core:'磁盘物理上常以扇区为最小读写单位（历史上多见 512 字节）。文件系统为减少次数、提高吞吐，常把若干扇区合成逻辑块（数据块），在 Linux 上常见 4KB，再以块为单位分配、读写与缓存。inode 里记的数据位置也按块寻址，见 `linux-inode-dentry`、`linux-inode-block-pointers`。格式化后的盘区通常还有超级块（文件系统全局信息）、inode 区与数据块区；超级块在挂载时进内存，具体 inode 多在访问对应文件时再装入。不要把扇区、逻辑块、页框三个“块”混成一个词。',
    why:'把扇区大小当成文件分配粒度，就对不上块设备和页缓存的常见路径，也解释不清为何小文件仍可能占满一个逻辑块。',
    example:'写一个远小于 4KB 的配置文件时，文件系统仍可能为它分配至少一个逻辑块；底层对磁盘的读写则按扇区对齐完成。',
    task:'分别写出扇区与逻辑块各回答什么问题；举一个常见逻辑块大小；点名 inode 寻址按哪一层。',
    answer:'扇区是磁盘物理 I/O 最小单位；逻辑块是文件系统分配与读写的单位。常见逻辑块 4KB。inode 按块（逻辑块）记数据位置。',
    keywords:'扇区 逻辑块 超级块 4KB inode',
    origin:'本地库《图解系统》扇区与逻辑块页',
    diagram:'library-assets/illustrated-basics/os-p0285.png',
    points:['扇区是物理 I/O 最小单位','文件系统常按更大的逻辑块分配与读写','超级块/inode 区/数据块区是盘上布局，勿与页框混称'],
    deep:[
      {title:'和 inode 课的关系',body:'`linux-inode-dentry` 讲名字与 inode。本课钉块设备上的扇区与文件系统逻辑块。'},
      {title:'怎样自己验证',body:'对照页里扇区与逻辑块的定义，写出 8 个 512 字节扇区如何合成一个 4KB 块。'},
    ],
    refs:[['man：stat','https://man7.org/linux/man-pages/man2/stat.2.html'],['kernel：VFS','https://docs.kernel.org/filesystems/vfs.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-inode-block-pointers',
    title:'inode 用直接与多级间接指针找数据块',
    prompt:'为什么小文件和大文件都能用同一套 inode 结构描述，却不能假设每次读都只跟一次指针？',
    promptAnswer:'inode 里既有直接指向数据块的指针，也有一到三级间接索引。小文件走直接指针；大文件要多查几级索引块。',
    core:'文件数据按逻辑块存放。经典 Ext2/3 风格的 inode 带一组块指针：多数是直接指向数据块；其余指向一级、二级乃至三级间接索引块。小文件常用直接指针，少一次跳转；大文件靠多级索引扩展可寻址范围，但读数据前可能要先读索引块。Ext4 等现代布局还会用更高效的映射（如 extent），细节随文件系统而变，不要把某一代指针个数当成所有 Linux 文件系统的固定常数。空闲块另有空闲表、空闲链表、位图等管理方式，与「文件内如何寻址」不是同一题。',
    why:'只背「inode 存位置」却不分直接/间接，就解释不清大文件为何多几次盘访问。区分信号是：这次读有没有先经过索引块。',
    example:'读一个只占几个直接指针就能覆盖的小文件时，inode 里就能拿到数据块号；读超大文件时，可能先读间接索引块，再拿到真正的数据块号。',
    task:'写出直接指针与间接索引各自解决什么问题；说明大文件路径上可能多一次什么访问；点名不要把某一代指针个数当成所有文件系统的常数。',
    answer:'直接指针让小文件少跳转；间接索引扩大可寻址范围。大文件可能先读索引块再读数据。指针个数与级数随文件系统演变，不能当全站常数。',
    keywords:'inode 间接索引 Ext 数据块 extent',
    origin:'本地库《图解系统》inode 多级索引与空闲空间页',
    diagram:'library-assets/illustrated-basics/os-p0299.png',
    points:['inode 可同时有直接指针与多级间接索引','小文件偏直接指针，大文件可能多读索引块','具体级数与 Ext4 extent 等随文件系统变化'],
    deep:[
      {title:'和 inode/dentry 课的关系',body:'`linux-inode-dentry` 讲名字与元数据分工。本课钉「数据块怎么从 inode 找到」。'},
      {title:'怎样自己验证',body:'对照多级索引图，从 inode 走到一个间接块再走到数据块，数清多了几次读。'},
    ],
    refs:[['kernel：ext4','https://docs.kernel.org/filesystems/ext4/index.html'],['man：inode','https://man7.org/linux/man-pages/man7/inode.7.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-network-stack-layers',
    title:'发包要经套接字进入内核协议栈逐层加头',
    prompt:'应用调用 send 之后，数据是直接交给网卡，还是先在内核里走完协议栈？',
    promptAnswer:'先经套接字进入内核协议栈，按传输层、网络层、网络接口层逐层加头（必要时加尾），再交给网卡发出。',
    core:'应用通常通过套接字接口发起系统调用，把数据从用户态拷到内核套接字侧，再进入网络协议栈。发送路径自上而下：传输层加 TCP/UDP 头，网络层加 IP 头，网络接口层加帧头/帧尾，最后由网卡送出。接收路径相反，自下而上剥头直到交给应用。这与「HTTP 是应用层协议、TCP 是传输层」的分层一致，见 `tcp-is-l4-not-http-handshake`；字节流上的应用消息边界仍要自己定，见 `tcp-stream-needs-framing`。',
    why:'以为 send 等于网卡立刻发出，就对不上内核缓冲、排队与分层封装，也解释不清抓包为何先看到以太网/IP/TCP 头。区分信号是：系统调用之后还有协议栈加工。',
    example:'浏览器发 HTTPS：应用写出的是 TLS 密文载荷；内核仍要加上 TCP、IP 与链路层头，才能在以太网上出现完整帧。',
    task:'按发送方向列出从应用到网卡经过的主要层次；说明接收方向如何；点名应用层消息边界去哪一课。',
    answer:'发送：套接字 → 传输层 → 网络层 → 网络接口层 → 网卡。接收自下而上。应用消息边界见 tcp-stream-needs-framing。',
    keywords:'协议栈 套接字 TCP IP 帧 系统调用',
    origin:'本地库《图解系统》Linux 网络协议栈封装页',
    diagram:'library-assets/illustrated-basics/os-p0378.png',
    points:['send 先进入内核套接字与协议栈','发送自上而下加头，接收自下而上剥头','分层与 HTTP/TCP 边界课一致，消息边界另见 framing'],
    deep:[
      {title:'和 TCP 传输层课的关系',body:'`tcp-is-l4-not-http-handshake` 钉 HTTP 不是传输层。本课钉数据在 Linux 内核里怎样逐层封装。'},
      {title:'怎样自己验证',body:'对照封装图，从应用数据向下标出 TCP 头、IP 头、帧头帧尾各加在哪一层。'},
    ],
    refs:[['man：socket','https://man7.org/linux/man-pages/man7/socket.7.html'],['man：ip','https://man7.org/linux/man-pages/man7/ip.7.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-tcp-listen-queues',
    title:'listen 后握手先入半连接队列，完成后再进全连接队列',
    prompt:'三次握手成功了，为什么应用还没 accept 时连接可能已经在内核里排队？',
    promptAnswer:'服务端 listen 之后，内核用半连接队列承接 SYN，握手完成的连接进入全连接（accept）队列，等应用 accept 取走。',
    core:'服务端 `bind`/`listen` 之后，客户端 `connect` 发来 SYN：连接先进入半连接队列（SYN 队列），服务端回 SYN+ACK；收到最终 ACK 后，连接进入全连接队列（accept 队列），状态为已建立但尚未交给应用。应用调用 `accept` 才从全连接队列取走一个连接。LISTEN 状态下用 `ss`/`netstat` 看时，Recv-Q/Send-Q 常表示全连接队列当前长度与上限，与 ESTABLISHED 下表示未读/未确认字节不是同一含义。队列满时，新握手可能失败或重试，表现为客户端超时或连接被拒，根因要分清是半连接还是 accept 队列。',
    why:'只背三次握手包序、不看两级队列，就会把「握手成功」等同于「应用已经拿到连接」，排障时对不上 Recv-Q 与 accept 堆积。',
    example:'服务端业务线程卡住不再 accept：客户端仍可能完成握手，但连接堆在全连接队列；`ss -ltn` 上 Recv-Q 接近 Send-Q 所示上限。',
    task:'按顺序列出 SYN 之后连接经过的两个队列；说明 accept 从哪一个取连接；写出 LISTEN 下 Recv-Q 与 ESTABLISHED 下 Recv-Q 的差别要点。',
    answer:'先半连接队列，握手完成进全连接队列。accept 取全连接队列。LISTEN 下 Recv-Q 多表示 accept 队列长度；ESTABLISHED 下表示应用尚未读走的字节。',
    keywords:'listen accept 半连接队列 全连接队列 SYN queue backlog ss',
    origin:'本地库《图解系统》TCP 半连接与全连接队列页',
    diagram:'library-assets/illustrated-basics/os-p0383.png',
    points:['SYN 先入半连接队列，完成握手后进全连接队列','accept 从全连接队列取连接','LISTEN 与 ESTABLISHED 下 Recv-Q 含义不同'],
    deep:[
      {title:'和协议栈封装课的关系',body:'`linux-network-stack-layers` 讲数据如何下栈。本课钉监听套接字上握手与 accept 的队列边界。'},
      {title:'和 ss 列含义课的关系',body:'`linux-ss-recvq-sendq` 专讲 LISTEN 与 ESTABLISHED 下 Recv-Q/Send-Q 各表示什么。'},
      {title:'怎样自己验证',body:'对照握手与双队列时序图，标出 SYN、SYN+ACK、ACK 以及 accept 各落在哪一段。再用 `ss -ltn` 看 LISTEN 行的 Recv-Q/Send-Q。'},
    ],
    refs:[['man：listen','https://man7.org/linux/man-pages/man2/listen.2.html'],['man：accept','https://man7.org/linux/man-pages/man2/accept.2.html'],['man：ss','https://man7.org/linux/man-pages/man8/ss.8.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-ss-recvq-sendq',
    title:'ss 的 Recv-Q/Send-Q 在 LISTEN 与已连接含义不同',
    prompt:'为什么在 LISTEN 行上看到 Recv-Q=10、Send-Q=128，不能理解成“还有 10 字节没读完”？',
    promptAnswer:'LISTEN 下这两列常表示全连接（accept）队列的当前长度与上限；已连接状态下才多表示未读字节与未确认发送字节。',
    core:'`ss`/`netstat` 都会列出 Recv-Q 与 Send-Q，但含义随套接字状态变化。ESTABLISHED：Recv-Q 多为应用尚未从套接字缓冲读走的字节数，Send-Q 多为已写出、对端尚未确认的字节数。LISTEN：Recv-Q 多为全连接队列当前长度，Send-Q 多为该队列允许的最大长度（与 listen backlog 相关）。生产排障优先 `ss`：同类信息下通常比 `netstat` 开销更小。半连接与全连接队列机制见 `linux-tcp-listen-queues`。',
    why:'不看状态就读 Recv-Q，会把 accept 堆积误判成应用读慢，或反过来。区分信号是：这一行的 State 是 LISTEN 还是 ESTABLISHED。',
    example:'`ss -ltnp` 显示某 HTTP 端口 `LISTEN 120 128`：更像 accept 队列已接近上限，应查应用是否还在 accept，而不是先查“谁没读 120 字节”。',
    task:'写出 ESTABLISHED 与 LISTEN 下 Recv-Q 各表示什么；说明 LISTEN 下 Send-Q 常见含义；点名队列机制去哪一课。',
    answer:'ESTABLISHED：Recv-Q 多为未读字节。LISTEN：Recv-Q 多为 accept 队列长度，Send-Q 多为队列上限。队列机制见 linux-tcp-listen-queues。',
    keywords:'ss netstat Recv-Q Send-Q LISTEN backlog accept',
    origin:'本地库《图解系统》ss/netstat 队列列含义页',
    diagram:'library-assets/illustrated-basics/os-p0382.png',
    points:['Recv-Q/Send-Q 含义随套接字状态变化','LISTEN 下常表示 accept 队列长度与上限','排障优先 ss，并先看 State 再读队列列'],
    deep:[
      {title:'和 listen 队列课的关系',body:'`linux-tcp-listen-queues` 讲半连接/全连接。本课钉工具列怎么读。'},
      {title:'怎样自己验证',body:'对同一服务分别跑 `ss -ltn` 与对已连接行看 `ss -tn`，对照两行 Recv-Q 的释义是否套用了正确状态。'},
    ],
    refs:[['man：ss','https://man7.org/linux/man-pages/man8/ss.8.html'],['man：netstat','https://man7.org/linux/man-pages/man8/netstat.8.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-net-four-metrics',
    title:'带宽、延时、吞吐与 PPS 不是同一个数',
    prompt:'为什么链路标称 1Gbps，却不能直接说应用一定有 1Gbps 吞吐？',
    promptAnswer:'带宽是链路能力上限；吞吐是单位时间实际传成功的数据量，还受延时、丢包、CPU 与应用限制；PPS 看的是包个数转发能力。',
    core:'看 Linux 网络表现时常分四类指标，不要并成一句。带宽是链路最大传输速率（常用 b/s）。延时是发出到收到响应的时间，可指建连耗时或 RTT。吞吐是单位时间实际传成功的数据量（b/s 或 B/s），上限受带宽约束，但常低于标称带宽。PPS（Packet Per Second）看每秒包数，小包场景下往往先撞上包处理能力而不是带宽字节数。另有可用性等指标。配置与接口计数见 `linux-nic-mtu-rx-errors`；套接字队列见 `linux-ss-recvq-sendq`。',
    why:'把带宽当吞吐，或把慢页面只怪“网速不够”，会对不上小包 PPS 打满、队列堆积或应用读慢等根因。',
    example:'千兆网卡上跑大量 64 字节小包时，PPS 先到上限，字节吞吐远低于 1Gbps；换大包后字节吞吐上升，PPS 压力下降。',
    task:'用一句话区分带宽与吞吐；说明 PPS 主要评估什么；举一个“带宽够但吞吐上不去”的原因方向。',
    answer:'带宽是上限能力，吞吐是实际成功传输量。PPS 评估包转发能力。原因方向如小包 PPS 打满、丢包重传、应用或 CPU 跟不上。',
    keywords:'带宽 延时 吞吐 PPS RTT',
    origin:'本地库《图解系统》网络性能指标页',
    diagram:'library-assets/illustrated-basics/os-p0379.png',
    points:['带宽是链路能力上限，吞吐是实际传输量','延时关注时间，PPS 关注包个数','四类指标不要合成一个“网速”'],
    deep:[
      {title:'和网卡计数课的关系',body:'接口 errors/dropped 等见 `linux-nic-mtu-rx-errors`。本课先分清要看哪一类指标。'},
      {title:'怎样自己验证',body:'列出带宽/延时/吞吐/PPS 各用什么单位；再举一个只改善其中一项仍不够的场景。'},
    ],
    refs:[['man：ip','https://man7.org/linux/man-pages/man8/ip.8.html'],['man：ping','https://man7.org/linux/man-pages/man8/ping.8.html']]
  },
  {
    track:'java', group:'工程实践', id:'linux-nic-mtu-rx-errors',
    title:'MTU 限制单帧载荷，接口计数区分丢包原因',
    prompt:'为什么 IP 包很大时要分片，而 ifconfig 里 dropped 又不能直接当成“网线坏了”？',
    promptAnswer:'链路有 MTU，超长 IP 包要在 IP 层分片。接口上的 errors/dropped/overruns 等计数指向不同故障面，要分开读。',
    core:'网卡与链路有最大传输单元（MTU）；以太网常见默认 1500 字节。IP 数据报超过链路 MTU 时，IP 层可能分片（路径上也可能禁止分片而返回错误）。接口还需正确配置地址、掩码、MAC、网关等才能通信。`ip`/`ifconfig` 上的 RX/TX 计数：errors 多与校验或帧同步等问题相关；dropped 常表示已进驱动环形缓冲后被丢（例如内存压力）；overruns 多表示处理跟不上导致环形缓冲溢出；carrier/collisions 更偏物理或双工等链路问题。这些只是接口与驱动侧统计，协议栈与套接字细节还要靠 `ss` 等，见 `linux-ss-recvq-sendq`。',
    why:'只看“有丢包”却不看是哪一列，会把驱动溢出、内存压力与网线故障混成一类。区分信号是：非零的是 errors、dropped 还是 overruns/carrier。',
    example:'压测小包时 RX overruns 上升，多像接收处理跟不上；若主要是 carrier 增加，应先查线缆或双工，而不是先调应用线程数。',
    task:'写出 MTU 的作用与常见默认值；列出至少三个接口计数并各用一句话说明偏向；点名套接字队列去哪一课。',
    answer:'MTU 限制单帧可承载大小，以太网常见 1500。errors/dropped/overruns（或 carrier）分别偏校验帧错误、缓冲后丢弃、处理跟不上溢出等。套接字队列见 linux-ss-recvq-sendq。',
    keywords:'MTU 分片 errors dropped overruns ss',
    origin:'本地库《图解系统》MTU 与接口计数页',
    diagram:'library-assets/illustrated-basics/os-p0381.png',
    points:['MTU 限制单帧载荷，超长可能分片','接口计数列含义不同，不能都叫网线坏','接口统计之外还要看 ss 等协议栈视图'],
    deep:[
      {title:'和四指标课的关系',body:'`linux-net-four-metrics` 分带宽/延时/吞吐/PPS。本课钉 MTU 与接口计数怎么读。'},
      {title:'怎样自己验证',body:'对一块网卡执行 `ip -s link`，标出 errors/dropped 等列；再对照是否超过该链路 MTU。'},
    ],
    refs:[['man：ip','https://man7.org/linux/man-pages/man8/ip.8.html'],['man：ifconfig','https://man7.org/linux/man-pages/man8/ifconfig.8.html']]
  }
];

for (const {points,refs,...lesson} of COVERAGE_JAVA_23) {
  window.LESSONS.push(lesson);
  window.KNOWLEDGE_POINTS[lesson.id]=points;
  window.LESSON_REFERENCES[lesson.id]=refs;
}
