#!/usr/bin/env node
/** Single publication manifest and validated loader shared by export and CI. */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { polishLessons } from './polish-readability.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
/** The only publication list. Add a script here to publish it; drafts stay out until then. */
export const publishedSources = [
  'lessons.js',
  'extra-lessons.js',
  'distributed-lessons.js',
  'knowledge-points.js',
  'coverage-lessons.js',
  'coverage-batch-03.js',
  'coverage-batch-04.js',
  'coverage-frontend-05.js',
  'coverage-java-05.js',
  'coverage-batch-06.js',
  'coverage-frontend-07.js',
  'coverage-java-07.js',
  'coverage-java-08.js',
  'coverage-frontend-08.js',
  'coverage-java-09.js',
  'coverage-frontend-09.js',
  'coverage-frontend-10.js',
  'coverage-frontend-11.js',
  'coverage-frontend-12.js',
  'coverage-frontend-13.js',
  'coverage-frontend-14.js',
  'coverage-frontend-15.js',
  'coverage-frontend-16.js',
  'coverage-frontend-17.js',
  'coverage-frontend-18.js',
  'coverage-frontend-19.js',
  'coverage-frontend-20.js',
  'coverage-frontend-21.js',
  'coverage-frontend-22.js',
  'coverage-frontend-23.js',
  'coverage-frontend-24.js',
  'coverage-frontend-25.js',
  'coverage-frontend-26.js',
  'coverage-frontend-27.js',
  'coverage-frontend-28.js',
  'coverage-frontend-29.js',
  'coverage-frontend-30.js',
  'coverage-frontend-31.js',
  'coverage-frontend-32.js',
  'coverage-frontend-33.js',
  'coverage-frontend-34.js',
  'coverage-frontend-35.js',
  'coverage-frontend-36.js',
  'coverage-frontend-37.js',
  'coverage-frontend-38.js',
  'coverage-frontend-39.js',
  'coverage-frontend-40.js',
  'coverage-frontend-41.js',
  'coverage-java-10.js',
  'coverage-java-11.js',
  'coverage-java-12.js',
  'coverage-java-13.js',
  'coverage-java-14.js',
  'coverage-java-15.js',
  'coverage-java-16.js',
  'coverage-java-17.js',
  'coverage-java-18.js',
  'coverage-java-19.js',
  'coverage-java-20.js',
  'coverage-java-21.js',
  'coverage-java-22.js',
  'coverage-java-23.js',
  'coverage-java-24.js',
  'coverage-java-25.js',
  'coverage-java-26.js',
  'coverage-java-27.js',
  'coverage-java-28.js',
  'coverage-java-29.js',
  'coverage-java-30.js',
  'coverage-java-31.js',
  'coverage-java-32.js',
  'coverage-java-33.js',
  'coverage-java-34.js',
  'coverage-java-35.js',
  'coverage-java-36.js',
  'coverage-java-37.js',
  'coverage-java-38.js',
  'coverage-java-39.js',
  'coverage-java-40.js',
  'coverage-java-41.js',
  'coverage-java-42.js',
  'coverage-java-43.js',
  'coverage-java-44.js',
  'coverage-java-45.js',
  'coverage-java-46.js',
  'coverage-java-47.js',
  'coverage-java-48.js',
  'coverage-java-49.js',
  'coverage-java-50.js',
  'coverage-java-51.js',
  'coverage-java-52.js',
  'coverage-java-53.js',
  'coverage-java-54.js',
  'coverage-java-55.js',
  'coverage-java-56.js',
  'coverage-java-57.js',
  'coverage-java-58.js',
  'coverage-java-59.js',
  'coverage-java-60.js',
  'coverage-java-61.js',
  'coverage-java-62.js',
  'coverage-java-63.js',
  'coverage-java-64.js',
  'coverage-java-65.js',
  'coverage-java-66.js',
  'coverage-java-67.js',
  'coverage-java-68.js',
  'coverage-java-69.js',
  'coverage-java-70.js',
  'coverage-java-71.js',
  'coverage-java-72.js',
  'coverage-java-73.js',
  'coverage-java-74.js',
  'coverage-java-75.js',
  'coverage-java-76.js',
  'coverage-java-77.js',
  'coverage-java-78.js',
  'coverage-java-79.js',
  'coverage-java-80.js',
  'coverage-java-81.js',
  'coverage-java-82.js',
  'coverage-java-83.js',
  'coverage-java-84.js',
  'coverage-java-85.js',
  'coverage-java-86.js',
  'coverage-java-87.js',
  'coverage-java-88.js',
  'coverage-java-89.js',
  'coverage-java-90.js',
  'coverage-java-91.js',
  'coverage-java-92.js',
  'coverage-java-93.js',
  'coverage-java-94.js',
  'coverage-java-95.js',
  'coverage-java-96.js',
  'coverage-java-97.js',
  'coverage-java-98.js',
  'coverage-java-99.js',
  'coverage-java-100.js',
  'coverage-java-101.js',
  'coverage-java-102.js',
  'coverage-path.js',
  'coverage-path-02.js',
  'coverage-path-03.js',
  'coverage-path-04.js',
  'coverage-path-05.js',
  'coverage-path-06.js',
  'coverage-path-07.js',
  'coverage-path-08.js',
  'coverage-path-09.js',
  'coverage-path-10.js',
  'coverage-path-11.js',
  'foundation-points.js',
  'coverage-chapters-10.js',
  'coverage-sca-12.js',
  'coverage-infra-13.js',
  'coverage-depth-14.js',
  'coverage-ship-15.js',
  'coverage-core-16.js',
  'coverage-ops-17.js',
  'answer-walkthrough.js',
  'example-code-blocks.js',
];

export const GROUP_ORDER = {
  frontend: [
    '全栈主线',
    '语言基础',
    'TypeScript',
    'CSS 与布局',
    '浏览器',
    '网络与安全',
    '安全',
    'React',
    'React 生态',
    'Vue',
    'Vue 生态',
    '技术选型',
    '微前端',
    'React Native',
    'Flutter',
    'UniApp 与 Taro',
    'Node.js',
    '测试',
    '工程实践',
  ],
  java: [
    '全栈主线',
    'Java 基础',
    '算法',
    '设计模式',
    'JVM',
    '并发',
    '数据库',
    '缓存',
    'Spring',
    'JPA',
    'MyBatis',
    '安全',
    'Nginx',
    '网关',
    'Netty',
    '消息队列',
    '搜索',
    'Spring Cloud Alibaba',
    '系统设计',
    '分布式与高并发',
    '交付与运行',
    '测试',
    '工程实践',
  ],
};

/** Sidebar labels. Prefer standard course names over cryptic abbreviations. */
export const GROUP_LABEL = {
  frontend: {
    全栈主线: '全栈主线',
    语言基础: 'JavaScript',
    TypeScript: 'TypeScript',
    'CSS 与布局': 'CSS',
    浏览器: '浏览器',
    '网络与安全': '网络与安全',
    安全: '安全',
    React: 'React',
    'React 生态': 'React 生态',
    Vue: 'Vue',
    'Vue 生态': 'Vue 生态',
    技术选型: '技术选型',
    微前端: '微前端',
    'React Native': 'React Native',
    Flutter: 'Flutter',
    'UniApp 与 Taro': '小程序',
    'Node.js': 'Node.js',
    测试: '测试',
    工程实践: '工程实践',
  },
  java: {
    全栈主线: '全栈主线',
    'Java 基础': 'Java 基础',
    算法: '算法',
    设计模式: '设计模式',
    JVM: 'JVM',
    并发: '并发',
    数据库: '数据库',
    缓存: '缓存',
    Spring: 'Spring',
    JPA: 'JPA',
    MyBatis: 'MyBatis',
    安全: '安全',
    Nginx: 'Nginx',
    网关: '网关',
    Netty: 'Netty',
    消息队列: '消息队列',
    搜索: '搜索',
    'Spring Cloud Alibaba': 'Spring Cloud Alibaba',
    系统设计: '系统设计',
    '分布式与高并发': '分布式',
    '交付与运行': '交付与运行',
    测试: '测试',
    工程实践: '工程实践',
  },
};

/** Subdirectories only where one chapter splits into different mechanisms. */
export const OUTLINE = {
  frontend: {
    全栈主线: [
      { title: '分层', ids: ['fs-four-layers', 'fs-page-feature'] },
      { title: '收尾', ids: ['fs-write-ui', 'fs-frontend-done'] },
    ],
    语言基础: [
      { title: '值与绑定', ids: ['js-equality', 'es6-const-binding', 'es6-destructure-copies', 'es6-default-param-call-time', 'es6-template-expression'] },
      { title: '作用域与对象', ids: ['js-scope-tdz', 'js-this-callsite', 'js-prototype-chain', 'js-not-everything-object', 'js-arrow-has-no-prototype', 'js-class-extends-super', 'js-private-field-hash'] },
      { title: '语法扩展', ids: ['es6-rest-spread-position', 'es6-map-set-keys', 'es6-symbol-key', 'js-optional-chaining', 'js-proxy-get-set-trap'] },
      { title: '异步', ids: ['eventloop', 'js-microtask-vs-macrotask', 'promise-chain', 'js-async-await', 'promise-all-and-settled'] },
      { title: '模块与迭代', ids: ['esm', 'es6-for-of-iterable', 'js-iteration-protocol', 'js-generator-yield-pause', 'js-async-generator-for-await', 'js-weakmap-lifetime'] },
      { title: '易错', ids: ['js-timer-fn-not-string', 'js-regex-dot-not-newline', 'js-json-stringify-not-equal', 'closure'] },
    ],
    TypeScript: [
      { title: '类型边界', ids: ['ts-unknown', 'ts-const-readonly', 'ts-type-vs-interface', 'ts-satisfies', 'ts-module-resolution', 'react-flow-not-default'] },
      { title: '类型', ids: ['ts-narrowing', 'ts-generics', 'ts-structural', 'ts-utility-types', 'ts-template-literal-types'] },
    ],
    'CSS 与布局': [
      { title: '盒模型与文档流', ids: ['css-box-sizing', 'css-position-flow', 'css-containing-block'] },
      { title: '层叠', ids: ['css-cascade', 'css-stacking'] },
      { title: 'Flex 与 Grid', ids: ['css-flex', 'css-grid-flex'] },
      { title: '现代特性', ids: ['css-container-query', 'css-has-parent', 'css-aspect-ratio'] },
    ],
    '网络与安全': [
      { title: 'HTTP', ids: ['http-methods', 'http-create-post-not-put', 'http-content-type-body', 'http-status-auth', 'fetch-credentials', 'api-error-contract', 'http-patch-rfc5789', 'http-503-unavailable', 'cookie-set-attributes', 'cookie-prefix-partitioned', 'long-poll-vs-websocket', 'sse-one-way-http-stream'] },
      { title: '请求', ids: ['ajax-page-update-not-a-library', 'fetch-platform-client', 'fetch-method-body-timeout', 'fetch-response-body-once', 'axios-rejects-http-errors', 'axios-shared-instance'] },
      { title: '传输', ids: ['http-connection-reuse', 'http-compression', 'http-range', 'http2-multiplex', 'tls-hostname-verify', 'tcp-is-l4-not-http-handshake', 'https-tls13-not-12-packets', 'tcp-stream-needs-framing', 'https-port-443-not-80', 'tcp-reliable-not-never-lose'] },
    ],
    浏览器: [
      { title: 'DOM 与事件', ids: ['dom-event-flow', 'html-dialog-modal'] },
      { title: '表单与 HTML', ids: ['html-form-semantics', 'html5-constraint-before-submit', 'formdata-multipart-upload', 'html5-main-landmark', 'html5-media-play-promise', 'html5-canvas-buffer', 'html5-pushstate-popstate', 'html5-dataset-string', 'html5-picture-source', 'html5-drop-prevent-default', 'miniprogram-wx-if-not-wxif'] },
      { title: '渲染', ids: ['browser-event-loop-frame', 'rendering', 'layout', 'image-loading'] },
      { title: '存储与缓存', ids: ['browser-storage', 'session-storage-tab-only', 'indexeddb-when-needed', 'http-cache', 'bfcache-pageshow', 'service-worker-stale', 'sw-cache-strategy-pick'] },
      { title: '同源与跨域', ids: ['cors', 'cors-credentials-allowlist', 'cors-preflight-max-age', 'same-origin-script-still-runs', 'html-form-cross-origin-navigate', 'fetch-abort'] },
    ],
    React: [
      { title: '状态', ids: ['linked-list', 'state-queue', 'react-setstate-batch', 'controlled-input', 'identity', 'effects', 'react-effect-timing', 'context', 'react-context-stable', 'react-props-state-sync', 'react-gdsfp-copy', 'react-hooks-over-hoc'] },
      { title: '渲染', ids: ['event-system', 'react-event-root', 'react-memo-when', 'react-fiber-interrupt', 'react-vdom-perf-bound', 'suspense', 'react-error-boundary'] },
      { title: '旧版', ids: ['react-version-checklist', 'react-createclass-gone'] },
    ],
    Vue: [
      { title: '响应式', ids: ['vue-reactivity', 'vue-defineproperty-proxy', 'vue-proxy-null-guard', 'vue-array-raw-proxy', 'vue-computed-watch', 'vue-nexttick'] },
      { title: '组件', ids: ['vue-props-one-way', 'vue-list-key', 'vue-composition-options', 'vue-modal-programmatic', 'vue-vnode-not-fragment'] },
      { title: '打包', ids: ['vue-design-goals-proxy', 'vue-tree-shake-options', 'vue-tree-shake-faster', 'vue-patch-hoist'] },
    ],
    'Vue 生态': [
      { title: '路由', ids: ['vue-router-reuse', 'vue-router-guard', 'vue-router-scroll'] },
      { title: '状态', ids: ['pinia-not-vuex', 'pinia-store-to-refs', 'vue-keep-alive', 'nuxt-payload'] },
    ],
    'UniApp 与 Taro': [
      { title: 'uni-app', ids: ['uniapp-x-uts-not-vue-page', 'uniapp-pages-json-entry', 'uniapp-onload-vs-onshow', 'uniapp-ifdef-stripped'] },
      { title: 'Taro', ids: ['taro-react-setdata-bridge', 'taro-pages-in-app-config', 'taro-4-compiler-choice', 'taro-and-uniapp-layers'] },
    ],
    技术选型: [
      { title: '目标端', ids: ['fe-pick-by-surface', 'fe-ui-update-model'] },
      { title: '框架', ids: ['fe-react-framework-first', 'fe-vue-official-slots', 'fe-angular-first-party', 'fe-sveltekit-runes'] },
      { title: '生态', ids: ['fe-ecosystem-follows-model', 'fe-react-one-slot', 'fe-vue-data-one-slot', 'fe-angular-resource-not-ngrx', 'fe-svelte-load-not-store'] },
      { title: '跨端', ids: ['fe-cross-end-one-runtime', 'fe-expo-router-one-nav', 'fe-flutter-state-one-approach', 'fe-server-state-one-owner'] },
    ],
    微前端: [
      { title: '边界', ids: ['mfe-when-to-split', 'mfe-not-for-everything', 'mfe-composition-models'] },
      { title: '选型', ids: ['mfe-pick-by-constraint', 'mfe-compare-matrix', 'mfe-pick-one-path'] },
      { title: '方案', ids: ['mfe-mf-host-setup', 'mfe-vite-federation', 'mfe-singlespa-register', 'mfe-qiankun-html-entry', 'mfe-wujie-startapp', 'mfe-iframe-postmessage'] },
      { title: '集成', ids: ['mfe-module-federation', 'mfe-shared-deps', 'mfe-runtime-lifecycle'] },
      { title: '运行时', ids: ['mfe-routing-one-history', 'mfe-style-isolation', 'mfe-shared-auth'] },
      { title: '交付', ids: ['mfe-independent-deploy', 'mfe-perf-cost', 'mfe-contract-version'] },
    ],
    'React 生态': [
      { title: '路由', ids: ['react-router-loader', 'react-router-element-api', 'react-router-error-element', 'rr-mode-gates-data', 'rr-outlet-keeps-layout', 'rr-redirect-before-render'] },
      { title: '状态', ids: ['state-kind-picks-home', 'state-reducer-context-screen'] },
      { title: '数据', ids: ['react-rsc-vs-client', 'query-cache-not-http-client', 'query-fn-calls-the-client', 'query-server-state', 'query-invalidate', 'redux-rtk-today'] },
    ],
    'React Native': [
      { title: '界面', ids: ['rn-view-not-div', 'rn-text-not-under-view', 'rn-flex-defaults', 'rn-pressable-not-click'] },
      { title: '列表', ids: ['rn-flatlist-window', 'rn-image-needs-size', 'rn-dimensions-not-cached', 'rn-platform-extension'] },
      { title: '运行时', ids: ['rn-hermes-default', 'rn-jsi-not-json-bridge', 'rn-navigate-not-push', 'rn-fetch-not-document'] },
    ],
    Flutter: [
      { title: '界面', ids: ['flutter-widget-not-html', 'flutter-impeller-own-pixels', 'flutter-constraints-down', 'flutter-setstate-rebuilds'] },
      { title: '导航', ids: ['flutter-gorouter-not-named', 'cross-four-who-paints', 'cross-four-where-it-fits'] },
    ],
    安全: [
      { title: '登录', ids: ['cookie-credential', 'auth-session-vs-jwt', 'csrf-boundary'] },
      { title: '页面', ids: ['xss', 'client-env-public', 'csp-script-src', 'csp-report-only-not-enforce', 'trusted-types-sink-guard', 'permissions-policy-feature-gate', 'document-policy-not-permissions-policy', 'coop-coep-cross-origin-isolated', 'referrer-policy-leak-bound', 'sri-integrity-not-csp', 'clear-site-data-not-full-logout', 'reporting-nel-not-csp-enforce', 'corp-embed-gate-not-cors', 'pna-private-network-access', 'fenced-frame-embed-boundary', 'attribution-reporting-not-cookie'] },
    ],
    测试: [
      { title: '组件', ids: ['frontend-testing', 'testing-library-role', 'test-mock-boundary', 'test-fake-timers', 'react-enzyme-not-default'] },
      { title: '契约测试', ids: ['playwright-user-journey', 'contract-test-path', 'msw-http-mock'] },
    ],
    'Node.js': [
      { title: '请求', ids: ['node-http-cookie', 'node-unhandled-rejection', 'node-emitter', 'node-global-fetch', 'node-http-close'] },
      { title: '事件循环', ids: ['node-nexttick', 'node-event-loop-phases', 'node-libuv-threadpool', 'node-stream', 'node-buffer', 'node-worker-cluster'] },
    ],
    工程实践: [
      { title: '构建', ids: ['vite-module-graph', 'build-code-splitting', 'build-cache', 'ssr-hydration', 'react-ssr-not-fewer-http', 'vite-sourcemap-prod', 'webpack-eval-sourcemap-dev-only', 'angular-ngonchanges-primitives'] },
      { title: '性能', ids: ['web-vitals', 'performance', 'accessibility'] },
      { title: '排查', ids: ['fe-slow-page-where', 'fe-tune-one-layer'] },
      { title: '发布', ids: ['vite-env-client-prefix', 'ci-gate-not-only-build', 'retired-frontend-stack'] },
    ],
  },
  java: {
    全栈主线: [
      { title: '写入', ids: ['fs-boot-chain', 'fs-write-invariant'] },
      { title: '读取', ids: ['fs-read-shape', 'fs-ship-bar'] },
    ],
    'Java 基础': [
      { title: '入门与类型', ids: ['java-main-launcher', 'java-pass-by-value', 'java-autoboxing-cache', 'java-string-immutability', 'java-string-new-vs-pool', 'java-generics', 'java-record-accessor', 'java-equals-contract'] },
      { title: '面向对象', ids: ['java-interface-contract', 'java-polymorphism-not-only-extends', 'java-protected-other-pkg-subclass', 'java-anonymous-extends-or-implements', 'java-default-class-wins-conflict', 'java-ctor-implicit-super-noarg'] },
      { title: '异常', ids: ['java-exceptions', 'java-unchecked-not-must-catch', 'java-runtime-ex-not-auto-caught', 'java-optional', 'java-finalize-not-guaranteed', 'java-clone-exception-checked'] },
      { title: '集合', ids: ['java-collections', 'java-arraylist-linkedlist', 'java-stack-prefer-deque', 'java-set-not-always-sorted', 'java-collection-vs-collections', 'java-arrays-aslist-fixed', 'java-stream', 'java-foreach-remove-cme', 'hashmap-initial-16-not-max', 'hashmap-treeify-need-capacity', 'chm-jdk8-not-segment-lock', 'chm-iterator-weakly-consistent', 'java-vector-cme-not-because-sync', 'java-enumeration-not-faster'] },
      { title: '字符串与时间', ids: ['java-stringbuilder-not-buffer', 'java-time-instant', 'java-charset-default', 'java-string-strip-not-trim', 'java-pattern-dot-not-nl'] },
      { title: '易错', ids: ['java-calendar-not-singleton', 'java-dcl-volatile-enum', 'java-long-atomic-on-64bit', 'jdk-feature-release-six-months', 'java-not-every-class-clone-serializable', 'java-raw-type-skips-checks', 'java-class-newinstance-deprecated', 'java-final-not-fifty-percent', 'java-shift-not-times-eight', 'java-switch-arrow-no-fall'] },
    ],
    算法: [
      { title: '查找', ids: ['complexity', 'algo-hash-lookup', 'java-binary-search', 'algo-stable-sort', 'hash-open-addressing-probe', 'quicksort-average-nlogn'] },
      { title: '树与图', ids: ['algo-two-pointers', 'algo-tree-walk', 'bfs', 'java-priority-queue'] },
      { title: '窗口与拓扑', ids: ['algo-sliding-window', 'algo-topo-kahn'] },
    ],
    设计模式: [
      { title: '总览', ids: ['pattern-gof-catalog', 'pattern-family-test', 'pattern-gof-rest', 'pattern-one-variation'] },
      { title: '创建型', ids: ['pattern-factory-method', 'pattern-builder-assemble', 'pattern-singleton-scope'] },
      { title: '结构型', ids: ['pattern-adapter-shape', 'pattern-decorator-contract', 'pattern-proxy-stand-in', 'pattern-facade-entry', 'pattern-bridge-two-axes', 'pattern-composite-tree', 'pattern-flyweight-share'] },
      { title: '行为型', ids: ['pattern-strategy-swap', 'pattern-template-steps', 'pattern-observer-push', 'pattern-chain-stop', 'pattern-state-transition'] },
      { title: 'Java 标准库', ids: ['java-comparator-strategy', 'java-buffered-stream-decorator', 'java-proxy-needs-interface', 'java-unmodifiable-is-view', 'java-runnable-is-command'] },
      { title: 'Spring', ids: ['spring-factorybean-product', 'spring-event-sync-default', 'spring-jdbctemplate-callback', 'spring-getbean-hides-deps'] },
    ],
    Spring: [
      { title: '容器', ids: ['spring-ioc-wiring', 'spring-bean-lifecycle', 'spring-scopes', 'spring-scope-catalog', 'spring-external-config', 'spring-legacy-config', 'spring-boot-war-still-ok', 'spring-boot3-autoconfig-imports', 'tomcat-nio-not-bio-default', 'spring-xmlbeanfactory-removed'] },
      { title: '请求', ids: ['spring-mvc-dispatch', 'spring-mvc-exception', 'spring-filter-vs-interceptor', 'spring-validation-binding', 'spring-mvc-restcontroller', 'spring-mvc-controller-singleton'] },
      { title: '切面', ids: ['spring-aop-proxy-type', 'spring-aop-self-invocation', 'spring-boot-aop-cglib-default'] },
      { title: '事务', ids: ['spring-transaction', 'spring-rollback', 'spring-propagation'] },
    ],
    JPA: [
      { title: '实体', ids: ['jpa-entity-identity', 'jpa-session-nplus1', 'jpa-flush-transaction', 'jpa-osiv-boundary', 'jpa-dirty-check'] },
      { title: '关联', ids: ['jpa-optimistic-lock', 'jpa-cascade-orphan'] },
      { title: '更新', ids: ['jpa-page-vs-slice', 'jpa-modifying-clear', 'jpa-entity-graph'] },
    ],
    MyBatis: [
      { title: 'SQL', ids: ['mybatis-mapper-bound', 'mybatis-parameters', 'mybatis-resultmap', 'mybatis-dynamic-sql', 'mybatis-type-handler', 'mybatis-lazy-javassist-not-cglib'] },
      { title: '执行', ids: ['mybatis-local-cache', 'mybatis-batch-executor', 'mybatis-plugin-interceptor', 'mybatis-rowbounds-memory', 'mybatis-second-cache'] },
      { title: '分页', ids: ['mybatis-log-preparing-parameters', 'mybatis-jdbc-log-inlines', 'mybatis-debug-boundsql', 'mybatis-pagehelper-next-query', 'mybatis-plus-page-argument', 'mybatis-middleware-layers'] },
    ],
    缓存: [
      { title: '键与类型', ids: ['redis-data-types', 'redis-hash-field-update', 'redis-zset-rank-range', 'redis-geo-on-zset-not-gis', 'redis-hyperloglog-approx', 'cache-aside-steps', 'cache-db-double-write-race', 'redis-client-side-cache-invalidate', 'redis-wait-replicas-not-durability', 'redis-hello-resp3-not-just-version', 'redis-big-hot-key', 'redis-expire', 'redis-eviction-policy-menu', 'cache-penetration-vs-breakdown', 'redis-fifo-not-maxmemory', 'cache-local-vs-distributed', 'redis-string-max-512mb', 'redis-list-quicklist-listpack', 'lru-needs-hash-and-list'] },
      { title: '集群', ids: ['redis-persistence', 'redis-transaction', 'redis-single-thread', 'redis-sentinel-cluster', 'redis-pipeline', 'redis-legacy-vm-limits', 'redis-repl-psync-not-sql', 'redis-aof-keeps-rdb', 'redis-cluster-cli-not-trib', 'redis-proxy-hash-not-cluster', 'redis-save-blocks-bgsave', 'redis-cluster-incr-not-five-steps'] },
      { title: '脚本', ids: ['redis-lua-atomic', 'redis-functions-not-just-eval', 'redis-acl-not-just-requirepass', 'redis-multi-vs-lua-pick', 'redis-stream-vs-pubsub', 'redis-pubsub-pattern-subscribe', 'redis-stream-xtrim-bound', 'redis-keyspace-notify-not-queue', 'redis-pubsub-not-reliable-queue'] },
    ],
    Nginx: [
      { title: '反向代理', ids: ['nginx-request-phases', 'nginx-upstream-passive', 'nginx-proxy-timeout', 'nginx-gunzip-not-compress', 'nginx-load-module', 'nginx-proxy-host', 'nginx-ip-hash-session', 'nginx-forward-not-direct', 'cdn-not-just-reverse-proxy-cache'] },
      { title: '限速', ids: ['nginx-static-cache-headers', 'nginx-limit-req', 'nginx-buffer-body', 'nginx-limit-req-not-iptables-loop'] },
    ],
    Netty: [
      { title: '线程', ids: ['netty-event-loop', 'netty-pipeline-handler', 'netty-bytebuf-leak', 'nio-not-one-thread-per-request', 'epoll-et-must-drain'] },
      { title: '解码', ids: ['netty-idle-heartbeat', 'netty-codec-shareable'] },
      { title: '发送', ids: ['netty-watermark-backpressure', 'netty-length-field-frame', 'netty-file-region'] },
    ],
    网关: [
      { title: '路由', ids: ['mw-proxy-lb-gateway', 'gateway-route-predicate', 'gateway-one-hop'] },
      { title: '超时', ids: ['gateway-retry-idempotent', 'gateway-timeout-chain'] },
      { title: '鉴权', ids: ['gateway-auth-where', 'gateway-body-buffer', 'gateway-websocket-upgrade'] },
    ],
    搜索: [
      { title: '查询', ids: ['es-inverted-index', 'es-lucene-not-btree', 'elastic-analysis', 'es-filter-context', 'es-refresh-visibility', 'es-term-lookup-not-o1'] },
      { title: '分页', ids: ['es-search-after', 'es-mapping-reindex'] },
      { title: '聚合', ids: ['es-aggregations', 'es-custom-routing'] },
    ],
    数据库: [
      { title: '表', ids: ['mysql-null-comparison', 'mysql-not-null-default-not-absolute', 'mysql-check-enforced-not-parsed-only', 'sql-outer-join-where', 'mysql-inner-join-match', 'mysql-join-ban-not-absolute', 'mysql-or-not-must-become-in', 'mysql-where-having', 'mysql-group-by-having', 'mysql-window-keeps-rows', 'mysql-union-distinct', 'mysql-second-nf', 'mysql-select-star', 'mysql-text-ban-not-absolute', 'mysql-varchar-length', 'mysql-varchar-row-max', 'mysql-wide-column-split', 'mysql-fk-redundancy', 'schema-migration', 'mysql-datetime-vs-timestamp', 'mysql-float-ieee-not-8-digits', 'mysql-money-decimal-not-ban', 'mysql-split-not-at-ten-million', 'mysql-json-not-document-db', 'mysql-view-is-stored-query', 'mysql-procedure-not-auto-txn', 'mysql-trigger-side-effect-hidden', 'mysql-cte-named-subquery', 'mysql-enum-ban-not-absolute', 'mysql-temp-table-vs-cte', 'mysql-utf8-alias-not-utf8mb4', 'mysql-fk-ban-not-absolute', 'mysql-phone-varchar-length-not-twenty', 'mysql-insert-must-name-columns', 'mysql-innodb-default-not-ban-others', 'mysql-db-not-blob-store', 'mysql-instance-table-count-not-500', 'mysql-column-count-thirty-not-law', 'mysql-db-features-ban-not-absolute', 'mysql-ddl-merge-heuristic', 'mysql-catch-sql-exception-not-enough', 'mysql-pk-autoinc-not-only-choice', 'mysql-subquery-ban-not-absolute', 'mysql-scalability-not-hopeless', 'db-proxy-layer-not-only-choice', 'hot-cold-ratio-not-fixed-one-to-four', 'business-split-db-not-only-path', 'rw-split-not-strong-consistency'] },
      { title: '表设计', ids: ['table-design-from-facts', 'table-row-one-grain', 'table-constraint-holds-rule'] },
      { title: '索引', ids: ['mysql-index', 'mysql-index-kinds', 'mysql-explain-analyze', 'mysql-innodb-fulltext', 'mysql-spatial-index-not-full-gis', 'mysql-innodb-index-lock', 'mysql-unique-change-buffer', 'mysql-prefix-index-and-cost', 'mysql-covering-not-index-kind', 'mysql-innodb-no-user-hash', 'mysql-index-count-five-not-law', 'mysql-implicit-convert-breaks-index', 'mysql-where-func-blocks-index', 'mysql-generated-column-not-where-wrap', 'mysql-negative-predicate-not-always-scan', 'mysql-leading-percent-like-heuristic', 'mysql-low-selectivity-index-heuristic', 'mysql-composite-selectivity-order-heuristic', 'mysql-count-star-innodb-not-always-scan', 'mysql-extend-index-before-new', 'mysql-and-order-optimizer-reorders', 'mysql-right-fuzzy-like-can-use-index', 'mysql-invisible-index-not-drop'] },
      { title: '慢查询', ids: ['mysql-slow-sql-locate', 'mysql-slow-sql-optimize'] },
      { title: '事务', ids: ['mysql-mvcc', 'mysql-mvcc-not-two-version-columns', 'mysql-isolation', 'mysql-isolation-levels', 'mysql-deadlock', 'mysql-upsert', 'mongo-multi-doc-txn', 'mongo-bson-use-lazy', 'mysql-acid-c-is-consistency', 'nosql-label-not-eventual'] },
      { title: '复制', ids: ['mysql-myisam-innodb', 'mysql-innodb-tablespace', 'mysql-binlog-format', 'mysql-replication-flow', 'mysql-replica-lag', 'mysql-prepared-statement', 'mysql-buffer-pool-size', 'mysql-query-cache-removal', 'mysql-replica-parallel-applier', 'mysql-redo-undo-binlog', 'mysql-pt-checksum-pk', 'mysql-initialize-not-install-db', 'mysql-autoinc-persists-8'] },
    ],
    并发: [
      { title: '锁', ids: ['java-thread-start-run', 'java-concurrency', 'java-happens-before', 'java-interrupt', 'java-reentrant-lock', 'java-lock-flexibility', 'java-wait-sleep', 'java-barrier-latch', 'java-concurrent-map', 'java-synchronized-monitor', 'java-aqs-not-futuretask', 'java-rwlock-no-upgrade', 'java-cas-aba-stamp', 'java-sync-not-all-methods', 'java-thread-six-states'] },
      { title: '线程池', ids: ['java-executor', 'java-virtual-threads', 'java-future-errors', 'java-thread-local-leak', 'java-fork-join-pool', 'java-executors-factory-oom', 'java-linked-blocking-unbounded', 'java-tpe-execute-order', 'java-loom-not-absent-coroutine', 'java-threads-not-linear-speedup', 'thread-pool-formula-not-law'] },
    ],
    JVM: [
      { title: '结构', ids: ['jvm-areas', 'java-classloading', 'java-memory', 'jvm-method-area-metaspace', 'jvm-platform-classloader-not-ext', 'jvm-jmm-not-runtime-areas', 'jvm-pc-no-oom', 'jmm-not-eight-memory-ops', 'java-heap-not-cpp-manual', 'jvm-xmx-not-container-limit'] },
      { title: 'GC', ids: ['jvm-gc-choice', 'java-gc', 'jvm-oom-signals', 'java-soft-ref-not-oom-proof', 'jvm-no-permgen-hotspot', 'jvm-tenuring-threshold-15', 'jvm-full-gc-not-permgen', 'jvm-major-gc-not-always-full', 'jvm-cms-removed-g1-default'] },
      { title: '诊断', ids: ['jvm-safepoint', 'jvm-jit-tiered', 'jvm-thread-vs-heap-dump'] },
    ],
    安全: [
      { title: '鉴权', ids: ['spring-security-filter-chain', 'spring-authn-authz', 'object-level-authz', 'spring-oauth2-resource', 'sshd-rate-limit-not-lastb'] },
      { title: '口令', ids: ['password-adaptive-hash', 'spring-csrf-spa', 'spring-security-cors', 'runtime-config', 'spring-session-stateless', 'jwt-payload-not-encrypted'] },
    ],
    测试: [
      { title: '用例', ids: ['junit-instance-lifecycle', 'test-one-behavior', 'test-observable-result'] },
      { title: '测试切片', ids: ['spring-test-slice', 'spring-test-transaction-rollback', 'testcontainers-real-db', 'spring-dirties-context'] },
    ],
    消息队列: [
      { title: '选型', ids: ['mq-why-decouple', 'mq-delivery-semantics', 'mq-compare-matrix', 'mq-pick-workload', 'mq-backpressure-producer', 'mq-dlq-backlog', 'mq-consume-idempotent-key', 'mq-delete-not-always-idempotent', 'mq-backlog-expand-queues'] },
      { title: 'Kafka', ids: ['kafka-model', 'kafka-producer-acks', 'kafka-isr-hwm', 'kafka-offset', 'kafka-rebalance', 'kafka-kraft-not-zk', 'kafka-producer-does-batch', 'kafka-isr-lag-time-not-count', 'kafka-partitions-increase-only'] },
      { title: 'RabbitMQ', ids: ['rabbit-model', 'rabbit-exchange-binding', 'rabbit-ack', 'rabbit-ha-queue', 'rabbit-queue-not-unbounded'] },
      { title: 'RocketMQ', ids: ['rocketmq-model', 'rocketmq-queue-order', 'rocketmq-flush-ha', 'rocketmq-store-not-ram-buffer', 'rocketmq-send-oneway-may-drop'] },
      { title: '其他', ids: ['activemq-jms-model', 'pulsar-segment-model', 'activemq-prefetch-limit', 'activemq-queue-competing-consumers'] },
    ],
    'Spring Cloud Alibaba': [
      { title: '总览', ids: ['sca-what', 'sca-component-map', 'sca-one-call'] },
      { title: 'Nacos', ids: ['sca-nacos-intro', 'sca-nacos-register', 'sca-nacos-config', 'config-center-poll-needs-watch', 'sca-nacos-ephemeral', 'sca-nacos-shared-config', 'sca-deregister-shutdown', 'eureka-lease-30-90'] },
      { title: '调用', ids: ['sca-feign-timeout-retry', 'sca-dubbo-or-feign', 'sca-stream-binding', 'dubbo-loadbalance-random-default', 'dubbo-hessian-zk-not-frozen', 'dubbo-registry-down-local-cache', 'dubbo-timeout-retry-idempotent', 'spring-cloud-feign-not-lb'] },
      { title: 'Sentinel', ids: ['sca-sentinel-intro', 'sca-sentinel-block', 'sca-sentinel-circuit-state', 'sca-sentinel-block-fallback', 'sca-sentinel-flow-mode', 'sca-circuit-not-only-hystrix'] },
      { title: 'Seata', ids: ['sca-seata-intro', 'sca-seata-at-boundary', 'sca-seata-tcc-empty', 'sca-seata-lock-timeout'] },
      { title: '其他', ids: ['sca-rocketmq-intro', 'sca-oss-intro', 'sca-schedulerx-intro', 'sca-sms-intro'] },
    ],
    系统设计: [
      { title: '拆分', ids: ['arch-evolution-stages', 'arch-monolith-when', 'arch-modular-boundary', 'arch-scale-before-split', 'arch-microservice-split', 'arch-split-order-case', 'arch-sync-vs-async'] },
      { title: '通用能力', ids: ['idempotency', 'cache', 'message-delivery', 'rate-limit', 'sql-keyset-page'] },
      { title: '容量', ids: ['arch-slo-budget', 'arch-queue-wait', 'arch-design-one-path'] },
      { title: '领域驱动', ids: ['ddd-same-word-two-contexts', 'ddd-aggregate-transaction-boundary', 'ddd-entity-or-value', 'ddd-repository-one-entry'] },
    ],
    '分布式与高并发': [
      { title: '一致性', ids: ['distributed-cap', 'base-slogan-not-ban-tx', 'distributed-consistency-three-words', 'distributed-xa', 'distributed-outbox', 'distributed-lock', 'dist-lock-owner-not-mac-pid-tid', 'dist-lock-reentrant-not-deadlock-cure', 'zk-linearizable-not-realtime', 'zk-odd-count-not-quorum-law', 'redis-lock-setnx-expire-race', 'redis-lock-getset-wall-clock', 'mysql-for-update-not-dist-lease', 'db-insert-unique-cron-not-lease', 'cap-label-not-product-tattoo', 'sync-replication-not-only-durability', 'snowflake-params-need-capacity-math'] },
      { title: '事务', ids: ['distributed-one-db-first', 'distributed-tx-not-cover-rpc', 'distributed-xid-must-travel', 'distributed-at-sees-before-global', 'distributed-saga-is-new-action', 'distributed-saga-who-drives', 'distributed-idempotent-key', 'distributed-read-your-writes', 'distributed-reconcile-last'] },
      { title: '流量', ids: ['distributed-token-bucket', 'leaky-bucket-not-no-critical-edge', 'distributed-seckill', 'seckill-js-needs-cache-control', 'seckill-client-gate-not-enough', 'seckill-mq-not-only-db-valve', 'distributed-mq-not-erase-invariant', 'distributed-consistent-hash', 'consistent-hash-vnode-count-not-law', 'distributed-bloom', 'distributed-cache', 'lru-capacity-not-ttl-expire', 'distributed-kafka-order', 'dns-lb-not-just-round-robin', 'http-redirect-lb-two-hops', 'microservices-not-just-soa-relabel', 'split-vs-cluster-not-interchangeable', 'service-extract-not-only-connection-math', 'select-not-always-business-idempotent', 'hash-skew-not-only-virtual-nodes', 'message-order-not-always-required'] },
      { title: '隔离', ids: ['distributed-clock-skew', 'distributed-unique-id', 'distributed-bulkhead', 'mysql-uuid-not-clustered-pk', 'uuid-not-only-random-string', 'db-sequence-batch-not-gapless', 'db-autoinc-offset-step-needs-ops'] },
    ],
    '交付与运行': [
      { title: 'CI', ids: ['gha-workflow-in-dot-github', 'gha-job-needs-success', 'gha-artifact-between-jobs', 'jenkins-not-only-ci-tool'] },
      { title: '镜像', ids: ['docker-layer-cache-copy', 'compose-service-name-dns', 'container-shares-host-kernel', 'docker-image-template-not-container', 'vm-vs-container-isolation-tradeoff', 'one-container-one-service-heuristic', 'docker-registry-not-just-repo-bucket'] },
      { title: '集群', ids: ['kubeadm-cni-before-coredns', 'kubeadm-control-plane-taint'] },
      { title: '工作负载', ids: ['k8s-pod-share-localhost', 'k8s-deploy-not-lone-pod'] },
      { title: '对外访问', ids: ['k8s-service-clusterip', 'k8s-ingress-needs-controller'] },
    ],
    工程实践: [
      { title: '可观测性', ids: ['request-trace-one-hop', 'otel-three-signals', 'java-http-timeout', 'hikari-pool-timeout', 'jdbc-datasource-not-diy-pool', 'spring-graceful-shutdown', 'log-correlation-id', 'zabbix-active-at-scale'] },
      { title: '排查', ids: ['server-slow-which-resource', 'backend-tune-the-span', 'cpu-cache-line-sharing', 'cpu-heap-not-cpu-cache'] },
      { title: '发布运维', ids: ['design-review', 'docker-multistage', 'k8s-probes', 'k8s-memory-limit', 'secrets-not-in-image', 'spring-boot-devtools-restarts', 'git-restore-over-checkout', 'linux-bkl-gone', 'k8s-runtime-not-only-docker', 'linux-root-group-not-root', 'linux-fork-copies-one-thread', 'docker-root-not-host-root', 'etcd-v3-grpc-not-rest', 'git-default-branch-not-master', 'retired-spring-cloud-netflix'] },
    ],
  },
};

export const PATH_LEAD = {
  frontend: {
    全栈主线: ['fs-four-layers', 'fs-page-feature', 'fs-write-ui', 'fs-frontend-done'],
    'CSS 与布局': [
      'css-box-sizing',
      'css-position-flow',
      'css-containing-block',
      'css-cascade',
      'css-stacking',
      'css-flex',
      'css-grid-flex',
      'css-container-query',
      'css-has-parent',
      'css-aspect-ratio',
    ],
    浏览器: [
      'dom-event-flow',
      'html-dialog-modal',
      'html-form-semantics',
      'browser-event-loop-frame',
      'rendering',
      'layout',
      'image-loading',
      'browser-storage',
      'http-cache',
      'cors',
      'fetch-abort',
    ],
    '网络与安全': [
      'api-error-contract',
      'http-methods',
      'http-create-post-not-put',
      'http-connection-reuse',
      'http-range',
      'http-compression',
      'http-status-auth',
      'fetch-credentials',
    ],
    安全: ['cookie-credential', 'auth-session-vs-jwt', 'csrf-boundary', 'xss', 'client-env-public'],
    TypeScript: [
      'ts-unknown',
      'ts-const-readonly',
      'ts-type-vs-interface',
      'ts-structural',
      'ts-narrowing',
      'ts-generics',
    ],
    React: ['identity', 'linked-list', 'react-memo-when'],
    'React 生态': ['react-rsc-vs-client', 'react-router-loader', 'query-server-state'],
    测试: [
      'frontend-testing',
      'testing-library-role',
      'test-mock-boundary',
      'playwright-user-journey',
      'contract-test-path',
    ],
    工程实践: ['vite-module-graph'],
    语言基础: [
      'js-equality',
      'es6-const-binding',
      'js-scope-tdz',
      'js-this-callsite',
      'js-prototype-chain',
      'eventloop',
      'js-microtask-vs-macrotask',
      'promise-chain',
      'js-async-await',
      'esm',
      'es6-for-of-iterable',
    ],
    'Node.js': [
      'node-http-cookie',
      'node-emitter',
      'node-unhandled-rejection',
      'node-nexttick',
      'node-stream',
      'node-buffer',
    ],
  },
  java: {
    全栈主线: ['fs-boot-chain', 'fs-write-invariant', 'fs-read-shape', 'fs-ship-bar'],
    'Java 基础': [
      'java-main-launcher',
      'java-pass-by-value',
      'java-autoboxing-cache',
      'java-string-immutability',
      'java-generics',
      'java-interface-contract',
      'java-polymorphism-not-only-extends',
      'java-exceptions',
      'java-optional',
      'java-collections',
      'java-arraylist-linkedlist',
      'java-stream',
      'java-time-instant',
    ],
    算法: [
      'complexity',
      'java-binary-search',
      'algo-two-pointers',
      'algo-hash-lookup',
      'algo-tree-walk',
      'bfs',
      'java-priority-queue',
    ],
    JVM: ['jvm-areas', 'java-classloading', 'java-memory', 'jvm-gc-choice', 'java-gc', 'jvm-oom-signals'],
    并发: [
      'java-thread-start-run',
      'java-concurrency',
      'java-happens-before',
      'java-interrupt',
      'java-reentrant-lock',
      'java-concurrent-map',
      'java-executor',
      'java-future-errors',
      'java-virtual-threads',
    ],
    消息队列: [
      'mq-why-decouple',
      'mq-delivery-semantics',
      'mq-compare-matrix',
      'mq-pick-workload',
      'kafka-model',
      'kafka-producer-acks',
      'kafka-isr-hwm',
      'kafka-offset',
      'kafka-rebalance',
      'rabbit-model',
      'rabbit-exchange-binding',
      'rabbit-ack',
      'rabbit-ha-queue',
      'rocketmq-model',
      'rocketmq-queue-order',
      'rocketmq-flush-ha',
      'activemq-jms-model',
      'pulsar-segment-model',
      'mq-dlq-backlog',
      'mq-backpressure-producer',
    ],
    系统设计: [
      'arch-evolution-stages',
      'arch-monolith-when',
      'arch-modular-boundary',
      'arch-scale-before-split',
      'arch-microservice-split',
      'arch-split-order-case',
      'arch-sync-vs-async',
      'idempotency',
      'cache',
      'message-delivery',
      'rate-limit',
      'sql-keyset-page',
    ],
    数据库: ['mysql-null-comparison', 'sql-outer-join-where', 'schema-migration'],
    Spring: [
      'spring-ioc-wiring',
      'spring-bean-lifecycle',
      'spring-scopes',
      'spring-scope-catalog',
      'spring-mvc-dispatch',
      'spring-mvc-exception',
      'spring-transaction',
      'spring-rollback',
      'spring-propagation',
      'spring-external-config',
      'spring-legacy-config',
    ],
    JPA: ['jpa-entity-identity', 'jpa-session-nplus1', 'jpa-flush-transaction', 'jpa-osiv-boundary'],
    MyBatis: ['mybatis-mapper-bound', 'mybatis-parameters', 'mybatis-resultmap', 'mybatis-dynamic-sql'],
    缓存: ['redis-data-types', 'cache-aside-steps', 'redis-big-hot-key', 'redis-expire', 'redis-persistence', 'redis-transaction'],
    Nginx: [
      'nginx-request-phases',
      'nginx-upstream-passive',
      'nginx-proxy-timeout',
      'nginx-static-cache-headers',
      'cdn-not-just-reverse-proxy-cache',
    ],
    Netty: ['netty-event-loop', 'netty-pipeline-handler', 'netty-bytebuf-leak'],
    网关: ['mw-proxy-lb-gateway', 'gateway-route-predicate', 'gateway-one-hop'],
    搜索: ['es-inverted-index', 'elastic-analysis', 'es-filter-context', 'es-refresh-visibility'],
    安全: [
      'spring-security-filter-chain',
      'spring-authn-authz',
      'object-level-authz',
      'password-adaptive-hash',
      'runtime-config',
    ],
    测试: ['junit-instance-lifecycle', 'test-one-behavior', 'spring-test-slice', 'test-observable-result'],
    工程实践: ['request-trace-one-hop', 'otel-three-signals'],
  },
};

/**
 * Introduced-in version for teaching navigation (official baseline, not marketing).
 * Applied at load; lessons may also set `since` in source. Prefer JDK / ES20xx / HTML5 / CSS names.
 */
export const LESSON_SINCE = {
  // JavaScript language (ECMAScript editions)
  'js-equality': 'ES2015',
  'es6-const-binding': 'ES2015',
  'es6-destructure-copies': 'ES2015',
  'es6-default-param-call-time': 'ES2015',
  'es6-template-expression': 'ES2015',
  'js-scope-tdz': 'ES2015',
  'js-prototype-chain': 'ES2015',
  'js-arrow-has-no-prototype': 'ES2015',
  'js-class-extends-super': 'ES2015',
  'js-private-field-hash': 'ES2022',
  'es6-rest-spread-position': 'ES2015',
  'es6-map-set-keys': 'ES2015',
  'es6-symbol-key': 'ES2015',
  'js-optional-chaining': 'ES2020',
  'js-proxy-get-set-trap': 'ES2015',
  'promise-chain': 'ES2015',
  'js-async-await': 'ES2017',
  'promise-all-and-settled': 'ES2020',
  esm: 'ES2015',
  'es6-for-of-iterable': 'ES2015',
  'js-iteration-protocol': 'ES2015',
  'js-generator-yield-pause': 'ES2015',
  'js-async-generator-for-await': 'ES2018',
  'js-weakmap-lifetime': 'ES2015',
  'fetch-response-body-once': 'Fetch Streams',
  'sse-one-way-http-stream': 'HTML SSE',
  // CSS
  'css-flex': 'CSS Flexbox',
  'css-grid-flex': 'CSS Grid',
  'css-container-query': 'CSS CQ',
  'css-has-parent': 'Selectors 4',
  'css-aspect-ratio': 'CSS Sizing 4',
  // Browser / HTML
  'html-dialog-modal': 'HTML dialog',
  'html5-constraint-before-submit': 'HTML5',
  'formdata-multipart-upload': 'HTML5',
  'html5-main-landmark': 'HTML5',
  'html5-media-play-promise': 'HTML5',
  'html5-canvas-buffer': 'HTML5',
  'html5-pushstate-popstate': 'HTML5',
  'html5-dataset-string': 'HTML5',
  'html5-picture-source': 'HTML5',
  'html5-drop-prevent-default': 'HTML5',
  'browser-storage': 'Web Storage',
  'session-storage-tab-only': 'Web Storage',
  'indexeddb-when-needed': 'IndexedDB',
  'service-worker-stale': 'Service Worker',
  'sw-cache-strategy-pick': 'Service Worker',
  'cookie-prefix-partitioned': 'Cookie Prefix/CHIPS',
  'csp-report-only-not-enforce': 'CSP Report-Only',
  'cors-preflight-max-age': 'CORS Max-Age',
  'trusted-types-sink-guard': 'Trusted Types',
  'permissions-policy-feature-gate': 'Permissions-Policy',
  'coop-coep-cross-origin-isolated': 'COOP/COEP',
  'referrer-policy-leak-bound': 'Referrer-Policy',
  'sri-integrity-not-csp': 'SRI',
  'clear-site-data-not-full-logout': 'Clear-Site-Data',
  'reporting-nel-not-csp-enforce': 'Reporting/NEL',
  'corp-embed-gate-not-cors': 'CORP',
  'document-policy-not-permissions-policy': 'Document-Policy',
  'pna-private-network-access': 'Private Network Access',
  'fenced-frame-embed-boundary': 'Fenced Frames',
  'attribution-reporting-not-cookie': 'Attribution Reporting',
  'mysql-invisible-index-not-drop': 'MySQL 8',
  'redis-hello-resp3-not-just-version': 'Redis 6 RESP3',
  'jvm-xmx-not-container-limit': 'JVM ergonomics',
  'cache-db-double-write-race': 'Redis Cache Aside',
  'leaky-bucket-not-no-critical-edge': 'rate limiting',
  'zk-odd-count-not-quorum-law': 'ZooKeeper',
  'mysql-check-enforced-not-parsed-only': 'MySQL 8.0.16',
  'redis-wait-replicas-not-durability': 'Redis WAIT',
  'thread-pool-formula-not-law': 'Java concurrency',
  'rw-split-not-strong-consistency': 'MySQL replication',
  'mysql-window-keeps-rows': 'MySQL 8.0',
  'mysql-cte-named-subquery': 'MySQL 8.0',
  'mysql-temp-table-vs-cte': 'MySQL',
  'mysql-json-not-document-db': 'MySQL JSON',
  'mysql-spatial-index-not-full-gis': 'MySQL SPATIAL',
  'mysql-generated-column-not-where-wrap': 'MySQL 8',
  'redis-geo-on-zset-not-gis': 'Redis GEO',
  'redis-stream-xtrim-bound': 'Redis 5 Stream',
  'redis-keyspace-notify-not-queue': 'Redis Keyspace',
  'redis-client-side-cache-invalidate': 'Redis 6 CSC',
  'redis-functions-not-just-eval': 'Redis 7 Functions',
  'redis-acl-not-just-requirepass': 'Redis 6 ACL',
  'uuid-not-only-random-string': 'RFC 9562',
  'db-autoinc-offset-step-needs-ops': 'MySQL AUTO_INCREMENT',
  'fetch-abort': 'Fetch + AbortController',
  // Java language / APIs (OpenJDK / JLS)
  'java-autoboxing-cache': 'JDK 5',
  'java-generics': 'JDK 5',
  'java-stringbuilder-not-buffer': 'JDK 5',
  'java-enumeration-not-faster': 'JDK 5',
  'java-foreach-remove-cme': 'JDK 5',
  'java-stack-prefer-deque': 'JDK 6',
  'java-finalize-not-guaranteed': 'JDK 7',
  'java-stream': 'JDK 8',
  'java-optional': 'JDK 8',
  'java-default-class-wins-conflict': 'JDK 8',
  'java-time-instant': 'JDK 8',
  'hashmap-treeify-need-capacity': 'JDK 8',
  'chm-jdk8-not-segment-lock': 'JDK 8',
  'chm-iterator-weakly-consistent': 'JDK 8',
  'java-class-newinstance-deprecated': 'JDK 9',
  'java-string-strip-not-trim': 'JDK 11',
  'java-switch-arrow-no-fall': 'JDK 14',
  'java-record-accessor': 'JDK 16',
  'jdk-feature-release-six-months': 'JDK 10+',
  // JVM structure tied to version stories
  'jvm-method-area-metaspace': 'JDK 8',
  'jvm-no-permgen-hotspot': 'JDK 8',
  'jvm-full-gc-not-permgen': 'JDK 8',
  'jvm-platform-classloader-not-ext': 'JDK 9',
  'jvm-gc-choice': 'JDK 9',
  'jvm-cms-removed-g1-default': 'JDK 9/14',
  'jmm-not-eight-memory-ops': 'JDK 5',
  // Concurrency
  'java-happens-before': 'JDK 5',
  'java-synchronized-monitor': 'JDK 15+',
  'java-virtual-threads': 'JDK 21',
  'java-loom-not-absent-coroutine': 'JDK 21',
  // TypeScript
  'ts-satisfies': 'TS 4.9',
  // React
  'react-hooks-over-hoc': 'React 16.8',
  'react-event-root': 'React 17',
  'react-setstate-batch': 'React 18',
  'react-version-checklist': 'React 19',
  'react-rsc-vs-client': 'React 19',
  'react-createclass-gone': 'React 15.5+',
  'react-enzyme-not-default': 'React 19',
  'react-memo-when': 'React 16.6',
  'react-context-stable': 'React 16.3',
  'react-gdsfp-copy': 'React 16.3',
  'react-fiber-interrupt': 'React 16',
  // Vue
  'vue-defineproperty-proxy': 'Vue 3',
  'vue-reactivity': 'Vue 3',
  'vue-composition-options': 'Vue 3',
  'vue-patch-hoist': 'Vue 3',
  'vue-tree-shake-faster': 'Vue 3',
  'vue-modal-programmatic': 'Vue 3',
  'vue-design-goals-proxy': 'Vue 3',
  'pinia-not-vuex': 'Vue 3 / Pinia',
  'pinia-store-to-refs': 'Pinia',
  'fe-sveltekit-runes': 'Svelte 5',
  // Node / network
  'node-global-fetch': 'Node 18',
  'node-unhandled-rejection': 'Node 15',
  'fetch-platform-client': 'Node 18+',
  'http2-multiplex': 'HTTP/2',
  'http-patch-rfc5789': 'RFC 5789',
  // Spring / MyBatis
  'spring-boot3-autoconfig-imports': 'Spring Boot 3',
  'spring-xmlbeanfactory-removed': 'Spring 5',
  'retired-spring-cloud-netflix': 'Boot 3 / SC 2020+',
  'mybatis-plus-page-argument': 'Boot 3 starter',
  // Data / MQ
  'mysql-query-cache-removal': 'MySQL 8.0',
  'mysql-innodb-fulltext': 'MySQL 5.6+',
  'mysql-datetime-vs-timestamp': 'MySQL 5.6.4+',
  'mysql-binlog-format': 'MySQL 8.0+',
  'redis-cluster-cli-not-trib': 'Redis 5',
  'redis-aof-keeps-rdb': 'Redis 4+',
  'kafka-kraft-not-zk': 'Kafka KRaft',
  // Cross-end tooling versions called out in titles
  'taro-4-compiler-choice': 'Taro 4',
  'taro-react-setdata-bridge': 'Taro 3+',
  'taro-pages-in-app-config': 'Taro 3+',
  'uniapp-onload-vs-onshow': 'uni-app',
  'rn-jsi-not-json-bridge': 'RN 0.76+',
  'flutter-impeller-own-pixels': 'Flutter 3.27+',
  // TypeScript / React / Vue follow-ups
  'ts-module-resolution': 'TS 5.0 bundler',
  'react-flow-not-default': 'react.dev + TS',
  'react-error-boundary': 'React 16',
  'react-router-loader': 'RR 6.4+',
  'rr-mode-gates-data': 'RR 6.4+',
  'vue-vnode-not-fragment': 'Vue 3',
  // Network / RFC baselines taught in the lesson
  'api-error-contract': 'RFC 9457',
  'https-tls13-not-12-packets': 'TLS 1.3',
  'http-connection-reuse': 'HTTP/1.1+',
  'jwt-payload-not-encrypted': 'RFC 7519',
  'distributed-unique-id': 'RFC 9562',
  // JVM / concurrency / misc
  'cpu-cache-line-sharing': 'JEP 142',
  'hash-open-addressing-probe': 'JDK 8 HashMap',
  'jvm-tenuring-threshold-15': 'HotSpot ≤15',
  'jvm-pc-no-oom': 'JDK 8+',
  // Java HTTP / Boot ops
  'java-http-timeout': 'Java 11 HttpClient',
  'spring-graceful-shutdown': 'Spring Boot 2.3+',
  'mybatis-jdbc-log-inlines': 'Spring Boot 3',
  'mybatis-pagehelper-next-query': 'PageHelper 6',
  // MySQL handbook baseline used in cores (current answer track)
  'mysql-union-distinct': 'MySQL 8.4',
  'mysql-varchar-length': 'MySQL 8.4',
  'mysql-varchar-row-max': 'MySQL 8.4',
  'mysql-myisam-innodb': 'MySQL 8.4',
  'mysql-innodb-tablespace': 'MySQL 8.4',
  'mysql-prepared-statement': 'MySQL 8.4',
  'mysql-buffer-pool-size': 'MySQL 8.4',
  'mysql-covering-not-index-kind': 'MySQL 8+',
  'mysql-autoinc-persists-8': 'MySQL 8.0',
  'mysql-initialize-not-install-db': 'MySQL 8.0+',
  // More frameworks / middleware with a clear version boundary
  'http-503-unavailable': 'RFC 9110',
  'spring-legacy-config': 'Spring 5.3 docs',
  'spring-boot-aop-cglib-default': 'Spring Boot',
  'tomcat-nio-not-bio-default': 'Tomcat 8.5+',
  'jdbc-datasource-not-diy-pool': 'JDBC 2.0',
  'java-reentrant-lock': 'JDK 5',
  'java-concurrent-map': 'JDK 8 compute*',
  'java-fork-join-pool': 'JDK 7',
  'java-executors-factory-oom': 'JDK 5 Executors',
  'redis-stream-vs-pubsub': 'Redis 5 Stream',
  'redis-list-quicklist-listpack': 'Redis 3.2/7',
  'redis-hyperloglog-approx': 'Redis 2.8+',
  'mongo-multi-doc-txn': 'MongoDB 4.0',
  'nginx-load-module': 'Nginx 1.9.11+',
  'dubbo-hessian-zk-not-frozen': 'Dubbo 3.x',
  'eureka-lease-30-90': 'Eureka defaults',
  'kafka-partitions-increase-only': 'Kafka partitions',
  'spring-mvc-restcontroller': 'Spring 4',
  'vite-module-graph': 'Vite',
  'vite-env-client-prefix': 'Vite',
  'build-code-splitting': 'ES2020',
  'retired-frontend-stack': 'CRA sunset',
  'uniapp-ifdef-stripped': 'uni-app',
  'long-poll-vs-websocket': 'RFC 6455',
  'cookie-set-attributes': 'Cookie SameSite',
  'http-range': 'RFC 9110 Range',
  'gateway-websocket-upgrade': 'RFC 6455',
  // Concurrency / futures
  'java-future-errors': 'JDK 8',
  'java-barrier-latch': 'JDK 5',
  'java-aqs-not-futuretask': 'JDK 5 AQS',
  'java-dcl-volatile-enum': 'JDK 5',
  // React / data / Angular
  suspense: 'React 16+',
  effects: 'React 16.8',
  'react-effect-timing': 'React 16.8',
  'fetch-method-body-timeout': 'AbortSignal.timeout',
  'query-server-state': 'TanStack Query',
  'redux-rtk-today': 'Redux Toolkit',
  'fe-angular-first-party': 'Angular v21',
  'fe-angular-resource-not-ngrx': 'Angular v21',
  'angular-ngonchanges-primitives': 'Angular v21',
  // Build / RN / Nuxt / Vite
  'client-env-public': 'Vite env',
  'vite-sourcemap-prod': 'Vite',
  'rn-hermes-default': 'RN Hermes',
  'nuxt-payload': 'Nuxt 3',
  'uniapp-pages-json-entry': 'uni-app',
  // Spring / data stores
  'spring-boot-war-still-ok': 'Spring Boot',
  'spring-test-slice': 'Spring Boot Test',
  'jpa-modifying-clear': 'Spring Data JPA',
  'mybatis-lazy-javassist-not-cglib': 'MyBatis 3',
  'junit-instance-lifecycle': 'JUnit 5',
  'mysql-replica-parallel-applier': 'MySQL 8.0+',
  'kafka-isr-lag-time-not-count': 'Kafka lag.time',
  'redis-legacy-vm-limits': 'Redis no VM',
  'redis-cluster-incr-not-five-steps': 'Redis Cluster',
  'es-search-after': 'ES search_after',
  'es-refresh-visibility': 'ES near-realtime',
  'sca-nacos-shared-config': 'Nacos',
  'sca-nacos-intro': 'Nacos',
  'netty-event-loop': 'Netty',
  'activemq-jms-model': 'JMS / ActiveMQ',
  'activemq-prefetch-limit': 'ActiveMQ',
  'activemq-queue-competing-consumers': 'JMS Queue',
  'pulsar-segment-model': 'Pulsar',
  'kafka-model': 'Kafka',
  'rabbit-model': 'AMQP / RabbitMQ',
  'rocketmq-model': 'RocketMQ',
  'rocketmq-send-oneway-may-drop': 'RocketMQ',
  // Vue / RN / SCA
  'fe-vue-official-slots': 'Vue 3 / create-vue',
  'fe-vue-data-one-slot': 'Vue / Nuxt / Pinia',
  'fe-ecosystem-follows-model': 'framework slots',
  'fe-server-state-one-owner': 'one cache owner',
  'vue-nexttick': 'Vue',
  'vue-list-key': 'Vue',
  'vue-props-one-way': 'Vue',
  'rn-fetch-not-document': 'RN JS env',
  'sca-what': 'SCA',
  'sca-circuit-not-only-hystrix': 'SC CircuitBreaker',
  'sca-stream-binding': 'SC Stream',
  'config-center-poll-needs-watch': 'config watch',
  // Concurrency / Spring / data
  'java-lock-flexibility': 'JDK 5 Lock',
  'java-rwlock-no-upgrade': 'JDK 5 RWLock',
  'java-cas-aba-stamp': 'JDK 5 Atomic*',
  'java-tpe-execute-order': 'JDK 5 TPE',
  'spring-transaction': 'Spring AOP TX',
  'spring-propagation': 'Spring TX',
  'spring-rollback': 'Spring TX',
  'spring-scopes': 'Spring',
  'spring-bean-lifecycle': 'Spring',
  'spring-ioc-wiring': 'Spring',
  'spring-validation-binding': 'Bean Validation',
  'jpa-entity-identity': 'JPA',
  'jpa-flush-transaction': 'JPA',
  'mybatis-second-cache': 'MyBatis',
  'mybatis-batch-executor': 'MyBatis',
  'dubbo-timeout-retry-idempotent': 'Dubbo',
  'dubbo-loadbalance-random-default': 'Dubbo',
  // Search / Redis / TS / test / Node
  'es-lucene-not-btree': 'Lucene / ES',
  'es-inverted-index': 'inverted index',
  'es-aggregations': 'ES aggs',
  'es-term-lookup-not-o1': 'Lucene postings',
  'redis-lua-atomic': 'Redis EVAL',
  'redis-pipeline': 'Redis Pipeline',
  'redis-transaction': 'Redis MULTI',
  'ts-unknown': 'TS 3.0',
  'ts-template-literal-types': 'TS 4.1',
  'ts-utility-types': 'TypeScript',
  'linked-list': 'React Hooks',
  'state-queue': 'React 18 batch',
  'playwright-user-journey': 'Playwright',
  'msw-http-mock': 'MSW',
  'testing-library-role': 'Testing Library',
  'node-stream': 'Node Stream',
  'node-buffer': 'Node Buffer',
  'node-worker-cluster': 'Node cluster/worker',
  'web-vitals': 'CWV / INP',
  'schema-migration': 'Flyway-style',
  'jvm-major-gc-not-always-full': 'HotSpot GC',
  'nginx-limit-req': 'Nginx limit_req',
  'nginx-upstream-passive': 'Nginx upstream',
  'netty-pipeline-handler': 'Netty Pipeline',
  // Restored full-coverage baselines (546)
  accessibility: "frontend eng",
  "ajax-page-update-not-a-library": "HTTP",
  "algo-hash-lookup": "algorithms",
  "algo-sliding-window": "algorithms",
  "algo-stable-sort": "algorithms",
  "algo-topo-kahn": "algorithms",
  "algo-tree-walk": "algorithms",
  "algo-two-pointers": "algorithms",
  "arch-design-one-path": "system design",
  "arch-evolution-stages": "system design",
  "arch-microservice-split": "system design",
  "arch-modular-boundary": "system design",
  "arch-monolith-when": "system design",
  "arch-queue-wait": "system design",
  "arch-scale-before-split": "system design",
  "arch-slo-budget": "system design",
  "arch-split-order-case": "system design",
  "arch-sync-vs-async": "system design",
  "auth-session-vs-jwt": "session / JWT",
  "axios-rejects-http-errors": "HTTP",
  "axios-shared-instance": "HTTP",
  "backend-tune-the-span": "engineering",
  "base-slogan-not-ban-tx": "distributed",
  "bfcache-pageshow": "bfcache",
  bfs: "algorithms",
  "browser-event-loop-frame": "browser",
  "build-cache": "frontend eng",
  "business-split-db-not-only-path": "MySQL 8.4",
  cache: "system design",
  "cache-aside-steps": "Redis",
  "cache-local-vs-distributed": "Redis",
  "cache-penetration-vs-breakdown": "Redis",
  "cap-label-not-product-tattoo": "distributed",
  "cdn-not-just-reverse-proxy-cache": "Nginx",
  "ci-gate-not-only-build": "frontend eng",
  closure: "JavaScript",
  complexity: "algorithms",
  "compose-service-name-dns": "ops",
  "container-shares-host-kernel": "ops",
  context: "React",
  "contract-test-path": "frontend test",
  "controlled-input": "React",
  "cookie-credential": "Cookie",
  cors: "CORS",
  "cors-credentials-allowlist": "CORS",
  "cpu-heap-not-cpu-cache": "engineering",
  "cross-four-where-it-fits": "cross-end",
  "cross-four-who-paints": "cross-end",
  "csp-script-src": "CSP",
  "csrf-boundary": "CSRF",
  "css-box-sizing": "CSS",
  "css-cascade": "CSS",
  "css-containing-block": "CSS",
  "css-position-flow": "CSS",
  "css-stacking": "CSS",
  "db-insert-unique-cron-not-lease": "MySQL 8.4",
  "db-proxy-layer-not-only-choice": "MySQL 8.4",
  "db-sequence-batch-not-gapless": "distributed",
  "ddd-aggregate-transaction-boundary": "system design",
  "ddd-entity-or-value": "system design",
  "ddd-repository-one-entry": "system design",
  "ddd-same-word-two-contexts": "system design",
  "design-review": "interview frame",
  "dist-lock-owner-not-mac-pid-tid": "distributed",
  "dist-lock-reentrant-not-deadlock-cure": "distributed",
  "distributed-at-sees-before-global": "Seata",
  "distributed-bloom": "distributed",
  "distributed-bulkhead": "distributed",
  "distributed-cache": "distributed",
  "distributed-cap": "distributed",
  "distributed-clock-skew": "distributed",
  "distributed-consistency-three-words": "distributed",
  "distributed-consistent-hash": "distributed",
  "distributed-idempotent-key": "distributed",
  "distributed-kafka-order": "distributed",
  "distributed-lock": "distributed",
  "distributed-mq-not-erase-invariant": "distributed",
  "distributed-one-db-first": "distributed",
  "distributed-outbox": "distributed",
  "distributed-read-your-writes": "distributed",
  "distributed-reconcile-last": "distributed",
  "distributed-saga-is-new-action": "Seata",
  "distributed-saga-who-drives": "Seata",
  "distributed-seckill": "distributed",
  "distributed-token-bucket": "distributed",
  "distributed-tx-not-cover-rpc": "distributed",
  "distributed-xa": "distributed",
  "distributed-xid-must-travel": "Seata",
  "dns-lb-not-just-round-robin": "distributed",
  "docker-image-template-not-container": "ops",
  "docker-layer-cache-copy": "ops",
  "docker-multistage": "engineering",
  "docker-registry-not-just-repo-bucket": "ops",
  "docker-root-not-host-root": "engineering",
  "dom-event-flow": "browser",
  "dubbo-registry-down-local-cache": "Dubbo",
  "elastic-analysis": "Elasticsearch",
  "epoll-et-must-drain": "Netty",
  "es-custom-routing": "Elasticsearch",
  "es-filter-context": "Elasticsearch",
  "es-mapping-reindex": "Elasticsearch",
  "etcd-v3-grpc-not-rest": "engineering",
  "event-system": "React",
  eventloop: "JavaScript",
  "fe-cross-end-one-runtime": "framework pick",
  "fe-expo-router-one-nav": "Expo Router",
  "fe-flutter-state-one-approach": "Flutter",
  "fe-pick-by-surface": "framework pick",
  "fe-react-framework-first": "react.dev",
  "fe-react-one-slot": "framework pick",
  "fe-slow-page-where": "framework pick",
  "fe-svelte-load-not-store": "SvelteKit",
  "fe-tune-one-layer": "framework pick",
  "fe-ui-update-model": "framework models",
  "fetch-credentials": "Fetch credentials",
  "flutter-constraints-down": "Flutter",
  "flutter-gorouter-not-named": "Flutter",
  "flutter-setstate-rebuilds": "Flutter",
  "flutter-widget-not-html": "Flutter",
  "frontend-testing": "frontend test",
  "fs-boot-chain": "path",
  "fs-four-layers": "path",
  "fs-frontend-done": "path",
  "fs-page-feature": "path",
  "fs-read-shape": "path",
  "fs-ship-bar": "path",
  "fs-write-invariant": "path",
  "fs-write-ui": "path",
  "gateway-auth-where": "gateway",
  "gateway-body-buffer": "gateway",
  "gateway-one-hop": "gateway",
  "gateway-retry-idempotent": "gateway",
  "gateway-route-predicate": "gateway",
  "gateway-timeout-chain": "gateway",
  "gha-artifact-between-jobs": "ops",
  "gha-job-needs-success": "ops",
  "gha-workflow-in-dot-github": "ops",
  "git-default-branch-not-master": "engineering",
  "git-restore-over-checkout": "engineering",
  "consistent-hash-vnode-count-not-law": "distributed",
  "hash-skew-not-only-virtual-nodes": "distributed",
  "hashmap-initial-16-not-max": "Java",
  "hikari-pool-timeout": "HikariCP",
  "hot-cold-ratio-not-fixed-one-to-four": "MySQL 8.4",
  "html-form-cross-origin-navigate": "HTML forms",
  "html-form-semantics": "HTML5",
  "http-cache": "HTTP caching",
  "http-compression": "HTTP",
  "http-content-type-body": "HTTP",
  "http-create-post-not-put": "HTTP",
  "http-methods": "HTTP",
  "http-redirect-lb-two-hops": "HTTP",
  "http-status-auth": "HTTP",
  "https-port-443-not-80": "HTTP",
  idempotency: "system design",
  identity: "React",
  "image-loading": "browser",
  "java-anonymous-extends-or-implements": "Java",
  "java-arraylist-linkedlist": "Java",
  "java-arrays-aslist-fixed": "Java",
  "java-binary-search": "Java",
  "java-buffered-stream-decorator": "Java",
  "java-calendar-not-singleton": "Java",
  "java-charset-default": "Java",
  "java-classloading": "JVM",
  "java-clone-exception-checked": "Java",
  "java-collection-vs-collections": "Java",
  "java-collections": "Java",
  "java-comparator-strategy": "Java",
  "java-concurrency": "JDK concurrency",
  "java-ctor-implicit-super-noarg": "Java",
  "java-equals-contract": "Java",
  "java-exceptions": "Java",
  "java-executor": "JDK concurrency",
  "java-final-not-fifty-percent": "Java",
  "java-gc": "JVM",
  "java-heap-not-cpp-manual": "JVM",
  "java-interface-contract": "Java",
  "java-interrupt": "JDK concurrency",
  "java-linked-blocking-unbounded": "JDK concurrency",
  "java-long-atomic-on-64bit": "Java",
  "java-main-launcher": "Java",
  "java-memory": "JVM",
  "java-not-every-class-clone-serializable": "Java",
  "java-pass-by-value": "Java",
  "java-pattern-dot-not-nl": "Java",
  "java-polymorphism-not-only-extends": "Java",
  "java-priority-queue": "Java",
  "java-protected-other-pkg-subclass": "Java",
  "java-proxy-needs-interface": "Java",
  "java-raw-type-skips-checks": "Java",
  "java-runnable-is-command": "Java",
  "java-runtime-ex-not-auto-caught": "Java",
  "java-set-not-always-sorted": "Java",
  "java-shift-not-times-eight": "Java",
  "java-soft-ref-not-oom-proof": "JVM",
  "java-string-immutability": "Java",
  "java-string-new-vs-pool": "Java",
  "java-sync-not-all-methods": "JDK concurrency",
  "java-thread-local-leak": "JDK concurrency",
  "java-thread-six-states": "JDK concurrency",
  "java-thread-start-run": "Java threads",
  "java-threads-not-linear-speedup": "JDK concurrency",
  "java-unchecked-not-must-catch": "Java",
  "java-unmodifiable-is-view": "Java",
  "java-vector-cme-not-because-sync": "Java",
  "java-wait-sleep": "JDK concurrency",
  "jenkins-not-only-ci-tool": "ops",
  "jpa-cascade-orphan": "JPA",
  "jpa-dirty-check": "JPA",
  "jpa-entity-graph": "JPA",
  "jpa-optimistic-lock": "JPA",
  "jpa-osiv-boundary": "JPA",
  "jpa-page-vs-slice": "JPA",
  "jpa-session-nplus1": "JPA",
  "js-json-stringify-not-equal": "JavaScript",
  "js-microtask-vs-macrotask": "JavaScript",
  "js-not-everything-object": "JavaScript",
  "js-regex-dot-not-newline": "JavaScript",
  "js-this-callsite": "JavaScript",
  "js-timer-fn-not-string": "JavaScript",
  "jvm-areas": "JVM",
  "jvm-jit-tiered": "JVM",
  "jvm-jmm-not-runtime-areas": "JVM",
  "jvm-oom-signals": "JVM",
  "jvm-safepoint": "JVM",
  "jvm-thread-vs-heap-dump": "JVM",
  "k8s-deploy-not-lone-pod": "ops",
  "k8s-ingress-needs-controller": "ops",
  "k8s-memory-limit": "engineering",
  "k8s-pod-share-localhost": "ops",
  "k8s-probes": "engineering",
  "k8s-runtime-not-only-docker": "engineering",
  "k8s-service-clusterip": "ops",
  "kafka-isr-hwm": "Kafka",
  "kafka-offset": "Kafka",
  "kafka-producer-acks": "Kafka",
  "kafka-producer-does-batch": "Kafka",
  "kafka-rebalance": "Kafka",
  "kubeadm-cni-before-coredns": "ops",
  "kubeadm-control-plane-taint": "ops",
  layout: "browser",
  "linux-bkl-gone": "engineering",
  "linux-fork-copies-one-thread": "engineering",
  "linux-root-group-not-root": "engineering",
  "log-correlation-id": "correlation id",
  "leaky-bucket-not-no-critical-edge": "distributed",
  "lru-capacity-not-ttl-expire": "distributed",
  "lru-needs-hash-and-list": "Redis",
  "message-delivery": "system design",
  "message-order-not-always-required": "distributed",
  "mfe-compare-matrix": "micro-frontend",
  "mfe-composition-models": "micro-frontend",
  "mfe-contract-version": "micro-frontend",
  "mfe-iframe-postmessage": "iframe",
  "mfe-independent-deploy": "micro-frontend",
  "mfe-mf-host-setup": "micro-frontend",
  "mfe-module-federation": "micro-frontend",
  "mfe-not-for-everything": "micro-frontend",
  "mfe-perf-cost": "micro-frontend",
  "mfe-pick-by-constraint": "micro-frontend",
  "mfe-pick-one-path": "micro-frontend",
  "mfe-qiankun-html-entry": "qiankun",
  "mfe-routing-one-history": "micro-frontend",
  "mfe-runtime-lifecycle": "micro-frontend",
  "mfe-shared-auth": "micro-frontend",
  "mfe-shared-deps": "micro-frontend",
  "mfe-singlespa-register": "single-spa",
  "mfe-style-isolation": "micro-frontend",
  "mfe-vite-federation": "micro-frontend",
  "mfe-when-to-split": "micro-frontend",
  "mfe-wujie-startapp": "无界",
  "microservices-not-just-soa-relabel": "distributed",
  "miniprogram-wx-if-not-wxif": "browser",
  "mongo-bson-use-lazy": "MySQL 8.4",
  "mq-backlog-expand-queues": "messaging",
  "mq-backpressure-producer": "messaging",
  "mq-compare-matrix": "messaging",
  "mq-consume-idempotent-key": "messaging",
  "mq-delete-not-always-idempotent": "messaging",
  "mq-delivery-semantics": "messaging",
  "mq-dlq-backlog": "messaging",
  "mq-pick-workload": "messaging",
  "mq-why-decouple": "messaging",
  "mw-proxy-lb-gateway": "gateway",
  "mybatis-debug-boundsql": "MyBatis",
  "mybatis-dynamic-sql": "MyBatis",
  "mybatis-local-cache": "MyBatis",
  "mybatis-log-preparing-parameters": "MyBatis",
  "mybatis-mapper-bound": "MyBatis",
  "mybatis-middleware-layers": "MyBatis",
  "mybatis-parameters": "MyBatis",
  "mybatis-plugin-interceptor": "MyBatis",
  "mybatis-resultmap": "MyBatis",
  "mybatis-rowbounds-memory": "MyBatis",
  "mybatis-type-handler": "MyBatis",
  "mysql-acid-c-is-consistency": "MySQL 8.4",
  "mysql-and-order-optimizer-reorders": "MySQL 8.4",
  "mysql-catch-sql-exception-not-enough": "MySQL 8.4",
  "mysql-column-count-thirty-not-law": "MySQL 8.4",
  "mysql-composite-selectivity-order-heuristic": "MySQL 8.4",
  "mysql-count-star-innodb-not-always-scan": "MySQL 8.4",
  "mysql-db-features-ban-not-absolute": "MySQL 8.4",
  "mysql-db-not-blob-store": "MySQL 8.4",
  "mysql-ddl-merge-heuristic": "MySQL 8.4",
  "mysql-deadlock": "MySQL 8.4",
  "mysql-enum-ban-not-absolute": "MySQL 8.4",
  "mysql-explain-analyze": "MySQL 8.4",
  "mysql-extend-index-before-new": "MySQL 8.4",
  "mysql-fk-ban-not-absolute": "MySQL 8.4",
  "mysql-fk-redundancy": "MySQL 8.4",
  "mysql-float-ieee-not-8-digits": "MySQL 8.4",
  "mysql-for-update-not-dist-lease": "MySQL 8.4",
  "mysql-group-by-having": "MySQL 8.4",
  "mysql-implicit-convert-breaks-index": "MySQL 8.4",
  "mysql-index": "MySQL 8.4",
  "mysql-index-count-five-not-law": "MySQL 8.4",
  "mysql-index-kinds": "MySQL 8.4",
  "mysql-inner-join-match": "MySQL 8.4",
  "mysql-innodb-default-not-ban-others": "MySQL 8.4",
  "mysql-innodb-index-lock": "MySQL 8.4",
  "mysql-innodb-no-user-hash": "MySQL 8.4",
  "mysql-insert-must-name-columns": "MySQL 8.4",
  "mysql-instance-table-count-not-500": "MySQL 8.4",
  "mysql-isolation": "MySQL 8.4",
  "mysql-isolation-levels": "MySQL 8.4",
  "mysql-join-ban-not-absolute": "MySQL 8.4",
  "mysql-leading-percent-like-heuristic": "MySQL 8.4",
  "mysql-low-selectivity-index-heuristic": "MySQL 8.4",
  "mysql-money-decimal-not-ban": "MySQL 8.4",
  "mysql-mvcc": "MySQL 8.4",
  "mysql-mvcc-not-two-version-columns": "MySQL 8.4",
  "mysql-negative-predicate-not-always-scan": "MySQL 8.4",
  "mysql-not-null-default-not-absolute": "MySQL 8.4",
  "mysql-null-comparison": "MySQL 8.4",
  "mysql-or-not-must-become-in": "MySQL 8.4",
  "mysql-phone-varchar-length-not-twenty": "MySQL 8.4",
  "mysql-pk-autoinc-not-only-choice": "MySQL 8.4",
  "mysql-prefix-index-and-cost": "MySQL 8.4",
  "mysql-procedure-not-auto-txn": "MySQL 8.4",
  "mysql-pt-checksum-pk": "MySQL 8.4",
  "mysql-redo-undo-binlog": "MySQL 8.4",
  "mysql-replica-lag": "MySQL 8.4",
  "mysql-replication-flow": "MySQL 8.4",
  "mysql-right-fuzzy-like-can-use-index": "MySQL 8.4",
  "mysql-scalability-not-hopeless": "MySQL 8.4",
  "mysql-second-nf": "MySQL 8.4",
  "mysql-select-star": "MySQL 8.4",
  "mysql-slow-sql-locate": "MySQL 8.4",
  "mysql-slow-sql-optimize": "MySQL 8.4",
  "mysql-split-not-at-ten-million": "MySQL 8.4",
  "mysql-subquery-ban-not-absolute": "MySQL 8.4",
  "mysql-text-ban-not-absolute": "MySQL 8.4",
  "mysql-trigger-side-effect-hidden": "MySQL 8.4",
  "mysql-unique-change-buffer": "MySQL 8.4",
  "mysql-upsert": "MySQL 8.4",
  "mysql-utf8-alias-not-utf8mb4": "MySQL 8.4",
  "mysql-uuid-not-clustered-pk": "MySQL 8.4",
  "mysql-view-is-stored-query": "MySQL 8.4",
  "mysql-where-func-blocks-index": "MySQL 8.4",
  "mysql-where-having": "MySQL 8.4",
  "mysql-wide-column-split": "MySQL 8.4",
  "netty-bytebuf-leak": "Netty",
  "netty-codec-shareable": "Netty",
  "netty-file-region": "Netty",
  "netty-idle-heartbeat": "Netty",
  "netty-length-field-frame": "Netty",
  "netty-watermark-backpressure": "Netty",
  "nginx-buffer-body": "Nginx",
  "nginx-forward-not-direct": "Nginx",
  "nginx-gunzip-not-compress": "Nginx",
  "nginx-ip-hash-session": "Nginx",
  "nginx-limit-req-not-iptables-loop": "Nginx",
  "nginx-proxy-host": "Nginx",
  "nginx-proxy-timeout": "Nginx",
  "nginx-request-phases": "Nginx",
  "nginx-static-cache-headers": "Nginx",
  "nio-not-one-thread-per-request": "Netty",
  "node-emitter": "Node.js",
  "node-event-loop-phases": "Node.js",
  "node-http-close": "Node.js",
  "node-http-cookie": "Node.js",
  "node-libuv-threadpool": "Node.js",
  "node-nexttick": "Node.js",
  "nosql-label-not-eventual": "MySQL 8.4",
  "object-level-authz": "authz",
  "one-container-one-service-heuristic": "ops",
  "otel-three-signals": "OpenTelemetry",
  "password-adaptive-hash": "password hashing",
  "pattern-adapter-shape": "GoF",
  "pattern-bridge-two-axes": "GoF",
  "pattern-builder-assemble": "GoF",
  "pattern-chain-stop": "GoF",
  "pattern-composite-tree": "GoF",
  "pattern-decorator-contract": "GoF",
  "pattern-facade-entry": "GoF",
  "pattern-factory-method": "GoF",
  "pattern-family-test": "GoF",
  "pattern-flyweight-share": "GoF",
  "pattern-gof-catalog": "GoF",
  "pattern-gof-rest": "GoF",
  "pattern-observer-push": "GoF",
  "pattern-one-variation": "GoF",
  "pattern-proxy-stand-in": "GoF",
  "pattern-singleton-scope": "GoF",
  "pattern-state-transition": "GoF",
  "pattern-strategy-swap": "GoF",
  "pattern-template-steps": "GoF",
  performance: "frontend eng",
  "query-cache-not-http-client": "TanStack Query",
  "query-fn-calls-the-client": "TanStack Query",
  "query-invalidate": "TanStack Query",
  "quicksort-average-nlogn": "algorithms",
  "rabbit-ack": "AMQP / RabbitMQ",
  "rabbit-exchange-binding": "AMQP / RabbitMQ",
  "rabbit-ha-queue": "AMQP / RabbitMQ",
  "rabbit-queue-not-unbounded": "AMQP / RabbitMQ",
  "rate-limit": "system design",
  "react-props-state-sync": "React",
  "react-router-element-api": "RR 6",
  "react-router-error-element": "RR 6",
  "react-ssr-not-fewer-http": "React",
  "react-vdom-perf-bound": "React",
  "redis-big-hot-key": "Redis",
  "redis-data-types": "Redis",
  "redis-eviction-policy-menu": "Redis",
  "redis-expire": "Redis",
  "redis-fifo-not-maxmemory": "Redis",
  "redis-hash-field-update": "Redis",
  "redis-lock-getset-wall-clock": "Redis",
  "redis-lock-setnx-expire-race": "Redis",
  "redis-multi-vs-lua-pick": "Redis",
  "redis-persistence": "Redis",
  "redis-proxy-hash-not-cluster": "Redis",
  "redis-pubsub-not-reliable-queue": "Redis",
  "redis-pubsub-pattern-subscribe": "Redis",
  "redis-repl-psync-not-sql": "Redis",
  "redis-save-blocks-bgsave": "Redis",
  "redis-sentinel-cluster": "Redis",
  "redis-single-thread": "Redis",
  "redis-string-max-512mb": "Redis",
  "redis-zset-rank-range": "Redis",
  rendering: "browser",
  "request-trace-one-hop": "OpenTelemetry",
  "rn-dimensions-not-cached": "React Native",
  "rn-flatlist-window": "React Native",
  "rn-flex-defaults": "React Native",
  "rn-image-needs-size": "React Native",
  "rn-navigate-not-push": "React Native",
  "rn-platform-extension": "React Native",
  "rn-pressable-not-click": "React Native",
  "rn-text-not-under-view": "React Native",
  "rn-view-not-div": "React Native",
  "rocketmq-flush-ha": "RocketMQ",
  "rocketmq-queue-order": "RocketMQ",
  "rocketmq-store-not-ram-buffer": "RocketMQ",
  "rr-outlet-keeps-layout": "RR 6",
  "rr-redirect-before-render": "RR 6",
  "runtime-config": "security",
  "same-origin-script-still-runs": "same-origin",
  "sca-component-map": "SCA",
  "sca-deregister-shutdown": "SCA",
  "sca-dubbo-or-feign": "Dubbo",
  "sca-feign-timeout-retry": "Dubbo",
  "sca-nacos-config": "Nacos",
  "sca-nacos-ephemeral": "Nacos",
  "sca-nacos-register": "Nacos",
  "sca-one-call": "SCA",
  "sca-oss-intro": "SCA",
  "sca-rocketmq-intro": "SCA",
  "sca-schedulerx-intro": "SCA",
  "sca-seata-at-boundary": "Seata",
  "sca-seata-intro": "Seata",
  "sca-seata-lock-timeout": "Seata",
  "sca-seata-tcc-empty": "Seata",
  "sca-sentinel-block": "Sentinel",
  "sca-sentinel-block-fallback": "Sentinel",
  "sca-sentinel-circuit-state": "Sentinel",
  "sca-sentinel-flow-mode": "Sentinel",
  "sca-sentinel-intro": "Sentinel",
  "sca-sms-intro": "SCA",
  "seckill-client-gate-not-enough": "distributed",
  "seckill-mq-not-only-db-valve": "distributed",
  "seckill-js-needs-cache-control": "distributed",
  "secrets-not-in-image": "engineering",
  "select-not-always-business-idempotent": "distributed",
  "server-slow-which-resource": "engineering",
  "service-extract-not-only-connection-math": "distributed",
  "snowflake-params-need-capacity-math": "distributed",
  "split-vs-cluster-not-interchangeable": "distributed",
  "spring-aop-proxy-type": "Spring",
  "spring-aop-self-invocation": "Spring",
  "spring-authn-authz": "Spring Security",
  "spring-boot-devtools-restarts": "Spring",
  "spring-cloud-feign-not-lb": "Spring",
  "spring-csrf-spa": "Spring Security",
  "spring-dirties-context": "Spring",
  "spring-event-sync-default": "Spring",
  "spring-external-config": "Spring",
  "spring-factorybean-product": "Spring",
  "spring-filter-vs-interceptor": "Spring",
  "spring-getbean-hides-deps": "Spring",
  "spring-jdbctemplate-callback": "Spring",
  "spring-mvc-controller-singleton": "Spring",
  "spring-mvc-dispatch": "Spring",
  "spring-mvc-exception": "Spring",
  "spring-oauth2-resource": "Spring Security OAuth2",
  "spring-scope-catalog": "Spring",
  "spring-security-cors": "Spring",
  "spring-security-filter-chain": "Spring Security",
  "spring-session-stateless": "Spring",
  "spring-test-transaction-rollback": "Spring",
  "sql-keyset-page": "MySQL 8.4",
  "sql-outer-join-where": "MySQL 8.4",
  "sshd-rate-limit-not-lastb": "sshd",
  "ssr-hydration": "frontend eng",
  "state-kind-picks-home": "React",
  "state-reducer-context-screen": "React",
  "sync-replication-not-only-durability": "distributed",
  "table-constraint-holds-rule": "MySQL 8.4",
  "table-design-from-facts": "MySQL 8.4",
  "table-row-one-grain": "MySQL 8.4",
  "taro-and-uniapp-layers": "Taro",
  "tcp-is-l4-not-http-handshake": "HTTP",
  "tcp-reliable-not-never-lose": "HTTP",
  "tcp-stream-needs-framing": "HTTP",
  "test-fake-timers": "frontend test",
  "test-mock-boundary": "frontend test",
  "test-observable-result": "frontend test",
  "test-one-behavior": "frontend test",
  "testcontainers-real-db": "Testcontainers",
  "tls-hostname-verify": "HTTP",
  "ts-const-readonly": "TypeScript",
  "ts-generics": "TypeScript",
  "ts-narrowing": "TypeScript",
  "ts-structural": "TypeScript",
  "ts-type-vs-interface": "TypeScript",
  "uniapp-x-uts-not-vue-page": "uni-app",
  "vm-vs-container-isolation-tradeoff": "ops",
  "vue-array-raw-proxy": "Vue",
  "vue-computed-watch": "Vue",
  "vue-keep-alive": "Vue",
  "vue-proxy-null-guard": "Vue",
  "vue-router-guard": "Vue",
  "vue-router-reuse": "Vue",
  "vue-router-scroll": "Vue",
  "vue-tree-shake-options": "Vue",
  "webpack-eval-sourcemap-dev-only": "Webpack",
  xss: "XSS",
  "zabbix-active-at-scale": "engineering",
  "zk-linearizable-not-realtime": "distributed",
  "zk-odd-count-not-quorum-law": "ZooKeeper",
};

export function validateLessons(lessons, groupOrder = GROUP_ORDER) {
  assert(Array.isArray(lessons) && lessons.length > 0, 'No published lessons');
  assert.equal(new Set(lessons.map(x => x.id)).size, lessons.length, 'Duplicate lesson ID');
  const allowed = new Set(['track','group','id','title','prompt','promptAnswer','core','why','example','task','answer','keywords','points','references','deep','map','diagram','origin','react','vue','since']);
  for (const lesson of lessons) {
    for (const key of Object.keys(lesson)) assert(allowed.has(key), `${lesson.id}: unexpected field ${key}`);
    for (const key of ['track','group','id','title','prompt','core','why','example','task','answer','keywords']) {
      assert(typeof lesson[key] === 'string' && lesson[key].trim(), `${lesson.id}: missing ${key}`);
    }
    if (lesson.since !== undefined) {
      assert(typeof lesson.since === 'string' && lesson.since.trim().length >= 2 && lesson.since.length <= 40, `${lesson.id}: invalid since`);
    }
    assert(/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(lesson.id), `Invalid lesson ID: ${lesson.id}`);
    assert(groupOrder[lesson.track]?.includes(lesson.group), `${lesson.id}: unknown track or group`);
    assert(Array.isArray(lesson.points) && lesson.points.length >= 3, `${lesson.id}: needs three knowledge points`);
    assert(lesson.points.every(x => typeof x === 'string' && x.trim().length >= 5), `${lesson.id}: invalid knowledge point`);
    assert.equal(new Set(lesson.points).size, lesson.points.length, `${lesson.id}: duplicate knowledge point`);
    assert(Array.isArray(lesson.references), `${lesson.id}: missing reference status`);
    for (const reference of lesson.references) {
      assert(Array.isArray(reference) && reference.length === 2 && typeof reference[0] === 'string' && reference[0].trim(), `${lesson.id}: invalid reference`);
      assert(typeof reference[1] === 'string' && /^https:\/\//.test(reference[1]), `${lesson.id}: unsafe reference URL`);
      assert(new URL(reference[1]).hostname, `${lesson.id}: invalid reference URL`);
    }
    if (lesson.promptAnswer) {
      assert(typeof lesson.promptAnswer === 'string' && lesson.promptAnswer.trim(), `${lesson.id}: empty promptAnswer`);
    }
    if (lesson.deep) assert(Array.isArray(lesson.deep) && lesson.deep.every(x => typeof x.title === 'string' && x.title.trim() && typeof x.body === 'string' && x.body.trim()), `${lesson.id}: invalid deep dive`);
    if (lesson.map) assert(Array.isArray(lesson.map) && lesson.map.length >= 2 && lesson.map.every(x => typeof x.title === 'string' && x.title.trim() && typeof x.body === 'string' && x.body.trim()), `${lesson.id}: invalid model map`);
    if (lesson.diagram) {
      assert(/^diagrams\/[a-z-]+\.svg$/.test(lesson.diagram), `${lesson.id}: invalid diagram path`);
      const diagramPath = path.join(root, 'curriculum', lesson.diagram);
      assert(fs.existsSync(diagramPath), `${lesson.id}: missing diagram`);
      const diagramBytes = fs.readFileSync(diagramPath);
      try {
        new TextDecoder('utf-8', { fatal: true }).decode(diagramBytes);
      } catch {
        assert.fail(`${lesson.id}: diagram ${lesson.diagram} is not valid UTF-8 (browser will show a broken image)`);
      }
    }
  }
}

function publishedOutline() {
  const outline = { frontend: {}, java: {} };
  for (const track of ['frontend', 'java']) {
    for (const [group, sections] of Object.entries(OUTLINE[track] || {})) {
      const usable = sections.filter((section) => section.title && section.ids.length >= 2);
      if (usable.length >= 2) outline[track][group] = usable;
    }
  }
  return outline;
}

function orderedLead(outline) {
  const lead = {
    frontend: { ...PATH_LEAD.frontend },
    java: { ...PATH_LEAD.java },
  };
  for (const track of ['frontend', 'java']) {
    for (const [group, sections] of Object.entries(outline[track])) {
      lead[track][group] = sections.flatMap((section) => section.ids);
    }
  }
  return lead;
}

export function loadCurriculum() {
const context = { window: {} };
vm.createContext(context);
for (const name of publishedSources) {
  assert(/^[a-z0-9-]+\.js$/.test(name), 'Only explicit curriculum scripts may be published');
  vm.runInContext(fs.readFileSync(path.join(root, 'curriculum', name), 'utf8'), context, { filename: name, timeout: 5000 });
}
const lessons = context.window.LESSONS.map((lesson, index) => ({
  ...lesson,
  ...(LESSON_SINCE[lesson.id] && !lesson.since ? { since: LESSON_SINCE[lesson.id] } : {}),
  _seq: index,
  points: context.window.KNOWLEDGE_POINTS[lesson.id] || [],
  references: context.window.LESSON_REFERENCES[lesson.id] || [],
}));
const outline = publishedOutline();
const pathLead = orderedLead(outline);

lessons.sort((a, b) => {
  if (a.track !== b.track) return a.track === 'frontend' ? -1 : 1;
  const groupDelta =
    GROUP_ORDER[a.track].indexOf(a.group) - GROUP_ORDER[b.track].indexOf(b.group);
  if (groupDelta) return groupDelta;
  const lead = pathLead[a.track]?.[a.group] || [];
  const rank = (item) => {
    const at = lead.indexOf(item.id);
    return at === -1 ? lead.length + item._seq : at;
  };
  return rank(a) - rank(b);
});

const cleaned = polishLessons(
  lessons.map(({ _seq, ...lesson }) => lesson),
  pathLead,
);
validateLessons(cleaned);
for (const track of ['frontend', 'java']) {
  for (const group of GROUP_ORDER[track]) {
    assert(GROUP_LABEL[track]?.[group], `${track} / ${group} needs a short label`);
  }
}
for (const [track, groups] of Object.entries(outline)) {
  for (const [group, sections] of Object.entries(groups)) {
    const seen = new Set();
    for (const section of sections) {
      for (const id of section.ids) {
        assert(!seen.has(id), `${id} is listed in two subdirectories`);
        seen.add(id);
        const lesson = cleaned.find((item) => item.id === id);
        assert(lesson && lesson.track === track && lesson.group === group, `${id} is not in ${track} / ${group}`);
      }
    }
    for (const lesson of cleaned.filter((item) => item.track === track && item.group === group)) {
      assert(seen.has(lesson.id), `${lesson.id} needs a subdirectory in ${group}`);
    }
  }
}
assert.equal(Object.keys(context.window.KNOWLEDGE_POINTS).length, cleaned.length, 'Knowledge point index has missing or stale lessons');
return {
  schemaVersion: 1,
  groupOrder: GROUP_ORDER,
  groupLabels: GROUP_LABEL,
  pathLead,
  outline,
  lessons: cleaned,
};
}
