import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import { loadCurriculum, publishedSources } from './curriculum.mjs';

const curriculum = loadCurriculum();
const generated = JSON.parse(fs.readFileSync(new URL('../web/src/data/curriculum.json', import.meta.url), 'utf8'));
assert.equal(JSON.stringify(generated), JSON.stringify(curriculum), 'Generated curriculum is stale: run npm run export:curriculum in web/');
const html = fs.readFileSync(new URL('../legacy/index.html', import.meta.url), 'utf8');
const loaded = [...html.matchAll(/src="\.\.\/curriculum\/([^"]+)"/g)].map((match) => match[1]);
assert.deepEqual(loaded, publishedSources, 'legacy/index.html must load the publication manifest in order');
assert.equal(publishedSources.includes('coverage-frontend-07.js'), true);
assert.equal(publishedSources.includes('coverage-java-07.js'), true);
assert.equal(publishedSources.includes('coverage-java-08.js'), true);
assert.equal(publishedSources.includes('coverage-frontend-08.js'), true);
assert.equal(publishedSources.includes('coverage-java-09.js'), true);
assert.equal(publishedSources.includes('coverage-frontend-09.js'), true);
assert.equal(publishedSources.includes('coverage-frontend-10.js'), true);
assert.equal(publishedSources.includes('coverage-frontend-11.js'), true);
assert.equal(publishedSources.includes('coverage-frontend-12.js'), true);
assert.equal(publishedSources.includes('coverage-frontend-13.js'), true);
assert.equal(publishedSources.includes('coverage-frontend-14.js'), true);
assert.equal(publishedSources.includes('coverage-java-10.js'), true);
assert.equal(publishedSources.includes('coverage-java-11.js'), true);
assert.equal(publishedSources.includes('coverage-java-12.js'), true);
assert.equal(publishedSources.includes('coverage-java-13.js'), true);
assert.equal(publishedSources.includes('coverage-java-14.js'), true);
assert.equal(publishedSources.includes('coverage-java-15.js'), true);
assert.equal(publishedSources.includes('coverage-java-16.js'), true);
assert.equal(publishedSources.includes('coverage-java-17.js'), true);
assert.equal(publishedSources.includes('coverage-java-18.js'), true);
assert.equal(publishedSources.includes('coverage-java-19.js'), true);
assert.equal(publishedSources.includes('coverage-java-20.js'), true);
assert.equal(publishedSources.includes('coverage-java-21.js'), true);
assert.equal(publishedSources.includes('coverage-java-22.js'), true);
assert.equal(publishedSources.includes('coverage-java-23.js'), true);
assert.equal(publishedSources.includes('coverage-java-24.js'), true);
assert.equal(publishedSources.includes('coverage-java-25.js'), true);
assert.equal(publishedSources.includes('coverage-java-26.js'), true);
assert.equal(publishedSources.includes('coverage-java-27.js'), true);
assert.equal(publishedSources.includes('coverage-java-28.js'), true);
assert.equal(publishedSources.includes('coverage-java-29.js'), true);
assert.equal(publishedSources.includes('coverage-java-30.js'), true);
assert.equal(publishedSources.includes('coverage-path-07.js'), true);
assert.equal(publishedSources.includes('coverage-path-08.js'), true);
assert.equal(publishedSources.includes('coverage-path-09.js'), true);
assert.equal(publishedSources.includes('foundation-points.js'), true);
assert.equal(publishedSources.includes('coverage-chapters-10.js'), true);
assert.equal(publishedSources.includes('coverage-sca-12.js'), true);
assert.equal(publishedSources.includes('coverage-infra-13.js'), true);
assert.equal(publishedSources.includes('answer-walkthrough.js'), true);
assert.equal(publishedSources.includes('coverage-depth-14.js'), true);
assert.equal(publishedSources.includes('coverage-ship-15.js'), true);
assert.equal(publishedSources.includes('coverage-core-16.js'), true);
assert.equal(publishedSources.includes('coverage-ops-17.js'), true);
const orderContext = { window: {} };
vm.runInContext(fs.readFileSync(new URL('../legacy/publication-order.js', import.meta.url), 'utf8'), vm.createContext(orderContext));
assert.equal(JSON.stringify(orderContext.window.GROUP_ORDER), JSON.stringify(curriculum.groupOrder));
assert.equal(JSON.stringify(orderContext.window.PATH_LEAD), JSON.stringify(curriculum.pathLead));
const lessons = curriculum.lessons;
console.log(`${lessons.length} lessons / ${lessons.reduce((n,x) => n+x.points.length,0)} knowledge points; export matches the publication manifest.`);
